{
  "hash": "964594b9ca727738829dd96cf7005885",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3 Exercises: Non-Linear Change\"\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n# Cognitive Task Performance\n\n:::frame\n__Dataset: Az.rda__  \n  \nThese data are available at [https://uoepsy.github.io/data/Az.rda](https://uoepsy.github.io/data/Az.rda). You can load the dataset using:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nload(url(\"https://uoepsy.github.io/data/Az.rda\"))\n```\n:::\n\n\n\nand you will find the `Az` object in your environment.  \n\nThe `Az` object contains information on 30 Participants with probable Alzheimer's Disease, who completed 3 tasks over 10 time points: A memory task, and two scales investigating ability to undertake complex activities of daily living (cADL) and simple activities of daily living (sADL). Performance on all of tasks was calculated as a percentage of total possible score, thereby ranging from 0 to 100. \n\nWe're interested in *whether performance on these tasks differed at the outset of the study, and if they differed in their subsequent change in performance*.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rncpybllzw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rncpybllzw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rncpybllzw thead, #rncpybllzw tbody, #rncpybllzw tfoot, #rncpybllzw tr, #rncpybllzw td, #rncpybllzw th {\n  border-style: none;\n}\n\n#rncpybllzw p {\n  margin: 0;\n  padding: 0;\n}\n\n#rncpybllzw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rncpybllzw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rncpybllzw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rncpybllzw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rncpybllzw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rncpybllzw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rncpybllzw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rncpybllzw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rncpybllzw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rncpybllzw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rncpybllzw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rncpybllzw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rncpybllzw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rncpybllzw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rncpybllzw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rncpybllzw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rncpybllzw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rncpybllzw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rncpybllzw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rncpybllzw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rncpybllzw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rncpybllzw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rncpybllzw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rncpybllzw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rncpybllzw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rncpybllzw .gt_left {\n  text-align: left;\n}\n\n#rncpybllzw .gt_center {\n  text-align: center;\n}\n\n#rncpybllzw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rncpybllzw .gt_font_normal {\n  font-weight: normal;\n}\n\n#rncpybllzw .gt_font_bold {\n  font-weight: bold;\n}\n\n#rncpybllzw .gt_font_italic {\n  font-style: italic;\n}\n\n#rncpybllzw .gt_super {\n  font-size: 65%;\n}\n\n#rncpybllzw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rncpybllzw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rncpybllzw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rncpybllzw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rncpybllzw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rncpybllzw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rncpybllzw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rncpybllzw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rncpybllzw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Subject</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Unique Subject Identifier</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Time</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Time point of the study (1 to 10)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Task</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Task type (Memory, cADL, sADL)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Performance</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Score on test (range 0 to 100)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nLoad in the data and examine it.  \nHow many participants, how many observations per participant, per task?  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nload(url(\"https://uoepsy.github.io/data/Az.rda\"))\nsummary(Az)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Subject         Time          Task      Performance   \n 1      : 30   Min.   : 1.0   cADL  :300   Min.   : 2.00  \n 2      : 30   1st Qu.: 3.0   sADL  :300   1st Qu.:40.00  \n 3      : 30   Median : 5.5   Memory:300   Median :52.00  \n 4      : 30   Mean   : 5.5                Mean   :49.27  \n 5      : 30   3rd Qu.: 8.0                3rd Qu.:61.00  \n 6      : 30   Max.   :10.0                Max.   :85.00  \n (Other):720                                              \n```\n\n\n:::\n:::\n\n\n\n\n30 participants: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlength(unique(Az$Subject))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n:::\n\n\n\n\nDoes every participant have 10 datapoints for each Task type?  Yes!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nany( table(Az$Subject, Az$Task) != 10 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nNo modelling just yet.  \n\nPlot the performance over time for each type of task.  \n\nTry using `stat_summary` so that you are plotting the means (and standard errors) of each task, rather than every single data point. Why? Because this way you can get a shape of the average trajectories of performance over time in each task.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nFor an example plot, see [Chapter 6: polynomial growth #example-in-mlm](https://uoepsy.github.io/lmm/06_poly.html#example-in-mlm){target=\"_blank\"}.\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\nYou can use \"pointranges\", or \"line\" and \"ribbon\".  \n`stat_summary` will take the data and for each value of `x` calculate some function (in this case the mean, or the mean and SE):  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(Az, aes(Time, Performance, color=Task, fill=Task)) + \n  stat_summary(fun.data=mean_se, geom=\"ribbon\", color=NA, alpha=0.5) +\n  stat_summary(fun=mean, geom=\"line\")\n```\n\n::: {.cell-output-display}\n![](03ex_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nWhy do you think *raw/natural* polynomials might be more useful than *orthogonal* polynomials for these data?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nAre we somewhat interested in group differences (i.e. differences in scores, or differences in rate of change) at *a specific point* in time?  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\nBecause we're interested in whether there are task differences at the starting point, raw polynomials are probably what we want here.  \n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nRe-center the Time variable so that the intercept is the first timepoint.  \n  \nThen choose an appropriate degree of polynomial (if any), and fit a full model that allows us to address the research aims.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nNote there is no part of the research question that specifically asks about how \"gradual\" or \"quick\" the change is (which would suggest we are interested in the quadratic term).  \n\nHowever, plots (summarised at the task level, and of individual participant's data separately) can help to give us a sense of what degree of polynomial terms might be suitable to succinctly describe the trends.  \n\nIn many cases, fitting higher and higher order polynomials will likely result in a 'better fit' to our sample data, but these will be worse and worse at generalising to new data - i.e. we run the risk of *overfitting*.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  1 - how many polynomials?</button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\nIn our plot, there were 2 straight line and one slightly curvy one. It wasn't S-shaped or 'wiggly' or anything, there was just a bit of a bend in it, which suggests that the quadratic term could be a good approximation here.   \n\nIt's worth also looking at the individual participant trajectories. In these we can also see the curvi-ness of the blue line - it's more pronounced for some people than others, but it does seem like individual's trajectories on the Memory task may be curvilinear. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(Az, aes(Time, Performance, color=Task, fill=Task)) + \n  stat_summary(fun.data=mean_se, geom=\"ribbon\", color=NA, alpha=0.5) +\n  stat_summary(fun=mean, geom=\"line\")+\n  facet_wrap(~Subject)\n```\n\n::: {.cell-output-display}\n![](03ex_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lme4)\nAz <- Az |> mutate(\n  Time1 = Time-1,\n  poly1 = poly(Time1,2,raw=T)[,1],\n  poly2 = poly(Time1,2,raw=T)[,2]\n)\n```\n:::\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Or using Dan's code:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# import Dan's code:\nsource(\"https://uoepsy.github.io/msmr/functions/code_poly.R\")\n\n# this also produces a nice little plot to show the polynomials\nAz$Time1 <- Az$Time-1\nAz <- code_poly(df = Az, predictor = 'Time1',\n                poly.order = 2, orthogonal = FALSE)\n```\n:::\n\n\n\n\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  2 - fixed effects</button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\nWe're interested in how performance changes over time, but we have `poly1` and `poly2` for time, so we're at:  \n```\nlmer(Performance ~ poly1 + poly2 ... \n```\n\nOur research aims are to investigate differences between task performance (both at baseline and change over time). So we want to interact time with task:  \n```\nlmer(Performance ~ (poly1 + poly2)*Task ... \n```\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  3 - grouping structure</button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(Az)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Subject Time Task Performance Time1 poly1 poly2\n1       1    1 cADL          65     0     0     0\n2       1    2 cADL          61     1     1     1\n3       1    3 cADL          53     2     2     4\n4       1    4 cADL          46     3     3     9\n5       1    5 cADL          42     4     4    16\n6       1    6 cADL          35     5     5    25\n```\n\n\n:::\n:::\n\n\n\n\nWe have 900 observations, and 30 for each participant.  \n\n```\nlmer(Performance ~ (poly1 + poly2)*Task ... +\n                   (1 + .... | Subject)\n```\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Fixed vs Random\n\nWe can account for group differences in models either by estimating group differences, or by estimating variance between groups:  \n\n- group as a fixed effect (`y ~ 1 + group`) = groups differ in $y$ by $b_1, b_2, ..., b_k$  \n- group as a random effect (`y ~ 1 + (1|group)`) = groups vary in $y$ with a standard deviation of $\\sigma_0$   \n\nOne way to think about whether a group is best in the random effects part or in the fixed part of our model is to think about \"what would happen if I repeated the experiment?\"  \n\n**Should variable `g` be fixed or random?**\n\n|  | Repetition: <br> _If the experiment were repeated:_ | Desired inference: <br> _The conclusions refer to:_ | \n|----------------|--------------------------------------------------|----------------------------------------------------|\n| Fixed<br>$y\\,\\sim\\,~\\,...\\, +\\, g$  | Same groups would be used   |    The groups used  |\n| Random<br>$y\\,\\sim\\,...\\,+\\,(\\,... |\\,g)$ | Different groups would be used   | A population from which the groups used are just a (random) sample |\n\n\nPractical points:  \n- Sometimes there isn't enough variability between groups to model as random effects (i.e. the variance gets estimated as too close to zero).\n- Sometimes you might not have sufficient number of groups to model as random effects (e.g. for groups of fewer than c8 things, estimates of the variance are often not a reliable reflection of the population).\n\n\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  4 - random effects</button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\nWhat slopes could vary by participant? \n\n__Q:__ Could participants vary in their performance over time?  \n__A:__ Yes, `(poly1 + poly2 | Subject)`  \n__Q:__ Could participants vary in how performance differs between Tasks?  \n__A:__ Yes, `(poly1 + poly2 + Task | Subject)`. E.g., Some participants might be much better at the memory task than other tasks, some might be better at the other tasks.  \n__Q:__ Could participants vary in how tasks differ in their performance over time?  \n__A:__ Yes, `((poly1 + poly2)*Task | Subject)`. E.g., For some participants, memory could decline more than cADL, for other participants it could decline less.  \n\n```\nlmer(Performance ~ (poly1 + poly2)*Task ... +\n                   (1 + (poly1 + poly2)*Task | Subject)\n```\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-8' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  5 - the model</button></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\n\n_small note: I'm using the bobyqa optimizer here because it tends to be slightly quicker than the default._  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1 = lmer(Performance ~ (poly1 + poly2) * Task +\n            (1 + (poly1 + poly2) * Task | Subject),\n          data=Az, control=lmerControl(optimizer = \"bobyqa\"))\n```\n:::\n\n\n\n<p style=\"color:red;font-size:.8em\">\nboundary (singular) fit: see help('isSingular')<br>\nWarning messages:<br>\n1: In commonArgs(par, fn, control, environment()) :<br>\n  maxfun < 10 * length(par)^2 is not recommended.<br>\n2: In optwrap(optimizer, devfun, getStart(start, rho\\$pp), lower = rho\\$lower,  :<br>\n  convergence code 1 from bobyqa: bobyqa -- maximum number of function evaluations exceeded\n</p>\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nOkay, so the model didn't converge.  It's trying to estimate __a lot__ of things in the random effects (even though it didn't converge, try looking at `VarCorr(model)` to see all the covariances it is trying to estimate).  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Categorical random effects on the RHS\n\nWhen we have a categorical random effect (i.e. where the `x` in `(1 + x | g)` is a categorical variable), then model estimation can often get tricky, because \"the effect of x\" for a categorical variable with $k$ levels is identified via $k-1$ parameters, meaning we have a lot of variances and covariances to estimate when we include `x|g`.  \n\n:::: {.columns}\n:::{.column width=\"45%\"}\n\nWhen `x` is numeric:  \n\n```\nGroups   Name        Std.Dev. Corr  \ng        (Intercept) ...        \n         x           ...      ...\nResidual             ...     \n```\n\n:::\n:::{.column width=\"10%\"}\n\n:::\n:::{.column width=\"45%\"}\n\nWhen `x` is categorical with $k$ levels:  \n\n```\nGroups   Name        Std.Dev. Corr  \ng        (Intercept) ...        \n         xlevel2     ...      ...\n         xlevel3     ...      ...     ...\n         ...         ...      ...     ...     ...\n         xlevelk     ...      ...     ...     ...   ...\nResidual             ...     \n```\n\n:::\n::::\n\nHowever, we can use an alternative formation of the random effects by putting a categorical `x` into the right-hand side:  \nInstead of `(1 + x | g)` we can fit `(1 | g) + (1 | g:x)`.   \n\nThe symbol `:` in `g:x` is used to refer to the combination of `g` and `x`.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n      g        x     g:x\n1    p1        a    p1.a\n2    p1        a    p1.a\n3    p1        b    p1.b\n4   ...      ...     ...\n5    p2        a    p2.a\n6    p2        b    p2.b\n7   ...      ...     ...\n```\n\n\n:::\n:::\n\n\n\n\nIt's a bit weird to think about it, but these two formulations of the random effects can kind of represent the same idea:  \n\n- `(1 + x | g)`:  each group of `g` can have a different intercept and a different effect of `x`  \n- `(1 | g) + (1 | g:x)`: each group of `g` can have a different intercept, and each level of x within each `g` can have a different intercept.  \n\nBoth of these allow the outcome `y` to change across `x` differently for each group in `g` (i.e. both of them result in `y` being different for each level of `x` in each group `g`).  \nThe first does so explicitly by estimating the group level variance of the `y~x` effect.  \nThe second one estimates the variance of $y$ between groups, and also the variance of $y$ between 'levels of x within groups'. In doing so, it achieves more or less the same thing, but by capturing these as intercept variances between levels of `x`, we don't have to worry about lots of covariances:  \n\n\n:::: {.columns}\n:::{.column width=\"45%\"}\n`(1 + x | g)`  \n\n```\nGroups   Name        Std.Dev. Corr  \ng        (Intercept) ...        \n         xlevel2     ...      ...\n         xlevel3     ...      ...     ...\n         ...         ...      ...     ...     ...\n         xlevelk     ...      ...     ...     ...   ...\nResidual             ...     \n```\n\n:::\n:::{.column width=\"10%\"}\n\n:::\n:::{.column width=\"45%\"}\n`(1 | g) + (1 | g:x)`  \n\n\n```\nGroups   Name        Std.Dev. \ng        (Intercept) ...        \ng.x      (Intercept) ...        \nResidual             ...     \n```\n\n:::\n::::\n\n:::\n\n\nTry adjusting your model by first moving `Task` to the right hand side of the random effects, and from there starting to simplify things (remove random slopes one-by-one) \n\n**This is our first experience of our random effect structures becoming more complex than simply `(.... | group)`. This is going to feel confusing, but don't worry, we'll see more structures like this next week.**    \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n`... + (1 + poly1 + poly2 | Subject) + (1 + poly1 + poly2 | Subject:Task)`  \n\nTo then start simplifying (if this model doesn't converge), it can be helpful to look at the `VarCorr()` of the non-converging model to see if anything looks awry. Look for small variances, perfect (or near perfect) correlations. These might be sensible things to remove.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-9' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\nHere's our model with subject-task effects on the right hand side.  \nAgain we have problems, as we have a singular fit:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm2 = lmer(Performance ~ (poly1 + poly2) * Task +\n            (1 + poly1 + poly2 | Subject) +\n            (1 + poly1 + poly2 | Subject:Task),\n          data=Az, control=lmerControl(optimizer = \"bobyqa\"))\n```\n:::\n\n\n\n<p style=\"color:red;font-size:.8em\">boundary (singular) fit: see help('isSingular')</p>\n\nLooking at the random effects of our model, note that the `poly2|Subject` random effect has very little variance (and high correlations).  \nNote that it makes sense that by including the random effects for `Subject:Task`, there might not be much above that leftover in `Subject` random effects. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nVarCorr(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups       Name        Std.Dev. Corr         \n Subject:Task (Intercept) 3.100837              \n              poly1       0.923485  0.275       \n              poly2       0.052644 -0.329  0.021\n Subject      (Intercept) 3.461349              \n              poly1       1.565908 -0.177       \n              poly2       0.007638  0.075 -0.995\n Residual                 1.019574              \n```\n\n\n:::\n:::\n\n\n\n\n\nWhen we remove it, our model converges!!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm3 = lmer(Performance ~ (poly1 + poly2) * Task +\n            (1 + poly1 | Subject) +\n            (1 + poly1 + poly2 | Subject:Task),\n          data=Az, control=lmerControl(optimizer = \"bobyqa\"))\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\n\nConduct a series of model comparisons investigating whether \n\n1. Tasks differ only in their linear change  \n2. Tasks differ in their quadratic change  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nRemember, these sorts of model comparisons are being used to isolate and test part of the fixed effects (we're interested in the how the average participant performs over the study). So our models want to have the same random effect structure, but different fixed effects.  \n\nSee the end of [Chapter 6: polynomial growth #example-in-mlm](https://uoepsy.github.io/lmm/06_poly.html#example-in-mlm){target=\"_blank\"}.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-10' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\nAs I'm comparing these with a likelihood ratio test, I'll fit them with `REML=FALSE`\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm3int = lmer(Performance ~ poly1 + poly2 + Task + \n            (1 + poly1 | Subject) +\n            (1 + poly1 + poly2 | Subject:Task),\n            REML = FALSE,\n          data=Az, control=lmerControl(optimizer = \"bobyqa\"))\n\nm3lin = lmer(Performance ~ poly1*Task + poly2 +\n            (1 + poly1 | Subject) +\n            (1 + poly1 + poly2 | Subject:Task),\n            REML = FALSE,\n          data=Az, control=lmerControl(optimizer = \"bobyqa\"))\n\nm3full = lmer(Performance ~ (poly1 + poly2) * Task +\n            (1 + poly1 | Subject) +\n            (1 + poly1 + poly2 | Subject:Task),\n            REML = FALSE,\n          data=Az, control=lmerControl(optimizer = \"bobyqa\"))\n\nanova(m3int, m3lin, m3full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: Az\nModels:\nm3int: Performance ~ poly1 + poly2 + Task + (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)\nm3lin: Performance ~ poly1 * Task + poly2 + (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)\nm3full: Performance ~ (poly1 + poly2) * Task + (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)\n       npar    AIC    BIC  logLik deviance   Chisq Df Pr(>Chisq)    \nm3int    15 3801.8 3873.8 -1885.9   3771.8                          \nm3lin    17 3775.4 3857.0 -1870.7   3741.4  30.413  2  2.488e-07 ***\nm3full   19 3607.8 3699.1 -1784.9   3569.8 171.532  2  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n:::int\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\nThe linear change over time differs between Tasks ($\\chi^2(2) = 30.41, p < 0.001).  \nThe quadratic change over time differs between Tasks ($\\chi^2(2) = 171.53, p < 0.001).  \n\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nGet some confidence intervals and provide an interpretation of each coefficient from the full model.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-11' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\nAs we've used likelihood ratio tests above, we'll get some profile likelihood confidence intervals for our parameters.  \n__note this took me about 4 mins to run__  \nIf you want to get some quicker (slightly less robust) confidence intervals, then switch `\"profile\"` to `\"Wald\"`.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconfint(m3full, method=\"profile\", parm=\"beta_\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"smyanfqnto\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#smyanfqnto table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#smyanfqnto thead, #smyanfqnto tbody, #smyanfqnto tfoot, #smyanfqnto tr, #smyanfqnto td, #smyanfqnto th {\n  border-style: none;\n}\n\n#smyanfqnto p {\n  margin: 0;\n  padding: 0;\n}\n\n#smyanfqnto .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#smyanfqnto .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#smyanfqnto .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#smyanfqnto .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#smyanfqnto .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#smyanfqnto .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#smyanfqnto .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#smyanfqnto .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#smyanfqnto .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#smyanfqnto .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#smyanfqnto .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#smyanfqnto .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#smyanfqnto .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#smyanfqnto .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#smyanfqnto .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#smyanfqnto .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#smyanfqnto .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#smyanfqnto .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#smyanfqnto .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#smyanfqnto .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#smyanfqnto .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#smyanfqnto .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#smyanfqnto .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#smyanfqnto .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#smyanfqnto .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#smyanfqnto .gt_left {\n  text-align: left;\n}\n\n#smyanfqnto .gt_center {\n  text-align: center;\n}\n\n#smyanfqnto .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#smyanfqnto .gt_font_normal {\n  font-weight: normal;\n}\n\n#smyanfqnto .gt_font_bold {\n  font-weight: bold;\n}\n\n#smyanfqnto .gt_font_italic {\n  font-style: italic;\n}\n\n#smyanfqnto .gt_super {\n  font-size: 65%;\n}\n\n#smyanfqnto .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#smyanfqnto .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#smyanfqnto .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#smyanfqnto .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#smyanfqnto .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#smyanfqnto .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#smyanfqnto .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#smyanfqnto .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#smyanfqnto div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"est\">est</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI\">CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interpretation\">interpretation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"est\" class=\"gt_row gt_right\">63.88</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[62.19, 65.57]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated score on the cADL task at baseline</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">poly1</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-3.27</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-3.93, -2.61]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated linear change in cADL scores from baseline</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">poly2</td>\n<td headers=\"est\" class=\"gt_row gt_right\">0.01</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.02, 0.03]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">no significant curvature to the cADL trajectory</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">TasksADL</td>\n<td headers=\"est\" class=\"gt_row gt_right\">1.44</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.18, 3.06]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">no significant difference between sADL and cADL tasks at baseline</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">TaskMemory</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-2.40</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-4.02, -0.78]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">at baseline, scores on memory task are 2.4 lower than cADL</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">poly1:TasksADL</td>\n<td headers=\"est\" class=\"gt_row gt_right\">1.34</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[0.82, 1.85]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">performance on sADL task is not decreasing from baseline as much as performance on cADL</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">poly1:TaskMemory</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-3.30</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-3.81, -2.78]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">performance on Memory task is decreasing (linearly) more than performance on cADL</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">poly2:TasksADL</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-0.01</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.05, 0.02]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">no significant difference between quadratic change of sADL from that of cADL</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">poly2:TaskMemory</td>\n<td headers=\"est\" class=\"gt_row gt_right\">0.34</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[0.3, 0.37]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">significant difference in quadratic change between performance on Memory vs performance on cADL</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n#### some tables of predictions (in case they help)\n\nTo get a sense of the quadratic term 'in action', think about the predictions across time for each task: \n\nFor cADL, this is just the linear change. Every timepoint, performance decreases by 3.27.  \n\n| timepoint | cADL |\n| ---- | ---- |\n| prediction formula | $63.88 + (-3.27 \\times time) + (0.01 \\times time^2)$ |\n| prediction formula<br><small>(with non-sig terms removed)</small> | $63.88 + (-3.27 \\times time)$ |\n| 0 | $63.88 + (-3.27 \\times 0) = 63.88$ |\n| 1 | $63.88 + (-3.27 \\times 1) = 60.61$ |\n| 2 | $63.88 + (-3.27 \\times 2) = 57.34$ |\n| 3 | $63.88 + (-3.27 \\times 3) = 54.07$ |\n\n\nFor sADL, the additional change is +1.34, so at every timepoint performance decreases by -1.93 (this is -3.27+1.34)    \n\n| timepoint | sADL |\n| ---- | ---- |\n| prediction formula | $63.88 + (-3.27 \\times time) + (0.01 \\times time^2) +$ $(1.44) + (1.34 \\times time) + (-0.01 \\times time^2)$ |\n| prediction formula<br><small>(with non-sig terms removed)</small> | $63.88 + (-3.27 \\times time) + (1.34 \\times time)$ |\n| 0 | $63.88 + (-3.27 \\times 0) + (1.34 \\times 0) = 63.88$ |\n| 1 | $63.88 + (-3.27 \\times 1) + (1.34 \\times 1) = 61.95$ |\n| 2 | $63.88 + (-3.27 \\times 2)+ (1.34 \\times 2)  = 60.02$ |\n| 3 | $63.88 + (-3.27 \\times 3)+ (1.34 \\times 3) = 58.09$ |\n\n\nFor the Memory task, the quadratic term is in play. at every timepoint performance decreases by $-3.27-3.30 +(0.34 \\times time^2)$. So for low timepoints, the quadratic term doesn't make much of a difference as it does for bigger time points.  \n\n| timepoint | Memory |\n| ---- | ---- |\n| prediction formula | $63.88 + (-3.27 \\times time) + (0.01 \\times time^2) +$ $(-2.40) + (-3.30 \\times time) + (0.34 \\times time^2)$ |\n| prediction formula<br><small>(with non-sig terms removed)</small> | $63.88 + (-3.27 \\times time) +$ $(-2.40) + (-3.30 \\times time) + (0.34 \\times time^2)$ |\n| 0 | $63.88 + (-3.27 \\times 0) +$ $(-2.40) + (-3.30 \\times 0) + (0.34 \\times 0^2) = 61.48$ |\n| 1 | $63.88 + (-3.27 \\times 1) +$ $(-2.40) + (-3.30 \\times 1) + (0.34 \\times 1^2) = 55.25$ |\n| 2 | $63.88 + (-3.27 \\times 2) +$ $(-2.40) + (-3.30 \\times 2) + (0.34 \\times 2^2) = 49.70$ |\n| 3 | $63.88 + (-3.27 \\times 3) +$ $(-2.40) + (-3.30 \\times 3) + (0.34 \\times 3^2) = 44.83$ |\n| ... | ... |\n| 9 | $63.88 + (-3.27 \\times 9) +$ $(-2.40) + (-3.30 \\times 9) + (0.34 \\times 9^2) = 29.89$ |\n| 10 | $63.88 + (-3.27 \\times 10) +$ $(-2.40) + (-3.30 \\times 10) + (0.34 \\times 10^2) = 29.78$ |\n\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nTake a piece of paper, and based on your interpretation for the previous question, sketch out the model estimated trajectories for each task.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-12' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-12', 'sol-start-12')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-12\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03ex_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nMake a plot showing both the average performance and the average model predicted performance across time.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-13' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-13', 'sol-start-13')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-13\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(broom.mixed)\naugment(m3) |>\n  ggplot(aes(x=poly1,col=Task))+\n  stat_summary(aes(y=Performance), geom=\"pointrange\") + \n  stat_summary(aes(y=.fitted), geom=\"line\")\n```\n\n::: {.cell-output-display}\n![](03ex_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<!-- # Polynomials and overfitting -->\n\n<!-- :::frame -->\n<!-- Two quotes -->\n\n<!-- \"all models are wrong. some are useful.\" [(George Box, 1976)](https://www.tandfonline.com/doi/abs/10.1080/01621459.1976.10480949).   -->\n\n<!-- \"...it does not seem helpful just to say that all models are wrong. The very word model implies simplification and idealization. The idea that complex physical, biological or sociological systems can be exactly described by a few formulae is patently absurd. The construction of idealized representations that capture important stable aspects of such systems is, however, a vital part of general scientific analysis and statistical models, especially substantive ones, do not seem essentially different from other kinds of model.\" (Sir David Cox, 1995).   -->\n\n<!-- ::: -->\n\n",
    "supporting": [
      "03ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}