{
  "hash": "568b817bb0d470fddd0c6e5f84a60963",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 1 Exercises: Intro to MLM\"\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n\n\n::: {.callout-note collapse=\"false\"}\n#### New Packages!\n\nThese are the main packages we're going to use in this block. It might make sense to install them now *if you do not have them already*\n\n+ __tidyverse__ : for organising data  \n+ __lme4__ : for fitting generalised linear mixed effects models\n+ __broom.mixed__ : tidying methods for mixed models\n+ __effects__ : for tabulating and graphing effects in linear models\n+ __lmerTest__: for quick p-values from mixed models\n+ __parameters__: various inferential methods for mixed models\n\n:::\n\n\n# Getting to grips with MLM\n\n:::lo\nThese first set of exercises are not \"how to do analyses with multilevel models\" - they are designed to get you thinking, and help with an understanding of how these models work.  \n:::\n\n\n:::frame\n__Data: New Toys!__  \n  \nRecall the example from last semesters' USMR course, where the lectures explored linear regression with a toy dataset of how practice influences the reading age of toy characters (see [USMR Week 7 Lecture](https://uoepsy.github.io/usmr/2324/lectures/lecture06.html#/learning-to-read-1){target=\"_blank\"}). We're going to now broaden our scope to the investigation of how practice affects reading age for **all** toys (not just Martin's Playmobil characters).  \n\nYou can find a dataset at [https://uoepsy.github.io/data/toy2.csv](https://uoepsy.github.io/data/toy2.csv){target=\"_blank\"} containing information on 129 different toy characters that come from a selection of different families/types of toy. You can see the variables in the table below^[Image sources:<br>http://tophatsasquatch.com/2012-tmnt-classics-action-figures/<br>https://www.dezeen.com/2016/02/01/barbie-dolls-fashionista-collection-mattel-new-body-types/<br>https://www.wish.com/product/5da9bc544ab36314cfa7f70c<br>https://www.worldwideshoppingmall.co.uk/toys/jumbo-farm-animals.asp<br>https://www.overstock.com/Sports-Toys/NJ-Croce-Scooby-Doo-5pc.-Bendable-Figure-Set-with-Scooby-Doo-Shaggy-Daphne-Velma-and-Fred/28534567/product.html<br>https://tvtropes.org/pmwiki/pmwiki.php/Toys/Furby<br>https://www.fun.com/toy-story-4-figure-4-pack.html<br>https://www.johnlewis.com/lego-minifigures-71027-series-20-pack/p5079461].  \n<br>  \n\n:::: {.columns}\n::: {.column width=\"45%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/toys.png){fig-align='center' width=300px}\n:::\n:::\n\n\n\n:::\n::: {.column width=\"10%\"}\n:::\n::: {.column width=\"45%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"shsghwnkrd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#shsghwnkrd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#shsghwnkrd thead, #shsghwnkrd tbody, #shsghwnkrd tfoot, #shsghwnkrd tr, #shsghwnkrd td, #shsghwnkrd th {\n  border-style: none;\n}\n\n#shsghwnkrd p {\n  margin: 0;\n  padding: 0;\n}\n\n#shsghwnkrd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#shsghwnkrd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#shsghwnkrd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#shsghwnkrd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#shsghwnkrd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#shsghwnkrd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#shsghwnkrd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#shsghwnkrd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#shsghwnkrd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#shsghwnkrd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#shsghwnkrd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#shsghwnkrd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#shsghwnkrd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#shsghwnkrd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#shsghwnkrd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shsghwnkrd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#shsghwnkrd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#shsghwnkrd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#shsghwnkrd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shsghwnkrd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#shsghwnkrd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shsghwnkrd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#shsghwnkrd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shsghwnkrd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shsghwnkrd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shsghwnkrd .gt_left {\n  text-align: left;\n}\n\n#shsghwnkrd .gt_center {\n  text-align: center;\n}\n\n#shsghwnkrd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#shsghwnkrd .gt_font_normal {\n  font-weight: normal;\n}\n\n#shsghwnkrd .gt_font_bold {\n  font-weight: bold;\n}\n\n#shsghwnkrd .gt_font_italic {\n  font-style: italic;\n}\n\n#shsghwnkrd .gt_super {\n  font-size: 65%;\n}\n\n#shsghwnkrd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#shsghwnkrd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#shsghwnkrd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#shsghwnkrd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#shsghwnkrd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#shsghwnkrd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#shsghwnkrd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#shsghwnkrd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#shsghwnkrd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">toy_type</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Type of Toy</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">year</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Year Released</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">toy</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Character</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">hrs_week</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Hours of practice per week</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">R_AGE</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Reading Age</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n:::\n::::\n\n:::\n\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nBelow is some code that fits a model of \"reading age\" (`R_AGE`) predicted by hours of practice (`hrs_week`). Line 2 then gets the 'fitted' values from the model and adds them as a new column to the dataset, called `pred_lm`. The fitted values are what the model predicts for every individual observation (every individual toy in our dataset).  \n\nLines 4-7 then plot the data, split up by each type of toy, and adds lines showing the model fitted values.  \n\nRun the code and check that you get a plot. What do you notice about the lines?  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nlm_mod <- lm(R_AGE ~ hrs_week, data = toy2)\ntoy2$pred_lm <- predict(lm_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_lm), col = \"red\")\n```\n:::\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\nWe should get something like this:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm_mod <- lm(R_AGE ~ hrs_week, data = toy2)\ntoy2$pred_lm <- predict(lm_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_lm), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nNote that the lines are exactly the same for each type of toy. This makes total sense, because the model (which is where we've got the lines from) completely _ignores_ the `toy_type` variable!  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\n\nBelow are 3 more code chunks that all 1) fit a model, then 2) add the fitted values of that model to the plot.  \n\nThe first model is a 'no-pooling' approach, where we use tools learned in USMR and simply add in `toy_type` as a predictor in the model to estimate all the differences between types of toys.\n\nThe second and third are multilevel models. The second fits random intercepts by-toytype, and the third fits random intercepts and slopes of `hrs_week`  \n\nCopy each chunk and run through the code. Pay attention to how the lines differ.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nfe_mod <- lm(R_AGE ~ toy_type + hrs_week, data = toy2)\ntoy2$pred_fe <- predict(fe_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_fe), col = \"blue\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(lme4)\nri_mod <- lmer(R_AGE ~ hrs_week + (1 | toy_type), data = toy2)\ntoy2$pred_ri <- predict(ri_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_ri), col = \"green\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nrs_mod <- lmer(R_AGE ~ hrs_week + (1 + hrs_week | toy_type), data = toy2)\ntoy2$pred_rs <- predict(rs_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_rs), col = \"orange\")\n```\n:::\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\nThe first model has an adjustment for each toy-type (we can see this in the coefficients if we want). What this means is that the line for each type of toy is shifted up or down. We can see that the lines are now shifted up for things like \"Scooby Doo\" and \"G.I.Joe\", and down for \"transformers\" and \"farm animals\":  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfe_mod <- lm(R_AGE ~ toy_type + hrs_week, data = toy2)\ntoy2$pred_fe <- predict(fe_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_fe), col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\nThis next one _looks_ very similar to the previous one, but it is conceptually doing something a bit different. Rather than separating out and estimating differences between all the toy-types, we are modelling _a distribution_ of deviations for each type from some average.  \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nri_mod <- lmer(R_AGE ~ hrs_week + (1 | toy_type), data = toy2)\ntoy2$pred_ri <- predict(ri_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_ri), col = \"green\")\n```\n\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nFinally, we can add in the random slopes of `hrs_week`. In this model, we are not only allowing toy-types to vary in their average reading age (i.e. shifting lines up and down), but we are also allowing them to vary in the association between hrs_week and reading age (letting the lines have different slopes). Some types of toy (Scooby Doo, Sock Puppets, Stretch Armstrong) have fairly positive slopes, and some have a flatter association (e.g, SuperZings etc).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrs_mod <- lmer(R_AGE ~ hrs_week + (1 + hrs_week | toy_type), data = toy2)\ntoy2$pred_rs <- predict(rs_mod)\n\nggplot(toy2, aes(x = hrs_week)) + \n  geom_point(aes(y = R_AGE), size=1, alpha=.3) +\n  facet_wrap(~toy_type) +\n  geom_line(aes(y=pred_rs), col = \"orange\")\n```\n\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\n\nFrom the previous questions you should have a model called `ri_mod`.  \n\nBelow is a plot of the fitted values from that model. Rather than having a separate facet for each type of toy as we did above, I have put them all on one plot. The thick black line is the average intercept and slope of the toy-type lines. \n\nIdentify the parts of the plot that correspond to A1-4 in the summary output of the model below  \n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/match_summ1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::\n:::{.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::\n::::\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nChoose from these options:\n\n+ where the black line cuts the y axis (at x=0)  \n+ the slope of the black line  \n+ the standard deviation of the distances from all the individual datapoints (toys) to their respective toy-type lines  \n+ the standard deviation of the distances from all the toy-type lines to the black line  \n\n:::\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/match_summ1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::\n:::{.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::\n::::\n\n+ **A1** = the standard deviation of the distances from all the toy-type lines to the black line  \n+ **A2** = the standard deviation of the distances from all the individual datapoints (toys) to their respective toy-type lines  \n+ **A3** = where the black line cuts the y axis  \n+ **A4** = the slope of the black line  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Optional Extra</div><div class='question-body'>\n\n\n\nBelow is the model equation for the `ri_mod` model.  \n\nIdentify the part of the equation that represents each of A1-4.  \n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/match_summ1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::\n\n:::{.column width=\"50%\"}\n<div style=\"font-size: .7em\">\n\n\\begin{align}\n\\text{For Toy }j\\text{ of Type }i & \\\\\n\\text{Level 1 (Toy):}& \\\\\n\\text{R\\_AGE}_{ij} &= b_{0i} + b_1 \\cdot \\text{hrs\\_week}_{ij} + \\epsilon_{ij} \\\\\n\\text{Level 2 (Type):}& \\\\\nb_{0i} &= \\gamma_{00} + \\zeta_{0i} \\\\\n\\text{Where:}& \\\\\n\\zeta_{0i} &\\sim N(0,\\sigma_{0}) \\\\\n\\varepsilon &\\sim N(0,\\sigma_{e}) \\\\\n\\end{align}\n\n</div>\n\n:::\n::::\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nChoose from:\n\n+ $\\sigma_{\\varepsilon}$  \n+ $b_{1}$  \n+ $\\sigma_{0}$   \n+ $\\gamma_{00}$  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n+ **A1 =** $\\sigma_{0}$   \n+ **A2 =** $\\sigma_{\\varepsilon}$  \n+ **A3 =** $\\gamma_{00}$  \n+ **A4 =** $b_{1}$  \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Audio Interference in Executive Functioning (Repeated Measures)\n\n:::lo\nThis next set are (slightly) closer to analysing a real study. We have some data and a research question (below). The exercises will walk you through describing the data, then prompt you to think about how we might fit an appropriate model to address the research question, and finally task you with having a go at writing up what you've done.  \n:::\n\n\n\n\n\n\n\n\n\n\n:::frame\n__Data: Audio interference in executive functioning__  \n\nThis data is from a simulated study that aims to investigate the following research question: \n\n> How do different types of audio interfere with executive functioning, and does this interference differ depending upon whether or not noise-cancelling headphones are used? \n\n30 healthy volunteers each completed the Symbol Digit Modalities Test (SDMT) - a commonly used test to assess processing speed and motor speed - a total of 15 times. During the tests, participants listened to either no audio (5 tests), white noise (5 tests) or classical music (5 tests). Half the participants listened via active-noise-cancelling headphones, and the other half listened via speakers in the room. Unfortunately, lots of the tests were not administered correctly, and so not every participant has the full 15 trials worth of data.  \n\nThe data is available at [https://uoepsy.github.io/data/lmm_ef_sdmt.csv](https://uoepsy.github.io/data/lmm_ef_sdmt.csv).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fptnpbqagc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fptnpbqagc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fptnpbqagc thead, #fptnpbqagc tbody, #fptnpbqagc tfoot, #fptnpbqagc tr, #fptnpbqagc td, #fptnpbqagc th {\n  border-style: none;\n}\n\n#fptnpbqagc p {\n  margin: 0;\n  padding: 0;\n}\n\n#fptnpbqagc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fptnpbqagc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fptnpbqagc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fptnpbqagc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fptnpbqagc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fptnpbqagc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fptnpbqagc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fptnpbqagc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fptnpbqagc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fptnpbqagc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fptnpbqagc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fptnpbqagc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fptnpbqagc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fptnpbqagc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fptnpbqagc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fptnpbqagc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fptnpbqagc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fptnpbqagc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fptnpbqagc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fptnpbqagc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fptnpbqagc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fptnpbqagc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fptnpbqagc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fptnpbqagc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fptnpbqagc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fptnpbqagc .gt_left {\n  text-align: left;\n}\n\n#fptnpbqagc .gt_center {\n  text-align: center;\n}\n\n#fptnpbqagc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fptnpbqagc .gt_font_normal {\n  font-weight: normal;\n}\n\n#fptnpbqagc .gt_font_bold {\n  font-weight: bold;\n}\n\n#fptnpbqagc .gt_font_italic {\n  font-style: italic;\n}\n\n#fptnpbqagc .gt_super {\n  font-size: 65%;\n}\n\n#fptnpbqagc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fptnpbqagc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fptnpbqagc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fptnpbqagc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fptnpbqagc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fptnpbqagc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fptnpbqagc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fptnpbqagc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fptnpbqagc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">PID</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant ID</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">audio</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Audio heard during the test ('no_audio', 'white_noise','music')</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">headphones</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether the participant listened via speakers (S) in the room or via noise cancelling headphones (H)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">SDMT</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Symbol Digit Modalities Test (SDMT) score</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nHow many participants are there in the data?   \nHow many have complete data (15 trials)?  \nWhat is the average number of trials that participants completed? What is the minimum?   \nDoes every participant have _some_ data for each type of audio?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nFunctions like `table()` and `count()` will likely be useful here. \n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  1 - read in the data </button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nefdat <- read_csv(\"https://uoepsy.github.io/data/lmm_ef_sdmt.csv\")\nhead(efdat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  PID    audio       headphones  SDMT\n  <chr>  <chr>       <chr>      <dbl>\n1 PPT_15 no_audio    S             37\n2 PPT_22 no_audio    H             55\n3 PPT_21 no_audio    H             40\n4 PPT_20 no_audio    H             36\n5 PPT_20 no_audio    H             30\n6 PPT_05 white_noise S             30\n```\n\n\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  2 - how many ppts?</button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\nFor a quick \"how many?\", functions like `n_distinct()` can be handy:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_distinct(efdat$PID)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n:::\n\n\n\n\nWhich is essentially the same as asking: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nunique(efdat$PID) |> length()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  3 - how many observations per ppt?</button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\nHere are the counts of trials for each participant. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nefdat |> \n  count(PID)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 2\n  PID        n\n  <chr>  <int>\n1 PPT_01    13\n2 PPT_02    12\n3 PPT_03    10\n4 PPT_04    10\n5 PPT_05    10\n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\n\n\nWe can pass that to something like `summary()` to get a quick descriptive of the `n` column, and so we can see that no participant completed all 15 trials (max is 14). Everyone completed at least 10, and the median was 12. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nefdat |> \n  count(PID) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     PID                  n     \n Length:30          Min.   :10  \n Class :character   1st Qu.:11  \n Mode  :character   Median :12  \n                    Mean   :12  \n                    3rd Qu.:13  \n                    Max.   :14  \n```\n\n\n:::\n:::\n\n\n\n\nWe could also do this easily with things like:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(efdat$PID) |> median()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-8' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  4 - how many observations for each audio type per ppt?</button></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\nFor this kind of thing I would typically default to using `table()` for smaller datasets, to see how many datapoints are in each combination of `PID` and `audio`:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(efdat$PID, efdat$audio)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         music no_audio white_noise\n  PPT_01     4        5           4\n  PPT_02     5        4           3\n  PPT_03     3        2           5\n  PPT_04     3        4           3\n  PPT_05     5        2           3\n  PPT_06     4        4           5\n  PPT_07     4        3           4\n  PPT_08     4        4           5\n  PPT_09     5        4           5\n  PPT_10     4        5           4\n  PPT_11     4        4           4\n  PPT_12     4        5           5\n  PPT_13     4        4           3\n  PPT_14     3        5           4\n  PPT_15     4        5           4\n  PPT_16     4        4           3\n  PPT_17     5        4           5\n  PPT_18     5        3           3\n  PPT_19     3        5           3\n  PPT_20     4        4           5\n  PPT_21     3        5           4\n  PPT_22     4        4           3\n  PPT_23     3        3           4\n  PPT_24     4        5           5\n  PPT_25     4        4           5\n  PPT_26     5        4           5\n  PPT_27     5        2           4\n  PPT_28     4        4           4\n  PPT_29     4        4           4\n  PPT_30     2        5           3\n```\n\n\n:::\n:::\n\n\n\n\nFrom the above, we can see that everyone has data from $\\geq 2$ trials for a given audio type.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(efdat$PID, efdat$audio) |> min()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n#### a tidyverse way:\n\nWhen tables get too big, we can do the same thing with `count()`, but we need to make sure that we are working with factors, in order to summarise all possible combinations of groups (even empty ones)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nefdat |> \n  mutate(PID = factor(PID),\n         audio = factor(audio)) |>\n  # the .drop=FALSE means \"keep empty groups\"\n  count(PID,audio,.drop=FALSE) |> \n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      PID             audio          n    \n PPT_01 : 3   music      :30   Min.   :2  \n PPT_02 : 3   no_audio   :30   1st Qu.:4  \n PPT_03 : 3   white_noise:30   Median :4  \n PPT_04 : 3                    Mean   :4  \n PPT_05 : 3                    3rd Qu.:5  \n PPT_06 : 3                    Max.   :5  \n (Other):72                               \n```\n\n\n:::\n:::\n\n\n\n\nThere are plenty of other ways (e.g., you could use combinations of `group_by()`, `summarise()`), so just pick one that makes sense to you.  \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\n\n> How do different types of audio interfere with executive functioning, and does this interference differ depending upon whether or not noise-cancelling headphones are used? \n\nConsider the following questions about the study:  \n  \n- What is our outcome of interest?  \n- What variables are we seeking to investigate in terms of their impact on the outcome?    \n- What are the units of observations?  \n- Are the observations clustered/grouped? In what way?  \n- What varies *within* these clusters?  \n- What varies *between* these clusters?  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-9' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\n\n- What is our outcome of interest?  \n    + __SDMT scores__  \n- What variables are we seeking to investigate in terms of their impact on the outcome?  \n    + __audio type__ and the interaction __audio type $\\times$ wearing headphones__\n- What are the units of observations?  \n    + __individual trials__  \n- What are the groups/clusters?  \n    + __participants__  \n- What varies *within* these clusters?  \n    + __the type of audio__    \n- What varies *between* these clusters?  \n    + __whether they listen via headphones or speakers__  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nMake factors and set the reference levels of the `audio` and `headphones` variables to \"no audio\" and \"speakers\" respectively.    \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nCan't remember about setting factors and reference levels? Check back to USMR!  \n\n:::\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-10' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nefdat <- efdat |>\n  mutate(\n    audio = fct_relevel(factor(audio), \"no_audio\"),\n    headphones = fct_relevel(factor(headphones), \"S\")\n  )\n```\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nFit a multilevel model to address the aims of the study (copied below)\n\n> How do different types of audio interfere with executive functioning, and does this interference differ depending upon whether or not noise-cancelling headphones are used? \n \nSpecifying the model may feel like a lot, but try splitting it into three parts:  \n\n$$\n\\text{lmer(}\\overbrace{\\text{outcome }\\sim\\text{ fixed effects}}^1\\, + \\, (1 + \\underbrace{\\text{slopes}}_3\\, |\\, \\overbrace{\\text{grouping structure}}^2 )\n$$\n\n\n1. Just like the `lm()`s we have used in the past, think about what we want to _test_. This should provide the outcome and the structure of our fixed effects.  \n2. Think about how the observations are clustered/grouped. This should tell us how to specify the grouping structure in the random effects.  \n3. Some predictors are within-group (i.e., observations in the group have different values), and some predictors are between-group (i.e., every observation in a group has the same value on the predictor). You can only use random slopes for within-group predictors. Think about what variable(s) you have within-group data for. This provides you with what to put in as random slopes. (this is the same idea as in the reading why we couldn't put `funding|school` [Chapter 2: MLM#a-multilevel-question](https://uoepsy.github.io/lmm/02_lmm.html#a-multilevel-model-for-a-multilevel-question){target=\"_blank\"}).  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nMake sure to read about multilevel modesl and how to fit them in [Chapter 2: MLM #multilevel-models-in-r](https://uoepsy.github.io/lmm/02_lmm.html#multilevel-models-in-r){target=\"_blank\"}.  \n\n:::\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-11' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  1 - fixed effects</button></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\nThe question  \n&nbsp;&nbsp;&nbsp; \"*How do different types of audio interfere with executive functioning*\"   means we are interested in the effects of audio type (`audio`) on executive functioning (`SDMT` scores), so we will want:\n\n```\nlmer(SDMT ~ audio ...\n```\n\nHowever, the research aim also asks    \n&nbsp;&nbsp;&nbsp; \"*... and does this interference differ depending upon whether or not noise-cancelling headphones are used?*\"  \nwhich suggests that we are interested in the interaction `SDMT ~ audio * headphones`  \n\n```\nlmer(SDMT ~ audio * headphones + ...   \n```\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-12' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-12', 'sol-start-12')\">  2 - hierarchical data structure</button></div><div class=\"solution-body\" id = \"sol-body-12\" style=\"display: none;\">\n\n\n\nThere are lots of ways that our data is grouped.  \nWe have:  \n\n- 3 different groups of audio type (no_audio, white_noise, music)\n- 2 groups of listening condition (S, H)\n- 30 groups of participants (\"PPT_01\", \"PPT_02\", \"PPT_03\", ...) \n\nThe effects of audio type and headphones are both things we actually want to _test_ - these variables are in our fixed effects. The levels of audio and headphones are not just a random sample from a wider population of levels - they're a specific set of things we want to compare SDMT scores between.  \n\nCompare this with the participants - we don't care about if there is a difference in SDMT scores between e.g., \"PPT_03\" and \"PPT_28\". The participants themselves are just a sample of people that we have taken from a wider population. This makes thinking of \"by-participant random effects\" a sensible approach - we model differences between participants as a normal distribution of deviations around some average:    \n\n```\nlmer(SDMT ~ audio * headphones + (1 + ... | PID)  \n```\n\nThe minimum that we can include is the random intercept. What `(1|PID)` specifies is that \"participants vary in their SDMT scores\". This makes sense - we would expect some participants to have higher executive functioning (and so will tend to score high on the SDMT), and others to have lower functioning (and so tend to score lower).  \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-13' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-13', 'sol-start-13')\">  3 - random slopes</button></div><div class=\"solution-body\" id = \"sol-body-13\" style=\"display: none;\">\n\n\n\nWe can also include a random by-participant effect of `audio`.  \n`audio|PID` specifies that the effect of audio type on SDMT varies by participant. This seems feasible - music might be very distracting (and interfere a lot with the test) for some participants, but have a negligible effect for others.  \n\n```\nlmer(SDMT ~ audio * headphones + \n              (1 + audio | PID), data = efdat)\n```\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Why can't we have `(headphones|PID)`?  \n\nWhy can we fit `(1 + audio | PID)` but not `(1 + headphones | PID)`, or both `(1 + audio + headphones | PID)` or `(1 + audio * headphones | PID)`?  \n\nRemember that `y ~ ... + (x | g)` is saying \"the slope of y~x varies by g\".  \nSuch a sentence only makes sense if each \"the slope of y~x\" is defined for every (or most) groups.  \n\nFor the `headphones` predictor, every participant is _either_ in the \"S\" (speakers) condition _or_ the \"H\" (headphones) condition.  \nThis means that \"the effect of headphones on SDMT\" _doesn't exist_ for any single participant! This means it makes no sense to try and think of the effect as 'varying by participant'.  \n\nCompare this to the `audio` predictor, for the effect _does_ exist for a single given participant, therefore it is possible to think of it as being different for different participants (e.g. PPT_30's performance improves with white noise, but PPT_16's performance does not).  \n\nThe plots below may help to cement this idea:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=80%}\n:::\n\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-29-2.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nWe now have a model, but we don't have any p-values or confidence intervals or anything - i.e. we have no inferential criteria on which to draw conclusions. There are a whole load of different methods available for drawing inferences from multilevel models, which means it can be a bit of a never-ending rabbit hole. For now, we'll just use the 'quick and easy' approach provided by the **lmerTest** package seen in the lectures.  \n\nUsing the **lmerTest** package, re-fit your model, and you should now get some p-values! \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nIf you use `library(lmerTest)` to load the package, then *every single* model you fit will show p-values calculated with the Satterthwaite method.  \nPersonally, I would rather this is not the case, so I often opt to fit specific models with these p-values without ever loading the package:  \n`modp <- lmerTest::lmer(y ~ 1 + x + ....`  \n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n#### optional: a model comparison\n\nIf we want to go down the model comparison route, we just need to isolate the relevant part(s) of the model that we are interested in.  \n\nRemember, model comparison is sometimes a useful way of testing a _set_ of coefficients. For instance, in this example the interaction involves estimating _two_ terms: \n`audiomusic:headphonesH` and `audiowhite_noise:headphonesH`.  \n\nTo test the interaction as a whole, we can create a model without the interaction, and then compare it. The `SATmodcomp()` function from the __pbkrtest__ package provides a way of conducting an F test with the same Satterthwaite method of approximating the degrees of freedom:  \n  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsdmt_mod <- lmer(SDMT ~ audio * headphones + \n              (1 + audio | PID), data = efdat)\nsdmt_res <- lmer(SDMT ~ audio + headphones + \n                   (1 + audio | PID), data = efdat)\nlibrary(pbkrtest)\nSATmodcomp(largeModel = sdmt_mod, smallModel = sdmt_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlarge : SDMT ~ audio * headphones + (1 + audio | PID)\nsmall : SDMT ~ audio + headphones + (1 + audio | PID)\n     statistic    ndf    ddf   p.value    \n[1,]    11.051  2.000 26.909 0.0003136 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-14' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-14', 'sol-start-14')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-14\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsdmt_mod <- lmerTest::lmer(SDMT ~ audio * headphones + \n              (1 + audio | PID), data = efdat)\n\nsummary(sdmt_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: SDMT ~ audio * headphones + (1 + audio | PID)\n   Data: efdat\n\nREML criterion at convergence: 2376.2\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.34520 -0.62861  0.05762  0.60807  2.21250 \n\nRandom effects:\n Groups   Name             Variance Std.Dev. Corr       \n PID      (Intercept)      51.17    7.153               \n          audiomusic       13.69    3.700     0.03      \n          audiowhite_noise 15.22    3.901    -0.25 -0.16\n Residual                  31.49    5.612               \nNumber of obs: 360, groups:  PID, 30\n\nFixed effects:\n                             Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)                  33.25799    1.98897 28.22065  16.721 3.54e-16 ***\naudiomusic                   -8.01731    1.41149 27.58766  -5.680 4.58e-06 ***\naudiowhite_noise             -0.03044    1.44502 26.32588  -0.021 0.983354    \nheadphonesH                   6.85313    2.81170 28.19226   2.437 0.021355 *  \naudiomusic:headphonesH       -3.58748    2.00129 27.94011  -1.793 0.083875 .  \naudiowhite_noise:headphonesH  8.02458    2.04498 26.46166   3.924 0.000556 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) audmsc adwht_ hdphnH adms:H\naudiomusic  -0.174                            \naudiowht_ns -0.352  0.192                     \nheadphonesH -0.707  0.123  0.249              \nadmsc:hdphH  0.123 -0.705 -0.135 -0.173       \nadwht_ns:hH  0.249 -0.136 -0.707 -0.351  0.191\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\n\nWe've already seen in the example with the with the different types of toys (above) that we can visualise the fitted values (model predictions). But these were plotting all the cluster-specific values, and what we are typically interested in are the estimates of (and uncertainty around) our *fixed effects* (i.e. estimates for clusters *on average*). We say “typically” because if you study individual differences, for example, sometimes you might really care about estimating the variability within and between people! But for now, we’re going to focus on what most research questions target: the fixed effects.  \n\nUsing tools like the __effects__ package can provide us with the values of the outcome across levels of a specific fixed predictor, averaging across other predictors (i.e., for any other predictor, if it is continuous then this is like holding the predictor at its mean, and if it is categorical, then it is like a weighted average of the predictions for each level of the predictor).   \n\nThis should get you started:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\neffect(term = \"audio*headphones\", mod = sdmt_mod) |>\n  as.data.frame()\n```\n:::\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nYou can see the effects package in [Chapter 2: MLM #visualising-models](https://uoepsy.github.io/lmm/02_lmm.html#visualising-models){target=\"_blank\"}. The logic is just the same as it was for USMR, it's just that the estimated effects are from an `lmer()` instead of an `lm()`/`glm()`.  \n\n:::\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-15' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-15', 'sol-start-15')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-15\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\neffect(term = \"audio*headphones\", mod = sdmt_mod) |>\n  as.data.frame() |>\n  ggplot(aes(x=audio,y=fit,\n             ymin=lower,ymax=upper,\n             col=headphones))+\n  geom_pointrange(size=1,lwd=1)\n```\n\n::: {.cell-output-display}\n![](01ex_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nNow we have some p-values and a plot, try to create a short write-up of the analysis and results.   \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThink about the principles that have guided you during write-ups thus far. \n\nThe aim in writing a statistical report should be that a reader is able to more or less replicate your analyses **without** referring to your analysis code. Furthermore, it should be able for a reader to understand and replicate your work _even if they use something other than R_. This requires detailing all of the steps you took in conducting the analysis, but without simply referring to R code.   \n\n\n- Provide a description of the sample that is used in the analysis, and any steps that you took to get this sample (i.e. data cleaning/removal)\n- Describe the model/test and how it addresses the research question. What is the structure of the model, and how did you get to this model? *(You don't need a fancy model equation, you can describe in words!)*. \n- Present (visually and numerically) the key results of the coefficient tests or model comparisons, and explain what these mean in the context of the research question (this could be things like practical significance of the effect size, and the group-level variability in the effects). \n\n\n:::\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-16' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-16', 'sol-start-16')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-16\" style=\"display: none;\">\n\n\n\n:::imp\nNot a perfect write-up (there's not really any such thing!).  \n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::int\nSDMT scores were modelled using linear mixed effects regression, with fixed effects of audio-type (no audio/white noise/music, treatment coded with no audio as the reference level), audio delivery (speakers vs ANC-headphones, treatment coded with speakers as the reference level) and their interaction. Participant-level random intercepts and random slopes of audio-type were also included. The inclusion of the interaction term between audio-type and audio-delivery was used to address the question of whether the interference of different audio on executive function depends on whether it is heard via noise-cancelling headphones. A model comparison was conducted between the full model and a restricted model that was identical to the full model with the exception that the interaction term was excluded. Models were fitted using the **lme4** package in R, and estimated with restricted estimation maximum likelihood (REML). Denominator degrees of freedom for all comparisons and tests were approximated using the Satterthwaite method.  \n\nInclusion of the interaction between headphones and audio-type was found to improve model fit ($F(2, 26.9) = 11.05, p < .001$), suggesting that the interference of different types of audio on executive functioning is dependent upon whether the audio is presented through ANC-headphones or through speakers.  \n\nParticipants not wearing headphones and presented with no audio scored on average 33.26 on the SDMT. For participants without headphones, listening to music via speakers was associated with lower scores compared to no audio ($b = -8.02, t(27.59)=-5.68, p <.001$), but there was no significant difference between white noise and no audio.   \n\nWith no audio playing, wearing ANC-headphones was associated with higher SDMT scores compared to those wearing no headphones ($b = 6.85, t(28.19)=2.44, p =.021$).\nThe apparent detrimental effect of music on SDMT scores was not significantly different in the headphones condition compared to the no-headphones condition ($b = -3.59, t(27.94)=-1.79, p =.084$). Compared to those listening through speakers, white noise was associated with a greater increase in scores over no audio, when listening via ANC-heaphones ($b = 8.02, t(26.46)=3.92, p <.001$).  \n\nThere was considerable variability in baseline (i.e. no-audio) SDMT scores across participants (SD = 7.15), with participants showing similar variability in the effects of music (SD = 3.7) and of white-noise (SD = 3.9). A weak negative correlation (-0.25) between participant-level intercepts and effects of white-noise indicated that people who score higher in the no-audio condition tended to be more negatively effect by white-noise. \n<!-- A similar weak negative correlation (-0.16) between music and white-noise effects suggests participants who were more positively affected by one type of audio tended to be more negatively affected by the other.   -->\n\nThese results suggest that music appears to interfere with executive functioning (lower SDMT scores) compared to listening to no audio, and this is not dependent upon whether is heard through headphones or speakers. When listening via speakers, white noise was not associated with differences in executive functioning compared to no audio, but this was different for those listening via headphones, in which white noise saw a greater increase in performance. Furthermore, there appear to be benefits for executive functioning from wearing ANC-headphones even when not-listening to audio, perhaps due to the noise cancellation. The pattern of findings are displayed in @fig-efplot.  \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Interaction between the type (no audio/white noise/music) and the delivery (speakers/ANC headphones) on executive functioning task (SDMT)](01ex_files/figure-html/fig-efplot-1.png){#fig-efplot fig-align='center' width=80%}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"4\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">SDMT</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Statistic</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">df</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">33.26</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">16.72</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">28.22</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">audio [music]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;8.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;5.68</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">27.59</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">audio [white_noise]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.983</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">26.33</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">headphones [H]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">6.85</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.44</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.021</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">28.19</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">audio [music] ×<br>headphones [H]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;3.59</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;1.79</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.084</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">27.94</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">audio [white_noise] ×<br>headphones [H]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">8.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">3.92</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">26.46</td>\n</tr>\n<tr>\n<td colspan=\"5\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">31.49</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>PID</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">51.17</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>11</sub> <sub>PID.audiomusic</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">13.69</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>11</sub> <sub>PID.audiowhite_noise</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">15.22</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&rho;<sub>01</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.03</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">-0.25</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.64</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>PID</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">30</td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"4\">360</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.392 / 0.783</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n\n:::\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n<div class=\"divider div-transparent div-dot\"></div>\n",
    "supporting": [
      "01ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}