{
  "hash": "4514a109298c99076184b8b7d976d4f3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 2 Exercises: Logistic and Longitudinal\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n# Great Apes!  \n\n:::frame\n__Data: msmr_apespecies.csv__ & __msmr_apeage.csv__  \n\nWe have data from a large sample of great apes who have been studied between the ages of 1 to 10 years old (i.e. during adolescence). Our data includes 4 species of great apes: Chimpanzees, Bonobos, Gorillas and Orangutans. Each ape has been assessed on a primate dominance scale at various ages. Data collection was not very rigorous, so apes do not have consistent assessment schedules (i.e., one may have been assessed at ages 1, 3 and 6, whereas another at ages 2 and 8).  \n\nThe researchers are interested in examining how the adolescent development of dominance in great apes differs between species.  \n\nData on the dominance scores of the apes are available at [https://uoepsy.github.io/data/msmr_apeage.csv](https://uoepsy.github.io/data/msmr_apeage.csv){target=\"_blank\"} and the information about which species each ape is are in [https://uoepsy.github.io/data/msmr_apespecies.csv](https://uoepsy.github.io/data/msmr_apespecies.csv){target=\"_blank\"}.  \n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n\n\n::: {#tbl-spec1 .cell layout-align=\"center\" tbl-cap='Data Dictionary: msmr_apespecies.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dyzbugvass\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dyzbugvass table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dyzbugvass thead, #dyzbugvass tbody, #dyzbugvass tfoot, #dyzbugvass tr, #dyzbugvass td, #dyzbugvass th {\n  border-style: none;\n}\n\n#dyzbugvass p {\n  margin: 0;\n  padding: 0;\n}\n\n#dyzbugvass .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dyzbugvass .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dyzbugvass .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dyzbugvass .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dyzbugvass .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dyzbugvass .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dyzbugvass .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dyzbugvass .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dyzbugvass .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dyzbugvass .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dyzbugvass .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dyzbugvass .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dyzbugvass .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dyzbugvass .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dyzbugvass .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyzbugvass .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dyzbugvass .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dyzbugvass .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dyzbugvass .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyzbugvass .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dyzbugvass .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyzbugvass .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dyzbugvass .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyzbugvass .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dyzbugvass .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyzbugvass .gt_left {\n  text-align: left;\n}\n\n#dyzbugvass .gt_center {\n  text-align: center;\n}\n\n#dyzbugvass .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dyzbugvass .gt_font_normal {\n  font-weight: normal;\n}\n\n#dyzbugvass .gt_font_bold {\n  font-weight: bold;\n}\n\n#dyzbugvass .gt_font_italic {\n  font-style: italic;\n}\n\n#dyzbugvass .gt_super {\n  font-size: 65%;\n}\n\n#dyzbugvass .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dyzbugvass .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dyzbugvass .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dyzbugvass .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dyzbugvass .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dyzbugvass .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dyzbugvass .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dyzbugvass .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dyzbugvass div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ape</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Ape Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">species</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Species (Bonobo, Chimpanzee, Gorilla, Orangutan)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n:::\n::: {.column width=\"10%\"}\n\n:::\n::: {.column width=\"45%\"}\n\n\n\n::: {#tbl-spec2 .cell layout-align=\"center\" tbl-cap='Data Dictionary: msmr_apeage.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"sdiwzdhuhq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sdiwzdhuhq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sdiwzdhuhq thead, #sdiwzdhuhq tbody, #sdiwzdhuhq tfoot, #sdiwzdhuhq tr, #sdiwzdhuhq td, #sdiwzdhuhq th {\n  border-style: none;\n}\n\n#sdiwzdhuhq p {\n  margin: 0;\n  padding: 0;\n}\n\n#sdiwzdhuhq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sdiwzdhuhq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sdiwzdhuhq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sdiwzdhuhq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sdiwzdhuhq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sdiwzdhuhq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sdiwzdhuhq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sdiwzdhuhq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sdiwzdhuhq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sdiwzdhuhq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sdiwzdhuhq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sdiwzdhuhq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sdiwzdhuhq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sdiwzdhuhq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sdiwzdhuhq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sdiwzdhuhq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sdiwzdhuhq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sdiwzdhuhq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sdiwzdhuhq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sdiwzdhuhq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sdiwzdhuhq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sdiwzdhuhq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sdiwzdhuhq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sdiwzdhuhq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sdiwzdhuhq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sdiwzdhuhq .gt_left {\n  text-align: left;\n}\n\n#sdiwzdhuhq .gt_center {\n  text-align: center;\n}\n\n#sdiwzdhuhq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sdiwzdhuhq .gt_font_normal {\n  font-weight: normal;\n}\n\n#sdiwzdhuhq .gt_font_bold {\n  font-weight: bold;\n}\n\n#sdiwzdhuhq .gt_font_italic {\n  font-style: italic;\n}\n\n#sdiwzdhuhq .gt_super {\n  font-size: 65%;\n}\n\n#sdiwzdhuhq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sdiwzdhuhq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sdiwzdhuhq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sdiwzdhuhq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sdiwzdhuhq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sdiwzdhuhq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sdiwzdhuhq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#sdiwzdhuhq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#sdiwzdhuhq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ape</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Ape Name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age at assessment (years)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">dominance</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Dominance (Z-scored)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n::::\n\n:::\n\n\n\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nRead in the data and check over it. Do any relevant cleaning/wrangling that might be necessary.   \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  1 - reading and joining</button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\nWe'll read in both datasets, and then join them together. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lme4)\nape_species <- read_csv(\"https://uoepsy.github.io/data/msmr_apespecies.csv\")\nape_age <- read_csv(\"https://uoepsy.github.io/data/msmr_apeage.csv\")\n```\n:::\n\n\n\nSometimes is handy to check that all our participants are in both datasets:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# are all the apes in ape_age also in ape_species?\nall(ape_age$ape %in% ape_species$ape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\n# and vice versa?\nall(ape_species$ape %in% ape_age$ape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.callout-warning collapse=\"true\"}\n#### optional - working with sets!\n\nI often default to using `%in%` and asking several questions to carefully make sure I know what's going on - i.e. \"is all of A `%in%` B? and is all of B `%in%` A, ... etc.\"  \nThere is actually a neat way to ask these questions both at once using some handy functions (that I often forget about) to perform operations on \"sets\" (i.e. collections of things). These include:\n\n- `union(x,y)` - return everything that is in set x or in set y (or both)\n- `intersect(x,y)` - return everything that is in both x and y\n- `setdiff(x,y)` - return everything in x that is not in y (*not there's asymmetry here!*)\n- `setequal(x,y)` - are sets x and y equal?\n\nSo we can use these to ask if, e.g., the two sets of apes in each dataset are equal:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsetequal(ape_species$ape,ape_age$ape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\nIf you want a fun^[really!?!?] challenge, there are lots of other (less concise ways) that we can ask the same thing. Try and come up with a few different ways.  \nE.g.: \"is there anything in the union of the two sets that is not in the intersection of the two sets?\"\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsetdiff(union(ape_species$ape,ape_age$ape), \n        intersect(ape_species$ape,ape_age$ape))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncharacter(0)\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\nOkay, both datasets contain data for the same set of apes.  \nLet's join them:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napedat <- full_join(ape_age, ape_species)\nhead(apedat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  ape     age dominance species   \n  <chr> <dbl>     <dbl> <chr>     \n1 Joel      7       0.6 chimpanzee\n2 Joel      5       1.2 chimpanzee\n3 Joel      8       1.1 chimpanzee\n4 Joel      1       0.2 chimpanzee\n5 Joel      2       0.5 chimpanzee\n6 Joel      6       1   chimpanzee\n```\n\n\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  2 - identifying issues</button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\nFirst off, we can see that we've got some weird typos. Some apes have been identified as \"gorrila\" but it is actually spelled \"gorilla\".  \nAlso, we've got people using two alternatives for the chimps: \"chimp\" and \"chimpanzee\". We'll need to combine those.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(apedat$species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    bonobo      chimp chimpanzee    gorilla    gorrila  orangutan \n       187        146        127        211          2        157 \n```\n\n\n:::\n:::\n\n\n\n\n\nAge looks like it has some weird values (possibly \"-99\"?), and there are possibly a few outliers in the dominance variable. Given that dominance is standardised, it is _extremely_ unlikely that we would see values around 20.. They're not \"impossible\", but they're so incredibly unlikely that I'd be more comfortable assuming they are typos: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(apedat$age, breaks=20)\nhist(apedat$dominance, breaks=20)\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nJust to see what the most extreme values of dominance are:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# show the biggest 5 absolute values in dominance variable\nsort(abs(apedat$dominance), decreasing = TRUE)[1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21.2 19.4  3.9  2.9  2.9\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  3 - cleaning up</button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napedat <- apedat |> \n  mutate(\n    # fix species typos\n    species = case_when(\n      species %in% c(\"chimp\",\"chimpanzee\") ~ \"chimp\",\n      species %in% c(\"gorilla\",\"gorrila\") ~ \"gorilla\",\n      TRUE ~ species\n    )\n  ) |>\n    filter(\n      # get rid of ages -99\n      age > 0, \n      # keep when dominance is between -5 and 5 \n      # (5 here is a slightly arbitrary choice, but you can see from\n      # our checks that this will only exclude the two extreme datapoints\n      # that are 21.2 and 19.4\n      (dominance < 5 & dominance > -5) \n    )\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nHow is this data structure \"hierarchical\" (or \"clustered\")? How many levels do we have, and what are the observational units at each level?  \n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe have a random sample of $\\underbrace{\\text{timepoints}}_{\\text{level 1}}$ from a random sample of $\\underbrace{\\text{apes}}_{\\text{level 2}}$.  \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nFor how many apes do we have data? How many of each species?  \nHow many datapoints does each ape have?  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nWe've seen this last week too - counting the different levels in our data. See [Chapter 4: logisticMLM - #getting-to-know-my-monkeys](https://uoepsy.github.io/lmm/04_log.html#getting-to-know-my-monkeys){target=\"_blank\"} for an example (also about monkeys!)  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nWe have 168 apes in our dataset:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlength(unique(apedat$ape))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 168\n```\n\n\n:::\n:::\n\n\n\n\nHere's how many of each species:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napedat |> \n  group_by(species) |>\n  summarise(\n   n_apes = n_distinct(ape) \n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  species   n_apes\n  <chr>      <int>\n1 bonobo        36\n2 chimp         56\n3 gorilla       46\n4 orangutan     30\n```\n\n\n:::\n:::\n\n\n\n\nLet's create a table of how many observations for each ape, and then we can create a table _from_ that table, to show how many apes have 2 datapoints, how many have 3, 4, and so on:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(apedat$ape) |>\n  table() |>\n  barplot()\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nMake a plot to show how dominance changes for each ape as they get older.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nIn [Chapter 5: Longitudinal MLM - #exploring-the-data](https://uoepsy.github.io/lmm/05_long.html#exploring-the-data){target=\"_blank\"} we made a facet for each cluster (each participant). That was fine because we had only 20 people. In this dataset we have 168! That's too many to facet. We could try using `group` aesthetic instead, to plot multiple lines on the same plot, or we could just plot a sample of our apes. This is all just an initial look at the data, after all. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nHere's a line for each ape, and a facet for each species:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(apedat, aes(x = age, y = dominance, col = species))+\n  geom_line(aes(group = ape)) + \n  facet_wrap(~species) + \n  guides(col=\"none\")\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nIt's kind of hard to see the trend for each ape, so let's also make a separate little linear model for each ape:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(apedat, aes(x = age, y = dominance, col = species))+\n  geom_smooth(aes(group = ape), method=lm, se=FALSE) + \n  facet_wrap(~species) + \n  guides(col=\"none\")\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nAlternatively, let's take a sample of apes, and plot the same stuff but facetted:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napedat |>\n  # choose the rows where ape ID is one of a random sample of 16 ape IDs\n  filter(ape %in% sample(unique(apedat$ape), 16) ) |>\n  ggplot(aes(x = age, y = dominance, col = species))+\n  geom_point() +\n  geom_smooth(method=lm, se=FALSE)+\n  facet_wrap(~ape)\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nRecenter the `age` variable on 1, which is the youngest ages that we've got data on for any of our species.   \n\nThen fit a model that estimates the differences between primate species in how dominance changes over time.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nthink slowly about \"differences between primate species in how dominance changes over time\".  \n\n- \"how dominance changes over time\" -- sounds like `dominance ~ time`\n- so differences between primate species in this would require the interaction `dominance ~ time * species`\n\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napedat$age = apedat$age-1 \n\nm.full <- lmer(dominance ~ 1 + age * species + (1 + age | ape), data = apedat)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\n__*Do*__ primate species differ in the growth of dominance?  \nPerform an appropriate test/comparison.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThis is asking about the `age*species` interaction, which in our model is represented by 3 parameters. To assess the overall question, it might make more sense to do a model comparison.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.int <- lmer(dominance ~ 1 + age + species + (1 + age | ape), data = apedat)\n\nanova(m.int, m.full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: apedat\nModels:\nm.int: dominance ~ 1 + age + species + (1 + age | ape)\nm.full: dominance ~ 1 + age * species + (1 + age | ape)\n       npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)   \nm.int     9 806.67 849.11 -394.34   788.67                        \nm.full   12 801.16 857.74 -388.58   777.16 11.517  3   0.009237 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::int\n\nSpecies differ in how dominance changes over adolescence ($\\chi^2(3) = 11.52, p = 0.009$).  \n\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nPlot the average model predicted values for each age.  \n\nBefore you plot.. do you expect to see straight lines? (remember, not every ape is measured at age 2, or age 3, etc).  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThis is like taking `predict()` from the model, and then then grouping by `age`, and calculating the mean of those predictions. However, we can do this more easily using `augment()` and then some fancy `stat_summary()` in ggplot (see [the lecture](https://uoepsy.github.io/msmr/2425/lectures/msmr_lec02-2_LinearLDA.html#17){target=\"_blank\"}).  \n\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nAveraging fitted values would give us straight lines _if_ every ape had data at all ages, but in our study we have some apes with only 2 data points, and each ape has different set of ages (e.g., one ape might be measured at age 3, 6, and 10, another ape might be at ages 2 and 16).  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(broom.mixed)\n\naugment(m.full) |>\nggplot(aes(age,dominance, color=species)) +\n  # the point ranges are our observations\n  stat_summary(fun.data=mean_se, geom=\"pointrange\") + \n  # the lines are our average predictions  \n  stat_summary(aes(y=.fitted, linetype=species), fun=mean, geom=\"line\")\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nPlot the model based fixed effects:  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neffects::effect(\"age*species\", m.full, xlevels=10) |>\n  as.data.frame() |>\n  ggplot(aes(x=age+1,y=fit,col=species))+\n  geom_line(lwd=1)+\n  geom_ribbon(aes(ymin=lower,ymax=upper,fill=species),col=NA,alpha=.3) +  \n  scale_color_manual(values=c(\"grey30\",\"black\",\"grey50\",\"darkorange\")) +\n  scale_fill_manual(values=c(\"grey30\",\"black\",\"grey50\",\"darkorange\")) +\n  facet_wrap(~species) + \n  guides(col=\"none\",fill=\"none\") +\n  labs(x=\"Age (years)\")\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nInterpret each of the fixed effects from the model (you might also want to get some p-values or confidence intervals).  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nEach of the estimates should correspond to part of our plot from the previous question.  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nLet's get some confidence intervals:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconfint(m.full, method=\"profile\",\n        parm = \"beta_\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           2.5 %      97.5 %\n(Intercept)          -0.67066925 -0.17299177\nage                   0.02361398  0.08142209\nspecieschimp          0.13383485  0.77009884\nspeciesgorilla        0.28124162  0.94933844\nspeciesorangutan     -0.38909919  0.34257548\nage:specieschimp     -0.03973125  0.03392308\nage:speciesgorilla   -0.05012759  0.02799393\nage:speciesorangutan -0.10625760 -0.02167806\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gerwptdbxb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gerwptdbxb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gerwptdbxb thead, #gerwptdbxb tbody, #gerwptdbxb tfoot, #gerwptdbxb tr, #gerwptdbxb td, #gerwptdbxb th {\n  border-style: none;\n}\n\n#gerwptdbxb p {\n  margin: 0;\n  padding: 0;\n}\n\n#gerwptdbxb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gerwptdbxb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gerwptdbxb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gerwptdbxb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gerwptdbxb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gerwptdbxb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gerwptdbxb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gerwptdbxb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gerwptdbxb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gerwptdbxb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gerwptdbxb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gerwptdbxb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gerwptdbxb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gerwptdbxb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gerwptdbxb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gerwptdbxb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gerwptdbxb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gerwptdbxb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gerwptdbxb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gerwptdbxb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gerwptdbxb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gerwptdbxb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gerwptdbxb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gerwptdbxb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gerwptdbxb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gerwptdbxb .gt_left {\n  text-align: left;\n}\n\n#gerwptdbxb .gt_center {\n  text-align: center;\n}\n\n#gerwptdbxb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gerwptdbxb .gt_font_normal {\n  font-weight: normal;\n}\n\n#gerwptdbxb .gt_font_bold {\n  font-weight: bold;\n}\n\n#gerwptdbxb .gt_font_italic {\n  font-style: italic;\n}\n\n#gerwptdbxb .gt_super {\n  font-size: 65%;\n}\n\n#gerwptdbxb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gerwptdbxb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gerwptdbxb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gerwptdbxb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gerwptdbxb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gerwptdbxb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gerwptdbxb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gerwptdbxb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gerwptdbxb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"est\">est</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI\">CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interpretation\">interpretation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-0.42</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.67, -0.17]*</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated dominance of 1 year old bonobos (at left hand side of plot, bonobo line is lower than 0)</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age</td>\n<td headers=\"est\" class=\"gt_row gt_right\">0.05</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[0.02, 0.08]*</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated change in dominance score for every year older a bonobo gets (slope of bonobo line)</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">specieschimp</td>\n<td headers=\"est\" class=\"gt_row gt_right\">0.45</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[0.13, 0.77]*</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated difference in dominance scores at age 1 between bonobos and chimps (at left hand side of plot, chimp line is higher than bonobo line)</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">speciesgorilla</td>\n<td headers=\"est\" class=\"gt_row gt_right\">0.62</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[0.28, 0.95]*</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated difference in dominance scores at age 1 between bonobos and gorillas (at left hand side of plot, gorilla line is higher than bonobo line)</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">speciesorangutan</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-0.02</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.39, 0.34]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">no significant difference in dominance scores at age 1 between bonobos and orangutans (at the left hand side of our plot, orangutan line is similar height to bonobo line)</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age:specieschimp</td>\n<td headers=\"est\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.04, 0.03]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">no significant difference between chimps and bonobos in the change in dominance for every year older (slope of chimp line is similar to slope of bonobo line)</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age:speciesgorilla</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-0.01</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.05, 0.03]</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">no significant difference between gorillas and bonobos in the change in dominance for every year older (slope of gorilla line is similar to slope of bonobo line)</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age:speciesorangutan</td>\n<td headers=\"est\" class=\"gt_row gt_right\">-0.06</td>\n<td headers=\"CI\" class=\"gt_row gt_left\">[-0.11, -0.02]*</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\">estimated difference between orangutans and bonobos in the change in dominance for every year older (slope of orangutan line is less steep than slope of bonobo line)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n# Trolley problems\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n:::frame\n__Data: msmr_trolley.csv__  \n\nThe \"Trolley Problem\" is a thought experiment in moral philosophy that asks you to decide whether or not to pull a lever to divert a trolley. Pulling the lever changes the trolley direction from hitting 5 people to a track on which it will hit one person.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/trolley.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nPrevious research has found that the \"framing\" of the problem will influence the decisions people make: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jzxpjdmlao\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jzxpjdmlao table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jzxpjdmlao thead, #jzxpjdmlao tbody, #jzxpjdmlao tfoot, #jzxpjdmlao tr, #jzxpjdmlao td, #jzxpjdmlao th {\n  border-style: none;\n}\n\n#jzxpjdmlao p {\n  margin: 0;\n  padding: 0;\n}\n\n#jzxpjdmlao .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jzxpjdmlao .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jzxpjdmlao .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jzxpjdmlao .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jzxpjdmlao .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jzxpjdmlao .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jzxpjdmlao .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jzxpjdmlao .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jzxpjdmlao .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jzxpjdmlao .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jzxpjdmlao .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jzxpjdmlao .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jzxpjdmlao .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jzxpjdmlao .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jzxpjdmlao .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzxpjdmlao .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jzxpjdmlao .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jzxpjdmlao .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jzxpjdmlao .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzxpjdmlao .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jzxpjdmlao .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzxpjdmlao .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jzxpjdmlao .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzxpjdmlao .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzxpjdmlao .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzxpjdmlao .gt_left {\n  text-align: left;\n}\n\n#jzxpjdmlao .gt_center {\n  text-align: center;\n}\n\n#jzxpjdmlao .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jzxpjdmlao .gt_font_normal {\n  font-weight: normal;\n}\n\n#jzxpjdmlao .gt_font_bold {\n  font-weight: bold;\n}\n\n#jzxpjdmlao .gt_font_italic {\n  font-style: italic;\n}\n\n#jzxpjdmlao .gt_super {\n  font-size: 65%;\n}\n\n#jzxpjdmlao .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jzxpjdmlao .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jzxpjdmlao .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jzxpjdmlao .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jzxpjdmlao .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jzxpjdmlao .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jzxpjdmlao .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jzxpjdmlao .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jzxpjdmlao div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"positive-frame\">positive frame</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"neutral-frame\">neutral frame</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"negative-frame\">negative frame</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"positive frame\" class=\"gt_row gt_left\">5 people will be saved if you pull the lever; one person on another track will be saved if you do not pull the lever. All your actions are legal and understandable. Will you pull the lever?</td>\n<td headers=\"neutral frame\" class=\"gt_row gt_left\">5 people will be saved if you pull the lever, but another person will die. One people will be saved if you do not pull the lever, but 5 people will die. All your actions are legal and understandable. Will you pull the lever?</td>\n<td headers=\"negative frame\" class=\"gt_row gt_left\">One person will die if you pull the lever. 5 people will die if you do not pull the lever. All your actions are legal and understandable. Will you pull the lever?</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nWe conducted a study to investigate **whether the framing effects on moral judgements depends upon the stakes (i.e. the number of lives saved)**.  \n\n120 participants were recruited, and each gave answers to 12 versions of the thought experiment. For each participant, four versions followed each of the positive/neutral/negative framings described above, and for each framing, 2 would save 5 people and 2 would save 15 people.  \n\nThe data are available at [https://uoepsy.github.io/data/msmr_trolley.csv](https://uoepsy.github.io/data/msmr_trolley.csv){target=\"_blank\"}.  \n\n\n\n\n::: {#tbl-trolley .cell layout-align=\"center\" tbl-cap='Data Dictionary: trolley.csv'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tlhoviadrs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tlhoviadrs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tlhoviadrs thead, #tlhoviadrs tbody, #tlhoviadrs tfoot, #tlhoviadrs tr, #tlhoviadrs td, #tlhoviadrs th {\n  border-style: none;\n}\n\n#tlhoviadrs p {\n  margin: 0;\n  padding: 0;\n}\n\n#tlhoviadrs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tlhoviadrs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tlhoviadrs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tlhoviadrs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tlhoviadrs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tlhoviadrs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tlhoviadrs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tlhoviadrs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tlhoviadrs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tlhoviadrs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tlhoviadrs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tlhoviadrs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tlhoviadrs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tlhoviadrs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tlhoviadrs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tlhoviadrs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tlhoviadrs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tlhoviadrs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tlhoviadrs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tlhoviadrs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tlhoviadrs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tlhoviadrs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tlhoviadrs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tlhoviadrs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tlhoviadrs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tlhoviadrs .gt_left {\n  text-align: left;\n}\n\n#tlhoviadrs .gt_center {\n  text-align: center;\n}\n\n#tlhoviadrs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tlhoviadrs .gt_font_normal {\n  font-weight: normal;\n}\n\n#tlhoviadrs .gt_font_bold {\n  font-weight: bold;\n}\n\n#tlhoviadrs .gt_font_italic {\n  font-style: italic;\n}\n\n#tlhoviadrs .gt_super {\n  font-size: 65%;\n}\n\n#tlhoviadrs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tlhoviadrs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tlhoviadrs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tlhoviadrs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tlhoviadrs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tlhoviadrs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tlhoviadrs .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tlhoviadrs .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tlhoviadrs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">PID</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant ID</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">frame</td>\n<td headers=\"description\" class=\"gt_row gt_left\">framing of the thought experiment (positive/neutral/negative</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">lives</td>\n<td headers=\"description\" class=\"gt_row gt_left\">lives at stake in the thought experiment (5 or 15)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">lever</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether or not the participant chose to pull the lever (1 = yes, 0 = no)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nRead in the data and check over how many people we have, and whether we have complete data for each participant.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nI would maybe try `data |> group_by(participant) |> summarise()`, and then use the `n_distinct()` function to count how many \"things\" each person sees (e.g., [Chapter 4: Logistic MLM #example](https://uoepsy.github.io/lmm/04_log.html#example){target=\"_blank\"}). \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntrolley <- read_csv(\"https://uoepsy.github.io/data/msmr_trolley.csv\")\nhead(trolley)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  PID   frame    lives   lever\n  <chr> <chr>    <chr>   <dbl>\n1 PPT_1 positive 5lives      1\n2 PPT_1 positive 15lives     1\n3 PPT_1 positive 5lives      1\n4 PPT_1 positive 15lives     1\n5 PPT_1 neutral  5lives      1\n6 PPT_1 neutral  15lives     0\n```\n\n\n:::\n:::\n\n\n\n\nHow many participants?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlength(unique(trolley$PID))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\n\n\nHow many trials for each participant in each condition.  \nWe can, for each participant, count how many trials they have in total, how many \"frames\" they see, how many \"lives\" they see, and how many \"frame x lives\" combinations they see:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntrolley |>\n  group_by(PID) |>\n  summarise(\n    n_trials = n(),\n    n_frame = n_distinct(frame),\n    n_lives = n_distinct(lives),\n    n_combn = n_distinct(frame,lives)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 120 × 5\n   PID     n_trials n_frame n_lives n_combn\n   <chr>      <int>   <int>   <int>   <int>\n 1 PPT_1         12       3       2       6\n 2 PPT_10        12       3       2       6\n 3 PPT_100       12       3       2       6\n 4 PPT_101       12       3       2       6\n 5 PPT_102       12       3       2       6\n 6 PPT_103       12       3       2       6\n 7 PPT_104       12       3       2       6\n 8 PPT_105       12       3       2       6\n 9 PPT_106       12       3       2       6\n10 PPT_107       12       3       2       6\n# ℹ 110 more rows\n```\n\n\n:::\n:::\n\n\n\n\nIf everybody gets the same here (as we can see they do below), then everyone has complete data!  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntrolley |>\n  group_by(PID) |>\n  summarise(\n    n_trials = n(),\n    n_frame = n_distinct(frame),\n    n_lives = n_distinct(lives),\n    n_combn = n_distinct(frame,lives)\n  ) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     PID               n_trials     n_frame     n_lives     n_combn \n Length:120         Min.   :12   Min.   :3   Min.   :2   Min.   :6  \n Class :character   1st Qu.:12   1st Qu.:3   1st Qu.:2   1st Qu.:6  \n Mode  :character   Median :12   Median :3   Median :2   Median :6  \n                    Mean   :12   Mean   :3   Mean   :2   Mean   :6  \n                    3rd Qu.:12   3rd Qu.:3   3rd Qu.:2   3rd Qu.:6  \n                    Max.   :12   Max.   :3   Max.   :2   Max.   :6  \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n\nConstruct an appropriate plot to summarise the data in a suitable way to illustrate the research question.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nSomething making use of `stat_summary()` to give proportions, a bit like the plot in [Chapter 4: Logistic MLM - #getting-to-know-my-monkeys](https://uoepsy.github.io/lmm/04_log.html#getting-to-know-my-monkeys){target=\"_blank\"}?  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nHere is a plot of proportions of trials in which the lever was pulled, split by how the problem was framed, and the number of lives saved:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(trolley, aes(x=frame, y=lever, col=lives)) +\n  stat_summary(geom=\"pointrange\", size=1, \n               position=position_dodge(width=.2)) \n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n\nFit a model to assess the research aims.  \nDon't worry if it gives you an error, we'll deal with that in a second.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- Remember, a good way to start is to split this up into 3 parts: 1) the outcome and fixed effects, 2) the grouping structure, and 3) the random slopes.  \n- fitting (or attempting to fit!) `glmer` models might take time!  \n\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  1 - fixed</button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\nThe researchers are *\"interested in whether the framing effects on moral judgements depends upon the stakes (i.e. the number of lives saved)\"*.  \n\n\"the framing effect on moral judgements\" here is operationalised as  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlever ~ frame\n```\n:::\n\n\n\nand the wording \"depends upon the stakes\" means that we want to know if that effect of frame \"is different for\" the situations when lives = 5, vs lives = 15 - i.e. we need the interaction!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlever ~ frame * lives\n```\n:::\n\n\n\n\nThe outcome here is lever pulled (yes v no), so it's a binary variable!  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglmer(lever ~ frame * lives + ....\n      ....,  \n      data = trolley, family = binomial)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  2 - grouping</button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\n\nWe know that we have multiple observations for each participant, and those participants are just a random sample (it's not something we're interested in testing, we would like to model participant differences as random variation).  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglmer(lever ~ frame * lives + ....\n      (1 + .... | PID),  \n      data = trolley, family = binomial)\n```\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  3 - random</button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\nFinally, what effects _could_ theoretically vary between our participants?  \nEvery participant saw everything (i.e. both `frame` and `lives` are \"within participant\" variables). \n\nIn theory, all of these are possible given our design:  \n\n- the effect of frame on probability of pulling the lever could vary between participants\n- the effect of number of lives on probability of pulling the lever could vary between participants\n- the amount by which number of lives influences the effect of frame on pulling the lever could vary between participants\n\nSo we could theoretically try and fit this model:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod1 <- glmer(lever ~ frame * lives + \n      (1 + frame * lives | PID),  \n      data = trolley, family = binomial)\n```\n:::\n\n\n\n<p style=\"color:red;\">\nWarning messages:<br>\n1: In (function (fn, par, lower = rep.int(-Inf, n), upper = rep.int(Inf,  :\n  failure to converge in 10000 evaluations<br>\n2: In optwrap(optimizer, devfun, start, rho\\$lower, control = control,  :\n  convergence code 4 from Nelder_Mead: failure to converge in 10000 evaluations<br>\n3: In checkConv(attr(opt, \"derivs\"), opt\\$par, ctrl = control\\$checkConv,  :\n  Model failed to converge with max|grad| = 0.0795145 (tol = 0.002, component 1)\n</p>\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 13</div><div class='question-body'>\n\n\nThis is probably the first time we've had to deal with a model not converging.  \n\nWhile sometimes changing the optimizer can help, more often than not, the model we are trying to fit is just too complex. Often, the groups in our sample just don't vary enough for us to estimate a random slope.  \n\nThe aim here is to simplify our random effect structure in order to obtain a converging model, but be careful not to over simplify.  \n\nTry it now. What model do you end up with? (You might not end up with the same model as each other, which is fine. These methods don't have \"cookbook recipes\"!)\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nyou could think of the interaction as the 'most complex' part of our random effects, so you might want to remove that first.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nThis model still does not converge:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod2 <- glmer(lever ~ frame * lives + \n      (1 + frame + lives | PID),  \n      data = trolley, family = binomial)\n```\n:::\n\n\n\n<p style=\"color:red;\">\nWarning message:<br>\nIn checkConv(attr(opt, \"derivs\"), opt\\$par, ctrl = control\\$checkConv,  :\n  Model failed to converge with max|grad| = 0.00734804 (tol = 0.002, component 1)\n</p>\n\nWe have a choice here - do we remove `frame|PID` or `lives|PID`? One practical point is that each participant has only 4 observations for each `frame` type, but they have 6 observations for each `lives` type, which might make it easier to fit.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod3 <- glmer(lever ~ frame * lives + \n      (1 + lives | PID),  \n      data = trolley, family = binomial)\n```\n:::\n\n\n\nHooray! it converges!  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 14</div><div class='question-body'>\n\n\nPlot the predicted probabilities from your model for each combination of `frame` and `lives`.  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\neffect(\"frame*lives\", mod3) |>\n  as.data.frame() |>\n  ggplot(aes(x = frame, y = fit, col = lives)) +\n  geom_pointrange(aes(ymin=lower,ymax=upper),\n                  position=position_dodge(width=.2),\n                  size=1)+\n  labs(y=\"probability of pulling the lever\")\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-43-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<!-- \n\n<div class='question-begin'>Question 15</div><div class='question-body'>\n\n -->\n<!-- Compute odds ratios and create some confidence intervals, then interpret them.   -->\n\n\n<!-- ::: {.callout-tip collapse=\"true\"} -->\n<!-- #### Hints -->\n\n<!-- Odds ratios are confusing, so take the lead from your plot about what goes up/down etc.   -->\n<!-- The default of profile likelihood confidence intervals might take a while to compute, so you could choose the Wald method instead (see [2B #interpretation](02b_loglong.html#interpretation){target=\"_blank\"}).   -->\n\n<!-- ::: -->\n\n\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div style=\"display:none;\">\n\n -->\n\n<!-- ```{r} -->\n<!-- cbind( -->\n<!--   fixef(mod3), # the fixed effects -->\n<!--   confint(mod3, method=\"Wald\", parm=\"beta_\") # Wald CIs for fixed effects -->\n<!-- ) |> -->\n<!--   exp() -->\n<!-- ``` -->\n\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- cbind( -->\n<!--   fixef(mod3), # the fixed effects -->\n<!--   confint(mod3, method=\"Wald\", parm=\"beta_\") # Wald CIs for fixed effects -->\n<!-- ) |> -->\n<!--   exp() |> as.data.frame() |> -->\n<!--   rownames_to_column() |> -->\n<!--   transmute( -->\n<!--     term = rowname, OR=round(V1,2), -->\n<!--     CI = paste0(\"[\", -->\n<!--                 round(`2.5 %`,2),\", \", -->\n<!--                 round(`97.5 %`,2),\"]\" -->\n<!--     ), -->\n<!--     interpretation = c( -->\n<!--       \"Odds of pulling the lever when in a positive framed problem with the potential of saving 5 lives\", -->\n<!--       paste0(\"With 5 lives at stake, a neutral framing is associated with \",round(exp(fixef(mod3))[2],2),\" times the odds of pulling the lever in comparison to a positive framing\"), -->\n<!--       paste0(\"With 5 lives at stake, a negative framing is associated with \",round(exp(fixef(mod3))[3],2),\" times the odds of pulling the lever in comparison to a positive framing\"), -->\n<!--       \"In a positive framing, the number of lives at stake is not associated with a change in the odds of pulling the lever\", -->\n<!--       paste0(\"In the neutral framing, the 15 vs 5 lives The neutral vs positive framing difference is increase  \",round(exp(fixef(mod3))[2],2),\" times the odds of pulling the lever in comparison to a positive framing\"), -->\n<!--     ) -->\n<!--   )  -->\n<!-- ``` -->\n\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n\n<br>\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n\n# Optional extra: Novel Word Learning\n\n\n:::frame\n__Data: nwl.Rdata__ \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nload(url(\"https://uoepsy.github.io/msmr/data/nwl.RData\"))\n```\n:::\n\n\n\n\nIn the `nwl` data set (accessed using the code above), participants with aphasia are separated into two groups based on the general location of their brain lesion: anterior vs. posterior. There is data on the numbers of correct and incorrect responses participants gave in each of a series of experimental blocks. There were 7 learning blocks, immediately followed by a test. Finally, participants also completed a follow-up test.\n<br>\nData were also collect from healthy controls. \n<br>\n@fig-nwl shows the differences between lesion location groups in the average proportion of correct responses at each point in time (i.e., each block, test, and follow-up)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Differences between groups in the average proportion of correct responses at each block](02ex_files/figure-html/fig-nwl-1.png){#fig-nwl fig-align='center' width=80%}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qvxcaazjpu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qvxcaazjpu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qvxcaazjpu thead, #qvxcaazjpu tbody, #qvxcaazjpu tfoot, #qvxcaazjpu tr, #qvxcaazjpu td, #qvxcaazjpu th {\n  border-style: none;\n}\n\n#qvxcaazjpu p {\n  margin: 0;\n  padding: 0;\n}\n\n#qvxcaazjpu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qvxcaazjpu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qvxcaazjpu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qvxcaazjpu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qvxcaazjpu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qvxcaazjpu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qvxcaazjpu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qvxcaazjpu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qvxcaazjpu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qvxcaazjpu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qvxcaazjpu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qvxcaazjpu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qvxcaazjpu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qvxcaazjpu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qvxcaazjpu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvxcaazjpu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qvxcaazjpu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qvxcaazjpu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qvxcaazjpu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvxcaazjpu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qvxcaazjpu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvxcaazjpu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qvxcaazjpu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvxcaazjpu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qvxcaazjpu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvxcaazjpu .gt_left {\n  text-align: left;\n}\n\n#qvxcaazjpu .gt_center {\n  text-align: center;\n}\n\n#qvxcaazjpu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qvxcaazjpu .gt_font_normal {\n  font-weight: normal;\n}\n\n#qvxcaazjpu .gt_font_bold {\n  font-weight: bold;\n}\n\n#qvxcaazjpu .gt_font_italic {\n  font-style: italic;\n}\n\n#qvxcaazjpu .gt_super {\n  font-size: 65%;\n}\n\n#qvxcaazjpu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qvxcaazjpu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qvxcaazjpu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qvxcaazjpu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qvxcaazjpu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qvxcaazjpu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qvxcaazjpu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qvxcaazjpu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qvxcaazjpu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">group</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether participant is a stroke patient ('patient') or a healthy control ('control')</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">lesion_location</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Location of brain lesion: anterior vs posterior</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">block</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Experimental block (1-9). Blocks 1-7 were learning blocks, immediately followed by a test in block 8. Block 9 was a follow-up test at a later point</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">PropCorrect</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Proportion of 30 responses in a given block that the participant got correct</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">NumCorrect</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of responses (out of 30) in a given block that the participant got correct</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">NumError</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of responses (out of 30) in a given block that the participant got incorrect</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ID</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Identifier</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Phase</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Experimental phase, corresponding to experimental block(s): 'Learning', 'Immediate','Follow-up'</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question 16</div><div class='question-body'>\n\n\nLoad the data. Take a look around. Any missing values? Can you think of why?  \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-8' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nload(url(\"https://uoepsy.github.io/msmr/data/nwl.RData\"))\nsummary(nwl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     group      lesion_location     block    PropCorrect       NumCorrect   \n control:126   anterior : 45    Min.   :1   Min.   :0.2000   Min.   : 6.00  \n patient:117   posterior: 63    1st Qu.:3   1st Qu.:0.5333   1st Qu.:16.00  \n               NA's     :135    Median :5   Median :0.7000   Median :21.00  \n                                Mean   :5   Mean   :0.6822   Mean   :20.47  \n                                3rd Qu.:7   3rd Qu.:0.8333   3rd Qu.:25.00  \n                                Max.   :9   Max.   :1.0000   Max.   :30.00  \n                                                                            \n    NumError              ID         Phase          \n Min.   : 0.000   control1 :  9   Length:243        \n 1st Qu.: 5.000   control10:  9   Class :character  \n Median : 9.000   control11:  9   Mode  :character  \n Mean   : 9.535   control12:  9                     \n 3rd Qu.:14.000   control13:  9                     \n Max.   :24.000   control14:  9                     \n                  (Other)  :189                     \n```\n\n\n:::\n:::\n\n\n\n\nThe only missing vales are in the lesion location, and it's probably because the healthy controls don't have any lesions. There may also be a few patients for which the lesion_location is missing, but this should be comparatively fewer values compared to controls.\n\nThe following command creates a two-way frequency table showing the number of controls or patients by lesion location, confirming that controls only have missing values (NAs) and only 9 patients have missing values:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(nwl$group, nwl$lesion_location, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          anterior posterior <NA>\n  control        0         0  126\n  patient       45        63    9\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 17</div><div class='question-body'>\n\n\nOur broader research aim today is to compare the two lesion location groups (those with anterior vs. posterior lesions) with respect to their accuracy of responses over the course of the study.  \n\n- What is the outcome variable? \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThink carefully: there might be several variables which either fully or partly express the information we are considering the \"outcome\" here. \nWe saw this back in [USMR](https://uoepsy.github.io/usmr/2425/labs/10a_glm.html#fitting-glm-in-r){target=\"_blank\"} with the `glm()`!  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-9' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\nThe outcome here is (in words) the proportion of correct answers or, equivalently, the probability of answering correctly. A proportion/probability can only vary between 0 and 1 and, as such, we cannot use traditional linear regression or we could end up with predictions outside of the [0, 1] range.\n\nAs said, the outcome is the proportion of correct answers in each block. This makes it tempting to look at the variable called `PropCorrect`, but this is encoded as a proportion. We have learned to use logistic models, but these require either:\n\n- a binary outcome variable, where the values are 0s or 1s\n- a binomial outcome variable, where the values are aggregated counts of 1s and 0s \n\n__Binary data__. In the case below you would use the specification `correct ~ ...`:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"oddopdumdq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#oddopdumdq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#oddopdumdq thead, #oddopdumdq tbody, #oddopdumdq tfoot, #oddopdumdq tr, #oddopdumdq td, #oddopdumdq th {\n  border-style: none;\n}\n\n#oddopdumdq p {\n  margin: 0;\n  padding: 0;\n}\n\n#oddopdumdq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#oddopdumdq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#oddopdumdq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#oddopdumdq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#oddopdumdq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#oddopdumdq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#oddopdumdq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#oddopdumdq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#oddopdumdq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#oddopdumdq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#oddopdumdq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#oddopdumdq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#oddopdumdq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#oddopdumdq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#oddopdumdq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddopdumdq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#oddopdumdq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#oddopdumdq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#oddopdumdq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddopdumdq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#oddopdumdq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddopdumdq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#oddopdumdq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddopdumdq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oddopdumdq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddopdumdq .gt_left {\n  text-align: left;\n}\n\n#oddopdumdq .gt_center {\n  text-align: center;\n}\n\n#oddopdumdq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#oddopdumdq .gt_font_normal {\n  font-weight: normal;\n}\n\n#oddopdumdq .gt_font_bold {\n  font-weight: bold;\n}\n\n#oddopdumdq .gt_font_italic {\n  font-style: italic;\n}\n\n#oddopdumdq .gt_super {\n  font-size: 65%;\n}\n\n#oddopdumdq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#oddopdumdq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#oddopdumdq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#oddopdumdq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#oddopdumdq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#oddopdumdq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#oddopdumdq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#oddopdumdq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#oddopdumdq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"participant\">participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"question\">question</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"correct\">correct</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">1</td>\n<td headers=\"question\" class=\"gt_row gt_right\">1</td>\n<td headers=\"correct\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">1</td>\n<td headers=\"question\" class=\"gt_row gt_right\">2</td>\n<td headers=\"correct\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">1</td>\n<td headers=\"question\" class=\"gt_row gt_right\">3</td>\n<td headers=\"correct\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">...</td>\n<td headers=\"question\" class=\"gt_row gt_right\">...</td>\n<td headers=\"correct\" class=\"gt_row gt_right\">...</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n__Binomial data__. You would use the specification `cbind(num_successes, num_failures)` which, in the case below, would be:\n\n`cbind(questions_correct, questions_incorrect) ~ ...`\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bfenaqvktz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bfenaqvktz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bfenaqvktz thead, #bfenaqvktz tbody, #bfenaqvktz tfoot, #bfenaqvktz tr, #bfenaqvktz td, #bfenaqvktz th {\n  border-style: none;\n}\n\n#bfenaqvktz p {\n  margin: 0;\n  padding: 0;\n}\n\n#bfenaqvktz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bfenaqvktz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bfenaqvktz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bfenaqvktz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bfenaqvktz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bfenaqvktz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bfenaqvktz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bfenaqvktz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bfenaqvktz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bfenaqvktz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bfenaqvktz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bfenaqvktz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bfenaqvktz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bfenaqvktz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bfenaqvktz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfenaqvktz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bfenaqvktz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bfenaqvktz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bfenaqvktz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfenaqvktz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bfenaqvktz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfenaqvktz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bfenaqvktz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfenaqvktz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bfenaqvktz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bfenaqvktz .gt_left {\n  text-align: left;\n}\n\n#bfenaqvktz .gt_center {\n  text-align: center;\n}\n\n#bfenaqvktz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bfenaqvktz .gt_font_normal {\n  font-weight: normal;\n}\n\n#bfenaqvktz .gt_font_bold {\n  font-weight: bold;\n}\n\n#bfenaqvktz .gt_font_italic {\n  font-style: italic;\n}\n\n#bfenaqvktz .gt_super {\n  font-size: 65%;\n}\n\n#bfenaqvktz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bfenaqvktz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bfenaqvktz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bfenaqvktz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bfenaqvktz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bfenaqvktz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bfenaqvktz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bfenaqvktz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bfenaqvktz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"participant\">participant</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"questions_correct\">questions_correct</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"questions_incorrect\">questions_incorrect</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">1</td>\n<td headers=\"questions_correct\" class=\"gt_row gt_right\">2</td>\n<td headers=\"questions_incorrect\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">2</td>\n<td headers=\"questions_correct\" class=\"gt_row gt_right\">1</td>\n<td headers=\"questions_incorrect\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">3</td>\n<td headers=\"questions_correct\" class=\"gt_row gt_right\">3</td>\n<td headers=\"questions_incorrect\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"participant\" class=\"gt_row gt_right\">...</td>\n<td headers=\"questions_correct\" class=\"gt_row gt_right\">...</td>\n<td headers=\"questions_incorrect\" class=\"gt_row gt_right\">...</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 18</div><div class='question-body'>\n\n\n> **Research Question 1:**  \n> Is the learning rate (training blocks) different between the two lesion location groups?\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- Do we want `cbind(num_successes, num_failures)`?\n\n- Ensure you are running models on only the data we are actually interested in. \n\n    + Are the healthy controls included in the research question under investigation?\n    + Are the testing blocks included in the research question, or only the learning blocks?\n\n- We could use model comparison via likelihood ratio tests (using `anova(model1, model2, model3, ...)`. For this question, we could compare:\n\n    + A model with just the change over the sequence of blocks\n    + A model with the change over the sequence of blocks *and* an overall difference between groups\n    + A model with groups differing with respect to their change over the sequence of blocks\n\n- What about the random effects part?  \n    \n    1. What are our observations grouped by? \n    2. What variables can vary within these groups? \n    3. What do you want your model to allow to vary within these groups?\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-10' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  1 - answers to the hints</button></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\n- Do we want `cbind(num_successes, num_failures)`?\n\n    + Yes, we don't a binary variable with correct/incorrect questions but the binomial variables NumCorrect and NumError representing, respectively, the aggregated count (out of 30) of correct and incorrect questions. As such, we will need the following: `cbind(NumCorrect, NumError)`\n\n- Ensure you are running models on only the data we are actually interested in. \n\n    + The healthy controls are not included in the research question under investigation, so we will exclude them.\n    + We are only interested in the learning blocks, and we will exclude the testing blocks (block > 7) \n    + You might want to store this data in a separate object, but in the code for the solution we will just use `filter()` *inside* the `glmer()`.   \n  \n- A model with just the change over the sequence of blocks:\n    - **outcome ~ block**\n- A model with the change over the sequence of blocks *and* an overall difference between groups:\n    - **outcome ~ block + lesion_location**\n- A model with groups differing with respect to their change *over the sequence of blocks:\n    - **outcome ~ block * lesion_location**\n    \n- What are our observations grouped by? \n    - repeated measures by-participant. i.e., the `ID` variable\n- What variables can vary within these groups? \n    - `Block` and `Phase`. Be careful though - you can create the `Phase` variable out of the `Block` variable, so really this is just one piece of information, encoded differently in two variables. \n    - The other variables (`lesion_location` and `group`) do **not** vary for each ID. Lesions don't suddenly change where they are located, nor do participants swap between being a patient vs a control (we don't need the group variable anyway as we are excluding the controls).  \nWhat do you want your model to allow to vary within these groups?\n    - Do you think the change over the course of the blocks is **the same** for everybody? Or do you think it varies? Is this variation important to think about in terms of your research question?   \n    \n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-11' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  2 - modelling</button></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.base <- glmer(cbind(NumCorrect, NumError) ~ block + (block | ID), \n                data = filter(nwl, block < 8, !is.na(lesion_location)),\n                family=binomial)\n\nm.loc0 <- glmer(cbind(NumCorrect, NumError) ~ block + lesion_location + (block | ID), \n                data=filter(nwl, block < 8, !is.na(lesion_location)),\n                family=binomial)\n\nm.loc1 <- glmer(cbind(NumCorrect, NumError) ~ block * lesion_location + (block | ID), \n                data=filter(nwl, block < 8, !is.na(lesion_location)),\n                family=binomial)\n\n\nanova(m.base, m.loc0, m.loc1, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: filter(nwl, block < 8, !is.na(lesion_location))\nModels:\nm.base: cbind(NumCorrect, NumError) ~ block + (block | ID)\nm.loc0: cbind(NumCorrect, NumError) ~ block + lesion_location + (block | ID)\nm.loc1: cbind(NumCorrect, NumError) ~ block * lesion_location + (block | ID)\n       npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)\nm.base    5 454.12 466.27 -222.06   444.12                     \nm.loc0    6 454.66 469.25 -221.33   442.66 1.4572  1     0.2274\nm.loc1    7 454.47 471.48 -220.23   440.47 2.1974  1     0.1382\n```\n\n\n:::\n:::\n\n\n\n:::int\nNo significant difference in learning rate between groups ($\\chi^2(1)=2.2, p = 0.138$).\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 19</div><div class='question-body'>\n\n\n> **Research Question 2**  \n> In the testing phase, does performance on the immediate test differ between lesion location groups, and does the retention from immediate to follow-up test differ between the two lesion location groups?\n\nLet's try a different approach to this. Instead of fitting various models and comparing them via likelihood ratio tests, just fit the one model which could answer both parts of the question above.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- This might required a bit more data-wrangling beforehand. Think about the order of your factor levels (alphabetically speaking, \"Follow-up\" comes before \"Immediate\")!\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-12' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-12', 'sol-start-12')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-12\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnwl_test <- filter(nwl, block > 7, !is.na(lesion_location)) |>\n    mutate(\n        Phase = factor(Phase), \n        Phase = fct_relevel(Phase, \"Immediate\")\n    )\n\nm.recall.loc <- glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (1 | ID), \n                      nwl_test, family=\"binomial\")\n\nsummary(m.recall.loc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized linear mixed model fit by maximum likelihood (Laplace\n  Approximation) [glmerMod]\n Family: binomial  ( logit )\nFormula: cbind(NumCorrect, NumError) ~ Phase * lesion_location + (1 |      ID)\n   Data: nwl_test\n\n     AIC      BIC   logLik deviance df.resid \n   139.3    145.2    -64.6    129.3       19 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.1556 -0.3352  0.0039  0.4963  1.3506 \n\nRandom effects:\n Groups Name        Variance Std.Dev.\n ID     (Intercept) 0.3626   0.6021  \nNumber of obs: 24, groups:  ID, 12\n\nFixed effects:\n                                        Estimate Std. Error z value Pr(>|z|)  \n(Intercept)                              -0.1124     0.3167  -0.355   0.7226  \nPhaseFollow-up                           -0.0278     0.2357  -0.118   0.9061  \nlesion_locationposterior                  0.9672     0.4211   2.297   0.0216 *\nPhaseFollow-up:lesion_locationposterior  -0.2035     0.3191  -0.638   0.5236  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) PhsFl- lsn_lc\nPhaseFllw-p -0.372              \nlsn_lctnpst -0.752  0.280       \nPhsFllw-p:_  0.275 -0.739 -0.385\n```\n\n\n:::\n:::\n\n\n\n\n\n__Note 1__: \n\nIn the above, we have made sure to select the patients by specifying `!is.na(lesion_location)`, meaning that we want those rows where the lesion location is not missing. As a reminder `!` is the negation function (not). As we saw in the earlier question, this excludes the 126 healthy controls, as well as the 9 patients for which we have missing values (NAs).\n\n__Note 2__:  \n\nWe didn't specify `(Phase | ID)` as the random effect because each participant only has 2 data points for Phase, and there is only one line that fits two data points. In other words, there is only one possible way to fit those two data points. As such, as each group of 2 points will have a perfect line fit, and the residuals $\\varepsilon_{ij}$ will all be 0. As a consequence of this, the residuals will have no variability as they are all 0, so $\\sigma_{\\epsilon}$ is 0 which in turn leads to problem with estimating the model coefficients.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsubset(nwl_test, ID == 'patient15')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     group lesion_location block PropCorrect NumCorrect NumError        ID\n1  patient        anterior     8   0.5333333         16       14 patient15\n13 patient        anterior     9   0.5333333         16       14 patient15\n       Phase\n1  Immediate\n13 Follow-up\n```\n\n\n:::\n:::\n\n\n\n\nIf you try using `(Phase | ID)` as random effect, you will see the following message:\n\n`boundary (singular) fit: see help('isSingular')`\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 20</div><div class='question-body'>\n\n\n\n1. In `family = binomial(link='logit')`. What function is used to relate the linear predictors in the model to the expected value of the response variable?  \n2. How do we convert this into something more interpretable?  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-13' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-13', 'sol-start-13')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-13\" style=\"display: none;\">\n\n\n \n1. The link function is the `logit`, or log-odds (other link functions are available).\n\n2. To convert log-odds to odds, we can use `exp()`, to get odds and odds ratios.  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 21</div><div class='question-body'>\n\n\nMake sure you pay attention to trying to interpret each fixed effect from your models.  \nThese can be difficult, especially when it's logistic, and especially when there are interactions.  \n\n- What is the increase in the odds of answering correctly in the immediate test if you were to have a posterior legion instead of an anterior legion?  \n\n<!-- \n\n<div class=\"optional-begin\"><button id='opt-start-14' class=\"jk-circle-right optional-icon clickable\" onclick=\"toggle_visibility('opt-body-14', 'opt-start-14')\"> Optional help: Our Solution to A4 </button></div><div class=\"optional-body\" id = \"opt-body-14\" style=\"display: none;\">\n\n -->\n<!-- ```{r eval=F} -->\n<!-- nwl_test <- filter(nwl, block > 7, !is.na(lesion_location)) %>% -->\n<!--   mutate( -->\n<!--     Phase = fct_relevel(factor(Phase),\"Immediate\") -->\n<!--   ) -->\n\n<!-- m.recall.loc <- glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (Phase | ID),  -->\n<!--                   nwl_test, family=\"binomial\") -->\n<!-- ``` -->\n<!-- \n\n</div><p class=\"optional-end\"></p>\n\n -->\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp(fixef(m.recall.loc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            (Intercept)                          PhaseFollow-up \n                              0.8936639                               0.9725791 \n               lesion_locationposterior PhaseFollow-up:lesion_locationposterior \n                              2.6306343                               0.8158868 \n```\n\n\n:::\n:::\n\n\n\n\n\n* `(Intercept)` ==> Anterior lesion group performance in immediate test. This is the odds of them answering correctly in the immediate test. \n* `PhaseFollow-up`  ==> Change in performance (for someone with an anterior lesion) from immediate to follow-up test. \n* `lesion_locationposterior` ==> Change in performance in immediate test were a patient to have a posterior lesion instead of an anterior lesion. \n* `PhaseFollow-up:lesion_locationposterior` ==> How change in performance from immediate to follow-up test would differ were a patient to have a posterior lesion instead of an anterior lesion.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp(fixef(m.recall.loc))[3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlesion_locationposterior \n                2.630634 \n```\n\n\n:::\n:::\n\n\n\n\n:::int\nHaving a posterior lesions is associated with 2.63 times the odds of answering correctly in the immediate test compared to having an anterior lesion.  \n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 22</div><div class='question-body'>\n\n\nRecreate the visualisation in @fig-nwl2.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Differences between groups in the average proportion of correct responses at each block](02ex_files/figure-html/fig-nwl2-1.png){#fig-nwl2 fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-15' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-15', 'sol-start-15')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-15\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(filter(nwl, !is.na(lesion_location)), aes(block, PropCorrect, \n                                                 color=lesion_location, \n                                                 shape=lesion_location)) +\n    #geom_line(aes(group=ID),alpha=.2) + \n    stat_summary(fun.data=mean_se, geom=\"pointrange\") + \n    stat_summary(data=filter(nwl, !is.na(lesion_location), block <= 7), \n                 fun=mean, geom=\"line\") + \n    geom_hline(yintercept=0.5, linetype=\"dashed\") + \n    geom_vline(xintercept=c(7.5, 8.5), linetype=\"dashed\") + \n    scale_x_continuous(breaks=1:9, \n                       labels=c(1:7, \"Test\", \"Follow-Up\")) + \n    theme_bw(base_size=10) + \n    labs(x=\"Block\", y=\"Proportion Correct\", \n         shape=\"Lesion\\nLocation\", color=\"Lesion\\nLocation\")\n```\n\n::: {.cell-output-display}\n![](02ex_files/figure-html/unnamed-chunk-57-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<!-- \n\n<div class='question-begin'>Question 23</div><div class='question-body'>\n\n -->\n<!-- This code is that we used to answer the question above, only we have edited it to change lesion location to be fitted with \"sum contrasts\".   -->\n\n<!-- ```{r echo=TRUE} -->\n<!-- nwl_test <- filter(nwl, block > 7, !is.na(lesion_location)) %>% -->\n<!--     mutate( -->\n<!--         Phase = factor(Phase), -->\n<!--         Phase = fct_relevel(Phase, \"Immediate\") -->\n<!--     ) -->\n\n<!-- m.recall.loc.effcoding <-  -->\n<!--     glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (1 | ID),  -->\n<!--           contrasts = list(lesion_location = \"contr.sum\"), -->\n<!--           data = nwl_test, family=\"binomial\") -->\n<!-- ``` -->\n\n\n<!-- The interpretation of this is going to get pretty tricky - we have a logistic regression, and we have different coding scheme for our categorical predictor, and we have an interaction.. &#x1f92f;   -->\n\n<!-- Can you work out the interpretation of the fixed effects estimates?   -->\n\n<!-- \n\n</div><p class=\"question-end\"></p>\n\n -->\n<!-- \n\n<div class=\"solution-begin\"><button id='sol-start-16' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-16', 'sol-start-16')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-16\" style=\"display: none;\">\n\n -->\n\n<!-- * `(Intercept)` ==> Overall performance in immediate test. This is the overall log-odds of answering correctly in the immediate test.  -->\n<!-- * `PhaseFollow-up`  ==> Average change in performance from immediate to follow-up test.  -->\n<!-- * `lesion_location1` ==> Anterior lesion group performance in immediate test relative to *overall average* performance in immediate test -->\n<!-- * `PhaseFollow-up:lesion_location1` ==> Change in performance from immediate to follow-up test, anterior lesion group relative to overall average -->\n\n\n<!-- **???**   -->\n<!-- How do we know that `lesion_location1` is the *anterior* and not the *posterior* lesion group?  -->\n<!-- We need to check the what the contrasts look like:   -->\n<!-- ```{r} -->\n<!-- contrasts(nwl_test$lesion_location) <- \"contr.sum\" -->\n<!-- contrasts(nwl_test$lesion_location) -->\n<!-- ``` -->\n<!-- Because there are only two levels to this variable, the estimate will simply flip sign (positive/negative) depending on which way the contrast is leveled.   -->\n\n\n<!-- ::: {.callout-note collapse=\"true\"} -->\n<!-- #### I liked my coefficients being named properly? -->\n\n<!-- ```{r} -->\n<!-- colnames(contrasts(nwl_test$lesion_location)) <- \"PeppaPig\" -->\n\n<!-- contrasts(nwl_test$lesion_location) -->\n\n<!-- modeltest <-  -->\n<!--     glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (1 | ID), -->\n<!--           nwl_test, family=\"binomial\") -->\n<!-- summary(modeltest)$coefficients -->\n<!-- ``` -->\n\n<!-- ::: -->\n\n<!-- \n\n</div><p class=\"solution-end\"></p>\n\n -->\n\n\n",
    "supporting": [
      "02ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}