<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Logistic Mixed Models | Longitudinal Mixed Models (linear growth)</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>MSMR</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Mixed Effects Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_intromlm.html">1: Intro to Multi-Level Modelling</a>
    </li>
    <li>
      <a href="02_lmm_log.html">2: Logistic | Longitudinal (linear)</a>
    </li>
    <li>
      <a href="03_nonlin.html">3: Longitudinal (non-linear)</a>
    </li>
    <li>
      <a href="04_other_ranef.html">4: Other Random Effect Structures</a>
    </li>
    <li>
      <a href="05_multilevel_recap.html">5: Recap | Individual Differences</a>
    </li>
    <li>
      <a href="06_rev.html">Break Week</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Data Reduction &amp; SEM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_efapca.html">PCA | EFA</a>
    </li>
    <li>
      <a href="08_cfa.html">CFA</a>
    </li>
    <li>
      <a href="09_path.html">Path Analysis</a>
    </li>
    <li>
      <a href="10_sem1.html">SEM 1</a>
    </li>
    <li>
      <a href="11_sem2.html">SEM 2</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa-info-circle"></span>
     
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="00_tidyverse_markdown.html">Recap - Tidyverse &amp; Markdown</a>
    </li>
    <li>
      <a href="zz_writeuplogistic.html">Write-up &amp; Logistic GCA</a>
    </li>
    <li>
      <a href="zz_assumpts.html">MLM Assumptions &amp; Diagnostics</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Logistic Mixed Models | Longitudinal Mixed Models (linear growth)</h1>

</div>


<div class="red">
<p><strong>Preliminaries</strong></p>
<ol style="list-style-type: decimal">
<li>Open Rstudio, and create a new RMarkdown document (giving it a title for this week).</li>
</ol>
</div>
<p>Last week we began to cover the idea of longitudinal mixed models (or ‘multi-level models’ - whatever we’re calling them!) in our exercises on Weight Change. The lectures this week have also introduced the idea of ‘change over time’ by looking at some data from Public Health England.</p>
<p>In the exercises this week, we’re going to concentrate on this in combination with the other topic this week, <em>Logistic</em> multi-level models. Then we’re going to look at <em>contrasts</em> (they’re a confusing topic, and can be pretty unintuitive, but we’re going to have to do it sometime!), and talk a little bit about making inferences.</p>
<div id="logistic-mlm" class="section level1">
<h1>Logistic MLM</h1>
<div class="frame">
<p><strong>Don’t forget to look back at other materials!</strong></p>
<p>Back in USMR, we introduced logistic regression in week 10. The lectures followed the example of some <a href="https://uoepsy.github.io/usmr/lectures/lecture_9.html#1">singing aliens that either survived or were splatted</a>, and the exercises used some simulated data based on a hypothetical study <a href="https://uoepsy.github.io/usmr/labs/09_glm.html">about inattentional blindness</a>.
That content will provide a lot of the groundwork for this week, so we recommend revisiting it if you feel like it might be useful.</p>
</div>
<div id="lmer-glmer" class="section level2">
<h2><code>lmer()</code> &gt;&gt; <code>glmer()</code></h2>
<p>Remember how we simply used <code>glm()</code> and could specify the <code>family = "binomial"</code> in order to fit a logistic regression? Well it’s much the same thing for multi-level models!</p>
<ul>
<li>Gaussian model: <code>lmer(y ~ x1 + x2 + (1 | g), data = data)</code><br />
</li>
<li>Binomial model: <code>glmer(y ~ x1 + x2 + (1 | g), data = data, family = binomial(link='logit'))</code>
<ul>
<li>or just <code>glmer(y ~ x1 + x2 + (1 | g), data = data, family = "binomial")</code></li>
<li>or <code>glmer(y ~ x1 + x2 + (1 | g), data = data, family = binomial)</code></li>
</ul></li>
</ul>
<div class="frame">
<p>Binary? Binomial? Huh?</p>
<p>Very briefly in the USMR materials we made the distinction between <strong>binary</strong> and <strong>binomial</strong>. This wasn’t hugely relevant at the time just because we only looked at binary outcomes.</p>
<p>For binary regression, all the data in our outcome variable has to be a 0 or a 1.<br />
For example, the <code>correct</code> variable below:</p>
<div id="takbwxroey" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#takbwxroey .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#takbwxroey .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#takbwxroey .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#takbwxroey .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#takbwxroey .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#takbwxroey .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#takbwxroey .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#takbwxroey .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#takbwxroey .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#takbwxroey .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#takbwxroey .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#takbwxroey .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#takbwxroey .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#takbwxroey .gt_from_md > :first-child {
  margin-top: 0;
}

#takbwxroey .gt_from_md > :last-child {
  margin-bottom: 0;
}

#takbwxroey .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#takbwxroey .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#takbwxroey .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#takbwxroey .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#takbwxroey .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#takbwxroey .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#takbwxroey .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#takbwxroey .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#takbwxroey .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#takbwxroey .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#takbwxroey .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#takbwxroey .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#takbwxroey .gt_left {
  text-align: left;
}

#takbwxroey .gt_center {
  text-align: center;
}

#takbwxroey .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#takbwxroey .gt_font_normal {
  font-weight: normal;
}

#takbwxroey .gt_font_bold {
  font-weight: bold;
}

#takbwxroey .gt_font_italic {
  font-style: italic;
}

#takbwxroey .gt_super {
  font-size: 65%;
}

#takbwxroey .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">participant</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">question</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">correct</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_left">1</td>
<td class="gt_row gt_left">1</td></tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_left">2</td>
<td class="gt_row gt_left">0</td></tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_left">3</td>
<td class="gt_row gt_left">1</td></tr>
    <tr><td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td></tr>
  </tbody>
  
  
</table>
</div>
<p>But we can re-express this information in a different way, when we know the total number of questions asked.</p>
<div id="wxtvpsarxg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#wxtvpsarxg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wxtvpsarxg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wxtvpsarxg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wxtvpsarxg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wxtvpsarxg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wxtvpsarxg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wxtvpsarxg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wxtvpsarxg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wxtvpsarxg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wxtvpsarxg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wxtvpsarxg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wxtvpsarxg .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#wxtvpsarxg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wxtvpsarxg .gt_from_md > :first-child {
  margin-top: 0;
}

#wxtvpsarxg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wxtvpsarxg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wxtvpsarxg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#wxtvpsarxg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wxtvpsarxg .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#wxtvpsarxg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wxtvpsarxg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wxtvpsarxg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wxtvpsarxg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wxtvpsarxg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wxtvpsarxg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#wxtvpsarxg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wxtvpsarxg .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#wxtvpsarxg .gt_left {
  text-align: left;
}

#wxtvpsarxg .gt_center {
  text-align: center;
}

#wxtvpsarxg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wxtvpsarxg .gt_font_normal {
  font-weight: normal;
}

#wxtvpsarxg .gt_font_bold {
  font-weight: bold;
}

#wxtvpsarxg .gt_font_italic {
  font-style: italic;
}

#wxtvpsarxg .gt_super {
  font-size: 65%;
}

#wxtvpsarxg .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">participant</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">questions_correct</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">questions_incorrect</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_left">2</td>
<td class="gt_row gt_left">1</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_left">1</td>
<td class="gt_row gt_left">2</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_left">3</td>
<td class="gt_row gt_left">0</td></tr>
    <tr><td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td></tr>
  </tbody>
  
  
</table>
</div>
<p>To model data when it is in this form, we can express our outcome as <code>cbind(questions_correct, questions_incorrect)</code></p>
</div>
<div class="question-begin">
Question A1
</div>
<div class="question-body">
<p>Load any of the packages you think you might be using today.</p>
<p>By now you may have started get into a sort of routine with R, and you might know what functions you like, and which you don’t. Because there are so many alternatives for doing the same thing, the packages and functions you use are very much up to you.</p>
<p>If I’m planning on doing some multi-level modelling, I will tend to load these by default at the top:</p>
<pre class="r"><code>library(tidyverse) # for everything
library(lme4) # for fitting models
library(broom.mixed) # for tidying model output</code></pre>
<p class="question-end">
</p>
</div>
<div class="optional-begin">
Novel Word Learning: Data Codebook<span id="opt-start-37" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-37&#39;, &#39;opt-start-37&#39;)"></span>
</div>
<div id="opt-body-37" class="optional-body" style="display: none;">
<pre class="r"><code>load(url(&quot;https://uoepsy.github.io/msmr/data/nwl.RData&quot;))</code></pre>
<p>In the <code>nwl</code> data set (accessed using the code above), participants with aphasia are separated into two groups based on the general location of their brain lesion: anterior vs. posterior. There is data on the numbers of correct and incorrect responses participants gave in each of a series of experimental blocks. There were 7 learning blocks, immediately followed by a test. Finally, participants also completed a follow-up test.<br />
<br>
Data were also collect from healthy controls.
<br>
Figure <a href="#fig:nwl-fig">1</a> shows the differences between groups in the average proportion of correct responses at each point in time (i.e., each block, test, and follow-up)</p>
<div class="figure" style="text-align: center"><span id="fig:nwl-fig"></span>
<img src="02_lmm_log_files/figure-html/nwl-fig-1.png" alt="Differences between groups in the average proportion of correct responses at each block" width="80%" />
<p class="caption">
Figure 1: Differences between groups in the average proportion of correct responses at each block
</p>
</div>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question A2
</div>
<div class="question-body">
<p>Load the data. Take a look around. Any missing values? Can you think of why?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-38" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-38&#39;, &#39;sol-start-38&#39;)"></span>
</div>
<div id="sol-body-38" class="solution-body" style="display: none;">
<pre class="r"><code>load(url(&quot;https://uoepsy.github.io/msmr/data/nwl.RData&quot;))
summary(nwl)</code></pre>
<pre><code>##      group      lesion_location     block    PropCorrect       NumCorrect   
##  control:126   anterior : 45    Min.   :1   Min.   :0.2000   Min.   : 6.00  
##  patient:117   posterior: 63    1st Qu.:3   1st Qu.:0.5333   1st Qu.:16.00  
##                NA&#39;s     :135    Median :5   Median :0.7000   Median :21.00  
##                                 Mean   :5   Mean   :0.6822   Mean   :20.47  
##                                 3rd Qu.:7   3rd Qu.:0.8333   3rd Qu.:25.00  
##                                 Max.   :9   Max.   :1.0000   Max.   :30.00  
##                                                                             
##     NumError              ID         Phase          
##  Min.   : 0.000   control1 :  9   Length:243        
##  1st Qu.: 5.000   control10:  9   Class :character  
##  Median : 9.000   control11:  9   Mode  :character  
##  Mean   : 9.535   control12:  9                     
##  3rd Qu.:14.000   control13:  9                     
##  Max.   :24.000   control14:  9                     
##                   (Other)  :189</code></pre>
<p>The only missing vales are in the lesion location, and it’s probably because the healthy controls don’t have any lesions.</p>
</div>
<p class="solution-end">
</p>
<blockquote>
<p><strong>Research Aims</strong><br />
Compare the two groups (those with anterior vs. posterior lesions) with respect to their accuracy of responses over the course of the study</p>
</blockquote>
<div class="question-begin">
Question A3: Initial thoughts
</div>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>What is our outcome?</li>
<li>Is it longitudinal? (simply, is there a temporal sequence to observations within a participant?)</li>
</ol>
<p><em>Hint:</em> Think carefully about question 1. There might be several variables which either fully or partly express the information we are considering the “outcome” here.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-39" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-39&#39;, &#39;sol-start-39&#39;)"></span>
</div>
<div id="sol-body-39" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>The outcome here is (in words) “the proportion of correct answers in each block.” This makes it tempting to look straight to the variable called <code>PropCorrect</code>. Unfortunately, this is encoded as a proportion (i.e., is bounded by 0 and 1), and of the models we have learned about so far, we don’t definitely have the necessary tools to model this.
<ul>
<li>linear regression = continuous <em>unbounded</em> outcome variable<br />
</li>
<li>logistic regression = binomial, expressed as <code>0</code> or <code>1</code> if the number of trials per observation is 1, and expressed as <code>cbind(num_successes, num_failures)</code> if the number of trials per observation is &gt;1.</li>
</ul></li>
<li>It is longitudinal in the sense that blocks are sequential. However, we probably wouldn’t call it a “longitudinal study” as that tends to get reserved for when we follow-up participants over a fairly long time period (months or years).</li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A4
</div>
<div class="question-body">
<blockquote>
<p><strong>Research Question 1:</strong><br />
Is the learning rate (training blocks) different between these two groups?</p>
</blockquote>
<p><strong>Hints</strong>:</p>
<ul>
<li><p>Do we want <code>cbind(num_successes, num_failures)</code>?</p></li>
<li><p>Make sure we’re running models on only the data we are actually interested in.<br />
</p></li>
<li><p>Think back to what we did in last week’s exercises using model comparison via likelihood ratio tests (using <code>anova(model1, model2, model3, ...)</code>. We could use this approach for this question, to compare:</p>
<ul>
<li>A model with just the change over the sequence of blocks</li>
<li>A model with the change over the sequence of blocks <em>and</em> an overall difference between groups</li>
<li>A model with groups differing with respect to their change over the sequence of blocks</li>
</ul></li>
<li><p>What about the random effects part?</p>
<ol style="list-style-type: decimal">
<li>What are our observations grouped by?</li>
<li>What variables can vary within these groups?</li>
<li>What do you want your model to allow to vary within these groups?</li>
</ol></li>
</ul>
<div class="optional-begin">
Suggested answers to the hints if you don’t know where to start<span id="opt-start-40" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-40&#39;, &#39;opt-start-40&#39;)"></span>
</div>
<div id="opt-body-40" class="optional-body" style="display: none;">
<ul>
<li>Make sure we’re running models on only the data we are actually interested in.
<ul>
<li>We want only the learning blocks, and none of the healthy controls.</li>
<li>You might want to store this data in a separate object, but in the code for the solutio we will just use <code>filter()</code> <em>inside</em> the <code>glmer()</code>.</li>
</ul></li>
<li>A model with just the change over the sequence of blocks:
<ul>
<li><strong>outcome ~ block</strong></li>
</ul></li>
<li>A model with the change over the sequence of blocks <em>and</em> an overall difference between groups:
<ul>
<li><strong>outcome ~ block + lesion_location</strong></li>
</ul></li>
<li>A model with groups differing with respect to their change *over the sequence of blocks:
<ul>
<li><strong>outcome ~ block * lesion_location</strong></li>
</ul></li>
<li>What are our observations grouped by?
<ul>
<li>repeated measures by-participant. i.e., the <code>ID</code> variable</li>
</ul></li>
<li>What variables can vary within these groups?
<ul>
<li><code>Block</code> and <code>Phase</code>. Be careful though - you can create the <code>Phase</code> variable out of the <code>Block</code> variable, so really this is just one piece of information, encoded differently in two variables.</li>
<li>The other variables (<code>lesion_location</code> and <code>group</code>) do <strong>not</strong> vary for each ID. Lesions don’t suddenly change where they are located, nor do participants swap between being a patient vs a control (we don’t need the group variable anyway as we are excluding the controls).<br />
What do you want your model to allow to vary within these groups?</li>
<li>Do you think the change over the course of the blocks is <strong>the same</strong> for everybody? Or do you think it varies? Is this variation important to think about in terms of your research question?</li>
</ul></li>
</ul>
</div>
<p class="optional-end">
</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-41" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-41&#39;, &#39;sol-start-41&#39;)"></span>
</div>
<div id="sol-body-41" class="solution-body" style="display: none;">
<pre class="r"><code>m.base &lt;- glmer(cbind(NumCorrect, NumError) ~ block + (block | ID), 
                data = filter(nwl, block &lt; 8, !is.na(lesion_location)),
                family=binomial)
m.loc0 &lt;- glmer(cbind(NumCorrect, NumError) ~ block + lesion_location + (block | ID), 
                data=filter(nwl, block &lt; 8, !is.na(lesion_location)),
                family=binomial)
m.loc1 &lt;- glmer(cbind(NumCorrect, NumError) ~ block * lesion_location + (block | ID), 
                data=filter(nwl, block &lt; 8, !is.na(lesion_location)),
                family=binomial)
#summary(m.loc1)
anova(m.base, m.loc0, m.loc1, test=&quot;Chisq&quot;)</code></pre>
<pre><code>## Data: filter(nwl, block &lt; 8, !is.na(lesion_location))
## Models:
## m.base: cbind(NumCorrect, NumError) ~ block + (block | ID)
## m.loc0: cbind(NumCorrect, NumError) ~ block + lesion_location + (block | ID)
## m.loc1: cbind(NumCorrect, NumError) ~ block * lesion_location + (block | ID)
##        npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## m.base    5 454.12 466.27 -222.06   444.12                     
## m.loc0    6 454.66 469.25 -221.33   442.66 1.4572  1     0.2274
## m.loc1    7 454.47 471.48 -220.23   440.47 2.1974  1     0.1382</code></pre>
<div class="int">
<p>No significant difference in learning rate between groups (<span class="math inline">\(\chi^2(1)=2.2, p = 0.138\)</span>).</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A5
</div>
<div class="question-body">
<blockquote>
<p><strong>Research Question 2</strong><br />
In the testing phase, does performance on the immediate test differ between lesion location groups, and does their retention from immediate to follow-up test differ?</p>
</blockquote>
<p>Let’s try a different approach to this. Instead of fitting various models and comparing them via likelihood ratio tests, just fit the one model which could answer both parts of the question above.</p>
<p><strong>Hints:</strong></p>
<ul>
<li>This might required a bit more data-wrangling before hand. Think about the order of your factor levels
(alphabetically speaking, “Follow-up” comes before “Immediate”)!</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-42" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-42&#39;, &#39;sol-start-42&#39;)"></span>
</div>
<div id="sol-body-42" class="solution-body" style="display: none;">
<pre class="r"><code>nwl_test &lt;- filter(nwl, block &gt; 7, !is.na(lesion_location)) %&gt;%
  mutate(
    Phase = fct_relevel(factor(Phase),&quot;Immediate&quot;)
  )

m.recall.loc &lt;- glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (Phase | ID), 
                  nwl_test, family=&quot;binomial&quot;)

summary(m.recall.loc)</code></pre>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: cbind(NumCorrect, NumError) ~ Phase * lesion_location + (Phase |  
##     ID)
##    Data: nwl_test
## 
##      AIC      BIC   logLik deviance df.resid 
##    142.6    150.9    -64.3    128.6       17 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.31708 -0.45014  0.03291  0.46924  1.09355 
## 
## Random effects:
##  Groups Name           Variance Std.Dev. Corr 
##  ID     (Intercept)    0.47660  0.6904        
##         PhaseFollow-up 0.02539  0.1593   -1.00
## Number of obs: 24, groups:  ID, 12
## 
## Fixed effects:
##                                         Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)                             -0.11375    0.35128  -0.324    0.746  
## PhaseFollow-up                          -0.02452    0.24634  -0.100    0.921  
## lesion_locationposterior                 0.99918    0.46868   2.132    0.033 *
## PhaseFollow-up:lesion_locationposterior -0.25437    0.33904  -0.750    0.453  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) PhsFl- lsn_lc
## PhaseFllw-p -0.578              
## lsn_lctnpst -0.750  0.435       
## PhsFllw-p:_  0.421 -0.729 -0.589
## optimizer (Nelder_Mead) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="interpreting-fixed-effects" class="section level2">
<h2>Interpreting fixed effects</h2>
<div class="frame">
<p>Take some time to remind yourself from USMR of the <a href="https://uoepsy.github.io/usmr/labs/09_glm.html#Introducing_GLM">interpretation of logistic regression coefficients</a>.</p>
<p>The interpretation of the fixed effects of a logistic multi-level model are no different.<br />
We can obtain them using:</p>
<ul>
<li><code>fixef(model)</code></li>
<li><code>summary(model)$coefficients</code></li>
<li><code>tidy(model)</code> <strong>from broom.mixed</strong><br />
</li>
<li>(there are probably more ways, but I can’t think of them right now!)</li>
</ul>
<p>It’s just that for multi-level models, we can model by-cluster andom variation around these effects.</p>
</div>
<div class="question-begin">
Question A6
</div>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>In <code>family = binomial(link='logit')</code>. What function is used to relate the linear predictors in the model to the expected value of the response variable?<br />
</li>
<li>How do we convert this into something more interpretable?</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-43" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-43&#39;, &#39;sol-start-43&#39;)"></span>
</div>
<div id="sol-body-43" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li><p>The link function is the <code>logit</code>, or log-odds (other link functions are available).</p></li>
<li><p>To convert log-odds to odds, we can use <code>exp()</code>, to get odds and odds ratios.</p></li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A7
</div>
<div class="question-body">
<p>Make sure you pay attention to trying to interpret each fixed effect from your models.<br />
These can be difficult, especially when it’s logistic, and especially when there are interactions.</p>
<ul>
<li>What is the increase in the odds of answering correctly in the immediate test for someone with a posterior legion compared to someone with an anterior legion?</li>
</ul>
<div class="optional-begin">
Optional help: Our Solution to A5<span id="opt-start-44" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-44&#39;, &#39;opt-start-44&#39;)"></span>
</div>
<div id="opt-body-44" class="optional-body" style="display: none;">
<pre class="r"><code>nwl_test &lt;- filter(nwl, block &gt; 7, !is.na(lesion_location)) %&gt;%
  mutate(
    Phase = fct_relevel(factor(Phase),&quot;Immediate&quot;)
  )

m.recall.loc &lt;- glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (Phase | ID), 
                  nwl_test, family=&quot;binomial&quot;)</code></pre>
</div>
<p class="optional-end">
</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-45" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-45&#39;, &#39;sol-start-45&#39;)"></span>
</div>
<div id="sol-body-45" class="solution-body" style="display: none;">
<ul>
<li><code>(Intercept)</code> ==&gt; Anterior lesion group performance in immediate test. This is the log-odds of them answering correctly in the immediate test.</li>
<li><code>PhaseFollow-up</code> ==&gt; Change in performance (for the anterior lesion group) from immediate to follow-up test.</li>
<li><code>lesion_locationposterior</code> ==&gt; Posterior lesion group performance in immediate test relative to anterior lesion group performance in immediate test</li>
<li><code>PhaseFollow-up:lesion_locationposterior</code> ==&gt; Change in performance from immediate to follow-up test, posterior lesion group relative to anterior lesion group</li>
</ul>
<pre><code>## lesion_locationposterior 
##                 2.716057</code></pre>
<div class="int">
<p>Those with posterior lesions have 2.72 times the odds of answering correctly in the immediate test compared to someone with an anterior lesion.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="optional-extra-exercise" class="section level2">
<h2>Optional extra exercise</h2>
<div class="question-begin">
Question A8: <strong>Extra</strong>
</div>
<div class="question-body">
<p>Recreate the visualisation in Figure <a href="#fig:nwl-fig2">2</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:nwl-fig2"></span>
<img src="02_lmm_log_files/figure-html/nwl-fig2-1.png" alt="Differences between groups in the average proportion of correct responses at each block" width="80%" />
<p class="caption">
Figure 2: Differences between groups in the average proportion of correct responses at each block
</p>
</div>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-46" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-46&#39;, &#39;sol-start-46&#39;)"></span>
</div>
<div id="sol-body-46" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(filter(nwl, !is.na(lesion_location)), aes(block, PropCorrect, 
                                            color=lesion_location, 
                                            shape=lesion_location)) +
  #geom_line(aes(group=ID),alpha=.2) + 
  stat_summary(fun.data=mean_se, geom=&quot;pointrange&quot;) + 
  stat_summary(data=filter(nwl, !is.na(lesion_location), block &lt;= 7), 
                           fun=mean, geom=&quot;line&quot;) + 
  geom_hline(yintercept=0.5, linetype=&quot;dashed&quot;) + 
  geom_vline(xintercept=c(7.5, 8.5), linetype=&quot;dashed&quot;) + 
  scale_x_continuous(breaks=1:9, labels=c(1:7, &quot;Test&quot;, &quot;Follow-Up&quot;)) + 
  theme_bw(base_size=10) + 
  labs(x=&quot;Block&quot;, y=&quot;Proportion Correct&quot;, shape=&quot;Lesion\nLocation&quot;, color=&quot;Lesion\nLocation&quot;)</code></pre>
<p><img src="02_lmm_log_files/figure-html/unnamed-chunk-10-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="optional-readings-inference-in-mlm" class="section level1">
<h1>Optional Readings: Inference in MLM</h1>
<div class="frame">
<p><strong>What, no p-values?</strong></p>
<p>Hang on, we have p-values for these models? You might have noticed that we didn’t get p-values last week<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> for <code>lmer()</code>, but we do now for <code>glmer()</code>?</p>
<p>The reason is partly just one of convention. There is a standard practice for determining the statistical significance of parameters in the generalised linear model, relying on asymptotic Wald tests which evaluate differences in log-likelihood.</p>
<p>When we are in the Gaussian (“normal”) world, we’re back in the world of sums of squares. In the rare occasion that you have a perfectly balanced experimental design, then it has been shown that ratios of sums of squares for multi-level models follow an <span class="math inline">\(F\)</span>-distribution, in which we know the numerator and denominator degrees of freedom (this means we can work out the degrees of freedom for the <span class="math inline">\(t\)</span>-test of our fixed effect parameters). Unfortunately, in the real world where things are not often perfectly balanced, determining the denominator degrees of freedom becomes unclear.</p>
</div>
<div class="frame">
<p><strong>What can we do??</strong></p>
<p>So far, we have been taking the approach of model comparison. This can be good because there are lots of different criteria for comparing models. Then when it comes to the specific effects of interest, we can then talk about the effect size (i.e., the <span class="math inline">\(\beta\)</span>), and about whether it improves model fit according to our criterion. Unfortunately, the reliability of the likelihood ratio tests which we have been using is dependent on the degrees of freedom issue above.</p>
<p>There are some alternatives:</p>
<ol style="list-style-type: decimal">
<li><p>Kenward-Rogers adjustment:</p>
<pre class="r"><code>library(pbkrtest)
KRmodcomp(model1, model2)</code></pre></li>
<li><p>Satterthwaite approximation:
(this will just add a column for p-values to your <code>summary(model)</code> output)</p>
<pre class="r"><code>library(lmerTest)
model &lt;- lmer(......
summary(model)</code></pre></li>
<li><p>Parametric bootstraps</p>
<pre class="r"><code>library(pbkrtest)
PBmodcomp(full_model, restricted_model)</code></pre></li>
</ol>
<p>If you want more information (not required reading for this course), then Julian Faraway has a page <a href="https://people.bath.ac.uk/jjf23/mixchange/index.html">here</a> with links to some worked examples, and Ben Bolker has a wealth of information on his <a href="http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#why-doesnt-lme4-display-denominator-degrees-of-freedomp-values-what-other-options-do-i-have">GLMM FAQ pages</a>.</p>
</div>
</div>
<div id="contrasts" class="section level1">
<h1>Contrasts</h1>
<p>We largely avoided the discussion of cotrasts in USMR because they can be quite incomprehensible at first, and we wanted to focus on really consolidating our learning of the linear model basics.</p>
<div class="frame">
<p><strong>What are contrasts and when are they relevant?</strong></p>
Recall when we have a categorical predictors? To continue the example in USMR, Martin’s lectures considered the utility of different types of toys (Playmo, SuperZings, and Lego).<br />

<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-14"></span>
<img src="images/loglong/leccontrasts.png" alt="[USMR Week 9 Lecture](https://uoepsy.github.io/usmr/lectures/lecture_8.html#36) utility of different toy_types" width="400px" />
<p class="caption">
Figure 3: <a href="https://uoepsy.github.io/usmr/lectures/lecture_8.html#36">USMR Week 9 Lecture</a> utility of different toy_types
</p>
</div>
<p>When we put a categorical variable into our model as a predictor, we are always relying on <strong>contrasts</strong>, which are essentially just combinations of 0s &amp; 1s which we use to define the differences which we wish to test.</p>
<p>The default, <em>treatment</em> coding, treats one level as a <strong>reference group</strong>, and results in coefficients which compare each group to that reference.<br />
When a variable is defined as a <strong>factor</strong> in R, there will always be an attached “attribute” defining the contrasts:</p>
<pre class="r"><code>#read the data
toy_utils &lt;- read_csv(&quot;https://uoepsy.github.io/msmr/data/toyutility.csv&quot;)

#make type a factor
toy_utils &lt;- toy_utils %&gt;%
  mutate(
    type = factor(type)
  )</code></pre>
<pre class="r"><code># look at the contrasts
contrasts(toy_utils$type)</code></pre>
<pre><code>##        playmo zing
## lego        0    0
## playmo      1    0
## zing        0    1</code></pre>
<p>Currently, the resulting coefficients from the contrasts above will correspond to:</p>
<ul>
<li>Intercept = estimated mean utility for Lego (reference group)</li>
<li>typeplaymo = estimated difference in mean utility Playmo vs Lego</li>
<li>typezing = estimated different in mean utility Zing vs Lego</li>
</ul>
</div>
<div class="question-begin">
Question B1
</div>
<div class="question-body">
<p>Read in the toy utility data from <a href="https://uoepsy.github.io/msmr/data/toyutility.csv">https://uoepsy.github.io/msmr/data/toyutility.csv</a>.<br />
We’re going to switch back to the normal <code>lm()</code> world here for a bit, so no multi-level stuff while we learn more about contrasts.</p>
<ol style="list-style-type: decimal">
<li><p>Fit the model below</p>
<pre class="r"><code>model_treatment &lt;- lm(UTILITY ~ type, data = toy_utils)</code></pre></li>
<li><p>Calculate the means for each group, and the differences between them, to match them to the coefficients from the model above</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-47" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-47&#39;, &#39;sol-start-47&#39;)"></span>
</div>
<div id="sol-body-47" class="solution-body" style="display: none;">
<p>You don’t have to do it this way. This was just the first way to calculate the difference in means that came to my head. <code>group_by()</code> will definitely come in handy though.</p>
<pre class="r"><code>toy_utils %&gt;% group_by(type) %&gt;%
  summarise(
    mutil = mean(UTILITY)
  ) %&gt;% 
  mutate(
    diff = mutil - mutil[type == &quot;lego&quot;]
  )</code></pre>
<pre><code>## # A tibble: 3 x 3
##   type   mutil   diff
##   &lt;fct&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 lego    2.82  0    
## 2 playmo  6.62  3.8  
## 3 zing    2.54 -0.280</code></pre>
<pre class="r"><code>coef(model_treatment)</code></pre>
<pre><code>## (Intercept)  typeplaymo    typezing 
##        2.82        3.80       -0.28</code></pre>
</div>
<p class="solution-end">
</p>
<div class="frame">
<p><strong>How can we change the way contrasts are coded?</strong></p>
<p>In our regression model we are fitting an intercept plus a coefficient for each explanatory variable, and any categorical predictors are coded as 0s and 1s.</p>
<p>We can add constraints to our the way our contrasts are coded. In fact, with the default <strong>treatment</strong> coding, we already have applied one - we constrained them such that the intercept (<span class="math inline">\(\beta_0\)</span>) = the mean of one of the groups.</p>
<div class="optional-begin">
Optional: Why constraints?<span id="opt-start-48" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-48&#39;, &#39;opt-start-48&#39;)"></span>
</div>
<div id="opt-body-48" class="optional-body" style="display: none;">
<p>Why do we not have:</p>
<ul>
<li><code>Intercept</code></li>
<li><code>typelego</code></li>
<li><code>typeplaymo</code></li>
<li><code>typezing</code></li>
</ul>
<p>The model has would become <strong>not identifiable</strong>. We cannot distinguish any more whether the group mean is due to a group effect or not. For example, we can get the same group mean <span class="math inline">\(μ_{lego}=10\)</span>, say, either by setting:</p>
<ul>
<li><span class="math inline">\(\beta_0=0\)</span> and <span class="math inline">\(\beta_1=10\)</span>, which interprets as “there is an effect due to being lego”</li>
<li><span class="math inline">\(\beta_0=10\)</span> and <span class="math inline">\(\beta_1=0\)</span>, which interprets as “there is no effect due to being lego”</li>
</ul>
</div>
<p class="optional-end">
</p>
<p>The other common constraint that is used is the <strong>sum-to-zero</strong> constraint.
Under this constraint the interpretation of the coefficients becomes:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> represents the global mean (sometimes referred to as the “grand mean”).</li>
<li><span class="math inline">\(\beta_1\)</span> the effect due to group <span class="math inline">\(i\)</span> — that is, the mean response in group <span class="math inline">\(i\)</span> minus the global mean.</li>
</ul>
<p><strong>Changing contrasts in R</strong><br />
There are two main ways to change the contrasts in R.</p>
<ol style="list-style-type: decimal">
<li><p>Change them in your data object.</p>
<pre class="r"><code>contrasts(toy_utils$type) &lt;- &quot;contr.sum&quot;</code></pre></li>
<li><p>Change them <em>only</em> in the fit of your model (don’t change them in the data object)</p>
<pre class="r"><code>model_sum &lt;- lm(UTILITY ~ type, contrasts = list(type = &quot;contr.sum&quot;), data = toy_utils)</code></pre></li>
</ol>
</div>
<div class="question-begin">
Question B2
</div>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>Using sum-to-zero contrasts, refit the same model of utility by toy-type.<br />
</li>
<li>Then calculate the global mean, and the differences from each mean to the global mean, to match them to the coefficients</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-49" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-49&#39;, &#39;sol-start-49&#39;)"></span>
</div>
<div id="sol-body-49" class="solution-body" style="display: none;">
<pre class="r"><code>model_sum &lt;- lm(UTILITY ~ type, contrasts = list(type = &quot;contr.sum&quot;), data = toy_utils)

globmean &lt;- mean(toy_utils$UTILITY)

toy_utils %&gt;% group_by(type) %&gt;%
  summarise(
    mutil = mean(UTILITY)
  ) %&gt;% 
  mutate(
    diff = mutil - globmean
  )</code></pre>
<pre><code>## # A tibble: 3 x 3
##   type   mutil  diff
##   &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 lego    2.82 -1.17
## 2 playmo  6.62  2.63
## 3 zing    2.54 -1.45</code></pre>
<pre class="r"><code>coef(model_sum)</code></pre>
<pre><code>## (Intercept)       type1       type2 
##    3.993333   -1.173333    2.626667</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B3
</div>
<div class="question-body">
<p>This code is what we used to answer question A5 above, only we have edited it to change lesion location to be fitted with sum-to-zero contrasts.</p>
<p>The interpretation of this is going to get pretty tricky - we have a logistic regression, and we have sum-to-zero contrasts, and we have an interaction.. 🤯</p>
<p>Can you work out the interpretation of the fixed effects estimates?</p>
<pre class="r"><code>nwl_test &lt;- filter(nwl, block &gt; 7, !is.na(lesion_location)) %&gt;%
  mutate(
    Phase = fct_relevel(factor(Phase),&quot;Immediate&quot;)
  )

m.recall.loc.sum &lt;- glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (Phase | ID), 
                      contrasts = list(lesion_location = &quot;contr.sum&quot;),
                  nwl_test, family=&quot;binomial&quot;)
rbind(summary(m.recall.loc.sum)$coefficients,
      summary(m.recall.loc)$coefficients)</code></pre>
<pre><code>##                                            Estimate Std. Error     z value
## (Intercept)                              0.38584493  0.2341574  1.64780173
## PhaseFollow-up                          -0.15170188  0.1688879 -0.89823996
## lesion_location1                        -0.49958816  0.2343374 -2.13191788
## PhaseFollow-up:lesion_location1          0.12717977  0.1695166  0.75024946
## (Intercept)                             -0.11375074  0.3512760 -0.32382152
## PhaseFollow-up                          -0.02452279  0.2463421 -0.09954771
## lesion_locationposterior                 0.99918109  0.4686765  2.13192071
## PhaseFollow-up:lesion_locationposterior -0.25437229  0.3390375 -0.75027786
##                                           Pr(&gt;|z|)
## (Intercept)                             0.09939336
## PhaseFollow-up                          0.36905763
## lesion_location1                        0.03301360
## PhaseFollow-up:lesion_location1         0.45310448
## (Intercept)                             0.74607317
## PhaseFollow-up                          0.92070341
## lesion_locationposterior                0.03301337
## PhaseFollow-up:lesion_locationposterior 0.45308737</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-50" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-50&#39;, &#39;sol-start-50&#39;)"></span>
</div>
<div id="sol-body-50" class="solution-body" style="display: none;">
<ul>
<li><code>(Intercept)</code> ==&gt; Overall performance in immediate test. This is the overall log-odds of answering correctly in the immediate test.</li>
<li><code>PhaseFollow-up</code> ==&gt; Average change in performance from immediate to follow-up test.</li>
<li><code>lesion_location1</code> ==&gt; Anterior lesion group performance in immediate test relative to <em>overall average</em> performance in immediate test</li>
<li><code>PhaseFollow-up:lesion_location1</code> ==&gt; Change in performance from immediate to follow-up test, anterior lesion group relative to overall average</li>
</ul>
<p><strong>???</strong><br />
How do we know that <code>lesion_location1</code> is the <em>anterior</em> and not the <em>posterior</em> lesion group?
We need to check the what the contrasts look like:</p>
<pre class="r"><code>contrasts(nwl_test$lesion_location) &lt;- &quot;contr.sum&quot;
contrasts(nwl_test$lesion_location)</code></pre>
<pre><code>##           [,1]
## anterior     1
## posterior   -1</code></pre>
<p>Because there are only two levels to this variable, the estimate will simply flip sign (positive/negative) depending on which way the contrast is levelled.</p>
<div class="optional-begin">
Optional: I liked my coefficients being named properly<span id="opt-start-51" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-51&#39;, &#39;opt-start-51&#39;)"></span>
</div>
<div id="opt-body-51" class="optional-body" style="display: none;">
<pre class="r"><code>colnames(contrasts(nwl_test$lesion_location)) &lt;- &quot;PeppaPig&quot;

contrasts(nwl_test$lesion_location)</code></pre>
<pre><code>##           PeppaPig
## anterior         1
## posterior       -1</code></pre>
<pre class="r"><code>modeltest &lt;- glmer(cbind(NumCorrect, NumError) ~ Phase * lesion_location + (Phase | ID),
                  nwl_test, family=&quot;binomial&quot;)
summary(modeltest)$coefficients</code></pre>
<pre><code>##                                          Estimate Std. Error    z value
## (Intercept)                             0.3858449  0.2341574  1.6478017
## PhaseFollow-up                         -0.1517019  0.1688879 -0.8982400
## lesion_locationPeppaPig                -0.4995882  0.2343374 -2.1319179
## PhaseFollow-up:lesion_locationPeppaPig  0.1271798  0.1695166  0.7502495
##                                          Pr(&gt;|z|)
## (Intercept)                            0.09939336
## PhaseFollow-up                         0.36905763
## lesion_locationPeppaPig                0.03301360
## PhaseFollow-up:lesion_locationPeppaPig 0.45310448</code></pre>
</div>
<p class="optional-end">
</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B4
</div>
<div class="question-body">
<p>Try playing around with the Toy Utility dataset again, fitting sum-to-zero contrasts.<br />
Can you re-level the factor first? What happens when you do?</p>
<p><strong>Tip:</strong> You can always revert easily to the treatment coding scheme, either by reading in the data again, or using</p>
<pre class="r"><code>contrasts(toy_utils$type) &lt;- NULL
contrasts(toy_utils$type)</code></pre>
<pre><code>##        playmo zing
## lego        0    0
## playmo      1    0
## zing        0    1</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-52" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-52&#39;, &#39;sol-start-52&#39;)"></span>
</div>
<div id="sol-body-52" class="solution-body" style="display: none;">
<p>No solution, just play!</p>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>We also didn’t get <span class="math inline">\(R^2\)</span>. Check out <a href="http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#how-do-i-compute-a-coefficient-of-determination-r2-or-an-analogue-for-glmms">http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#how-do-i-compute-a-coefficient-of-determination-r2-or-an-analogue-for-glmms</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
