<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Longitudinal (non-linear)</title>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/tabwid-1.1.2/tabwid.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>MSMR</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Mixed Effects Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_intromlm.html">1: Introduction to Multilevel Models</a>
    </li>
    <li>
      <a href="02_lmm_log.html">2: Logistic Multilevel Models</a>
    </li>
    <li>
      <a href="03_nonlin.html">3: Longitudinal Nonlinear Models</a>
    </li>
    <li>
      <a href="04_ranef.html">4: Random Effect Structures</a>
    </li>
    <li>
      <a href="05_multilevel_recap.html">5: Multilevel Modelling Recap</a>
    </li>
    <li class="dropdown-header">FLW: Flexible Learning Week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Data Reduction &amp; SEM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_efapca.html">6: PCA | EFA</a>
    </li>
    <li>
      <a href="07_cfa.html">7: CFA</a>
    </li>
    <li>
      <a href="08_path.html">8: Path Analysis</a>
    </li>
    <li>
      <a href="09_sem1.html">9: SEM 1</a>
    </li>
    <li>
      <a href="10_sem2.html">10: SEM 2</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-info-circle"></span>
     
    Extras
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="zz_tidyverse_markdown.html">Tidyverse &amp; Markdown Recap</a>
    </li>
    <li>
      <a href="zz_binary_binomial.html">Binary vs Binomial Data</a>
    </li>
    <li>
      <a href="zz_quickcontrasts.html">Contrasts: a Quick Overview</a>
    </li>
    <li>
      <a href="zz_lvp.html">Likelihood vs Probability</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Longitudinal (non-linear)</h1>

</div>


<div class="blue">
<p><strong>Preliminaries</strong></p>
<p>Create a new R Script or RMarkdown document (whichever you prefer working with) and give it a title for this week.</p>
<p><strong>Some extra background reading</strong></p>
<ul>
<li><a href="https://doi.org/10.1080/15248371003699969">Curran et al., 2010</a><br />
</li>
<li><a href="https://doi.org/10.1093/jole/lzv003">Winter &amp; Wieling, 2016</a></li>
</ul>
</div>
<p>We have already seen in the last couple of weeks that we can use MLM to study something ‘over the course of X’. In the novel word learning experiment from last week’s lab, we investigated the change in the probability of answering correctly over the course of the experimental blocks.</p>
<p>We’ve talked about how <strong>“longitudinal”</strong> is the term commonly used to refer to any data in which repeated measurements are taken over a continuous domain. This opens up the potential for observations to be unevenly spaced, or missing at certain points. It also, as will be the focus of this week, opens the door to thinking about how many effects of interest are likely to display <strong>non-linear patterns</strong>. These exercises focus on including higher-order polynomials in the multi-level model to capture non-linearity.</p>
<div id="linear-vs-non-linear" class="section level1">
<h1>Linear vs Non-Linear</h1>
<div style="display:inline-block;width:45%;margin:5px;vertical-align:middle">
<p>Suppose we had collected the data in Figure <a href="#fig:mcycle">1</a>, and we wanted to fit a model to predict <span class="math inline">\(y\)</span> based on the values of <span class="math inline">\(x\)</span>.</p>
<p>Let’s use our old friend linear regression, <span class="math inline">\(y = \beta_0 + \beta_1(x) + \varepsilon\)</span>.</p>
<p>We’ll get out some estimated coefficients, some standard errors, and some p-values:</p>
<ul>
<li>The intercept:<br />
<span class="math inline">\(\beta_0\)</span> = -110.28, SE = 19.54, p &lt; .001<br />
</li>
<li>The estimated coefficient of x:<br />
<span class="math inline">\(\beta_1\)</span> = 2.71, SE = 0.55, p &lt; .001</li>
</ul>
<p>Job done? Clearly not - we need only overlay model upon raw data (Figure <a href="#fig:mcycle3">2</a>) to see we are missing some key parts of the pattern.</p>
</div>
<div style="display:inline-block;width:45%;margin:5px;vertical-align:middle">
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:mcycle"></span>
<img src="03_nonlin_files/figure-html/mcycle-1.png" alt="A clearly non-linear pattern" width="80%" />
<p class="caption">
Figure 1: A clearly non-linear pattern
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:mcycle3"></span>
<img src="03_nonlin_files/figure-html/mcycle3-1.png" alt="Uh-oh... " width="80%" />
<p class="caption">
Figure 2: Uh-oh…
</p>
</div>
</div>
<div class="statbox">
<p><strong>Thoughts about Model + Error</strong></p>
<p>All our work here is in aim of making models of the world.</p>
<ol style="list-style-type: decimal">
<li>Models are just models. They are simplifications, and so they don’t perfectly fit to the observed world (indeed, how well a model fits to the world is often our metric for comparing models).<br />
</li>
<li><span class="math inline">\(y - \widehat{y}\)</span>. Our observed data minus our model predicted values (i.e. in linear regression our “residuals”) reflect everything that we don’t account for in our model</li>
<li>In an ideal world, our model accounts for all the systematic relationships, and what is left over (our residuals) is just randomness. If our model is mis-specified, or misses out something systematic, then our residuals will reflect this.</li>
<li>We check for this by examining how much like randomness the residuals appear to be (zero mean, normally distributed, constant variance, i.i.d (“independent and identically distributed”) - i.e., what gets referred to as the “assumptions”).</li>
<li>We will <strong>never</strong> know whether our residuals contain only randomness, because we can never observe <em>everything</em>.</li>
</ol>
<p><h/></p>
<p>Let’s just do a quick <code>plot(model)</code> for some diagnostic plots of my linear model:
<img src="03_nonlin_files/figure-html/unnamed-chunk-2-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Does it look like the residuals are independently distributed? Not really.
We need to find some way of incorporating the non-linear relationship between y and x into our model.</p>
</div>
</div>
<div id="what-is-a-polynomial" class="section level1">
<h1>What is a polynomial?</h1>
<div class="statbox">
<p>Polynomials are mathematical expressions which involve a sum of powers. For instance:</p>
<ul>
<li><span class="math inline">\(y = 4 + x + x^2\)</span> is a second-order polynomial as the highest power of <span class="math inline">\(x\)</span> that appears is <span class="math inline">\(x^2\)</span><br />
</li>
<li><span class="math inline">\(y = 9x + 2x^2 + 4x^3\)</span> is a third-order polynomial as the highest power of <span class="math inline">\(x\)</span> that appears is <span class="math inline">\(x^3\)</span><br />
</li>
<li><span class="math inline">\(y = x^6\)</span> is a sixth-order polynomial as the highest power of <span class="math inline">\(x\)</span> that appears is <span class="math inline">\(x^6\)</span></li>
</ul>
</div>
<p>For our purposes, extending our model to include higher-order terms can fit non-linear relationships between two variables. For instance, fitting models with linear and quadratic terms (<span class="math inline">\(y_i\)</span> = <span class="math inline">\(\beta_0 + \beta_1 x_{i} \ + \beta_2 x^2_i + \varepsilon_i\)</span>) and extending these to cubic (<span class="math inline">\(y_i\)</span> = <span class="math inline">\(\beta_0 + \beta_1 x_{i} \ + \beta_2 x^2_i + \beta_3 x^3_i + \varepsilon_i\)</span>) (or beyond), may aid in modelling nonlinear patterns.</p>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-3-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="statbox">
<p><strong>What are we interested in here?</strong></p>
<p>As the order of polynomials increases, we tend to be less interested in these terms in our model. Linear change is the easiest to think about: are things going up over the course of <span class="math inline">\(x\)</span>, or down? (or neither?). Quadratic change is the next most interesting, and it may help to think of this as the “rate of change”. For instance, in the plot below, it is the quadratic term which differs between the two groups trajectories.</p>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-4-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-1&#39;, &#39;opt-start-1&#39;)"> Positive and negative quadratic terms</span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<p><img src="03_nonlin_files/figure-html/quadfig-1.png" width="80%" style="display: block; margin: auto;" /></p>
<!-- 

<div class="optional-begin"><span id='opt-start-2' class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-2', 'opt-start-2')">  Code to create plot</span></div><div class="optional-body" id = "opt-body-2" style="display: none;">

 -->
<!-- ```{r eval=FALSE} -->
<!-- tibble( -->
<!--   x = -10:10, -->
<!--   y = x^2, -->
<!--   y1 = -x^2 -->
<!-- ) %>% pivot_longer(y:y1) %>% -->
<!--   mutate(name = ifelse(name=="y","quadratic term is positive \n Y = X^2", "quadratic term is negative \n Y = -X^2")) %>% -->
<!--   ggplot(.,aes(x=x,y=value,col=name)) + -->
<!--   geom_line()+ -->
<!--   guides(col=FALSE)+ -->
<!--   facet_wrap(~name, scales="free_y") -->
<!-- ``` -->
<!-- 

</div><p class="optional-end"></p>

 -->
</div>
<p class="optional-end">
</p>
</div>
<div id="raw-polynomials" class="section level2">
<h2>Raw Polynomials</h2>
<div style="display:inline-block; width: 60%; vertical-align: top">
<p>There are two types of polynomial we can construct. “Raw” (or “Natural”) polynomials are the straightforward ones you might be expecting the table to the right to be filled with.</p>
<p>These are simply the original values of the x variable to the power of 2, 3 and so on.</p>
<p>We can quickly get these in R using the <code>poly()</code> function, with <code>raw = TRUE</code>.</p>
<p>If you want to create “raw” polynomials, make sure to specify <code>raw = TRUE</code> or you will not get what you want because the default behaviour is <code>raw = FALSE</code>.</p>
</div>
<div style="display:inline-block; width: 30%;">
<center>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
x
</th>
<th style="text-align:left;">
x^2
</th>
<th style="text-align:left;">
x^3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
?
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
?
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
?
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
?
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
?
</td>
</tr>
<tr>
<td style="text-align:left;">
…
</td>
<td style="text-align:left;">
…
</td>
<td style="text-align:left;">
…
</td>
</tr>
</tbody>
</table>
</center>
</div>
<pre class="r"><code>poly(1:10, degree = 3, raw=TRUE)</code></pre>
<pre><code>##        1   2    3
##  [1,]  1   1    1
##  [2,]  2   4    8
##  [3,]  3   9   27
##  [4,]  4  16   64
##  [5,]  5  25  125
##  [6,]  6  36  216
##  [7,]  7  49  343
##  [8,]  8  64  512
##  [9,]  9  81  729
## [10,] 10 100 1000
## attr(,&quot;degree&quot;)
## [1] 1 2 3
## attr(,&quot;class&quot;)
## [1] &quot;poly&quot;   &quot;matrix&quot;</code></pre>
<div style="background-color: #eafaff; border-radius: 5px; padding: 20px 20px 10px 20px; margin-top: 20px; margin-bottom: 20px;">
<p><strong>Raw polynomials are correlated</strong></p>
<p>With raw (or “natural”) polynomials, the terms <code>poly1</code>, <code>poly2</code> and <code>poly3</code> are correlated.<br />
Think think about why this might be - by definition, as <span class="math inline">\(x^1\)</span> increases, so will <span class="math inline">\(x^2\)</span>, and so will <span class="math inline">\(x^3\)</span> and so on.</p>
<p>We can visualise them:</p>
<pre class="r"><code>matplot(poly(1:10, 3, raw=T), type=&quot;l&quot;)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-7-1.png" width="80%" style="display: block; margin: auto;" />
And measure the correlation coefficients:</p>
<pre class="r"><code>cor(poly(1:10, 3, raw=T)) %&gt;% round(2)</code></pre>
<pre><code>##      1    2    3
## 1 1.00 0.97 0.93
## 2 0.97 1.00 0.99
## 3 0.93 0.99 1.00</code></pre>
Why might this be a problem?<br />
Well, this multicollinearity can lead to estimation problems, and means that our parameter estimates may change considerably depending upon what terms we include in our model, and it becomes more difficult to determine which ones are important, and what the effect sizes are.<br />
Table <a href="#tab:rawpolytab">1</a> below shows the coefficients for models fitted to a randomly generated dataset, with <code>poly1</code>, <code>poly1+poly2</code>, and <code>poly1+poly2+poly3</code> as predictors (where <code>poly1</code>-<code>poly3</code> are <strong>natural</strong> polynomials). Notice that they change with the addition of each term.
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:rawpolytab">Table 1: </span>Incremental addition of raw polynomial terms
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:left;">
y~poly1
</th>
<th style="text-align:left;">
y~poly1+poly2
</th>
<th style="text-align:right;">
y~poly1+poly2+poly3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:left;">
639.37
</td>
<td style="text-align:left;">
-199.68
</td>
<td style="text-align:right;">
-0.12
</td>
</tr>
<tr>
<td style="text-align:left;">
poly1
</td>
<td style="text-align:left;">
-144.01
</td>
<td style="text-align:left;">
275.52
</td>
<td style="text-align:right;">
98.52
</td>
</tr>
<tr>
<td style="text-align:left;">
poly2
</td>
<td style="text-align:left;">
<ul>
<li></td>
<td style="text-align:left;">
-38.14
</td>
<td style="text-align:right;">
0.24
</td>
</tr>
<tr>
<td style="text-align:left;">
poly3
</td>
<td style="text-align:left;">
<ul>
<li></td>
<td style="text-align:left;">
<ul>
<li></td>
<td style="text-align:right;">
-2.33
</td>
</tr>
</tbody>
</table></li>
</ul></li>
</ul></li>
</ul>
</div>
</div>
<div id="orthogonal-polynomials" class="section level2">
<h2>Orthogonal Polynomials</h2>
<p>“Orthogonal” polynomials are uncorrelated (hence the name).
We can get these for <span class="math inline">\(x = 1,2,...,9,10\)</span> using the following code:</p>
<pre class="r"><code>poly(1:10, degree = 3, raw = FALSE)</code></pre>
<pre><code>##                 1           2          3
##  [1,] -0.49543369  0.52223297 -0.4534252
##  [2,] -0.38533732  0.17407766  0.1511417
##  [3,] -0.27524094 -0.08703883  0.3778543
##  [4,] -0.16514456 -0.26111648  0.3346710
##  [5,] -0.05504819 -0.34815531  0.1295501
##  [6,]  0.05504819 -0.34815531 -0.1295501
##  [7,]  0.16514456 -0.26111648 -0.3346710
##  [8,]  0.27524094 -0.08703883 -0.3778543
##  [9,]  0.38533732  0.17407766 -0.1511417
## [10,]  0.49543369  0.52223297  0.4534252
## attr(,&quot;coefs&quot;)
## attr(,&quot;coefs&quot;)$alpha
## [1] 5.5 5.5 5.5
## 
## attr(,&quot;coefs&quot;)$norm2
## [1]    1.0   10.0   82.5  528.0 3088.8
## 
## attr(,&quot;degree&quot;)
## [1] 1 2 3
## attr(,&quot;class&quot;)
## [1] &quot;poly&quot;   &quot;matrix&quot;</code></pre>
<p>Notice that the first order term has been scaled, so instead of the values 1 to 10, we have values ranging from -0.5 to +0.5, centered on 0.</p>
<pre class="r"><code>colMeans(poly(1:10, degree = 3, raw = FALSE)) %&gt;%
    round(2)</code></pre>
<pre><code>## 1 2 3 
## 0 0 0</code></pre>
<p>As you can see from the output above, which computes the mean of each column, each predictor has mean 0, so they are mean-centred. <strong>This is a key fact and will affect the interpretation of our predictors later on</strong>.</p>
<p>Think about what this means for <span class="math inline">\(x^2\)</span>. It will be uncorrelated with <span class="math inline">\(x\)</span> (because <span class="math inline">\(-0.5^2 = 0.5^2\)</span>)!</p>
<pre class="r"><code>matplot(poly(1:10, 3, raw=F), type=&quot;l&quot;)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-11-1.png" width="80%" style="display: block; margin: auto;" />
The correlations are zero!</p>
<pre class="r"><code>cor(poly(1:10, 3, raw=F)) %&gt;% round(2)</code></pre>
<pre><code>##   1 2 3
## 1 1 0 0
## 2 0 1 0
## 3 0 0 1</code></pre>
We can then fit the same models <code>y~poly1</code>, <code>y~poly1+poly2</code>, and <code>y~poly1+poly2+poly3</code> as predictors (where <code>poly1</code>-<code>poly3</code> are now <strong>orthogonal</strong> polynomials), and see that estimated coefficients do not change between models:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:orthpolytab">Table 2: </span>Incremental addition of orthogonal polynomial terms
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:left;">
y~poly1
</th>
<th style="text-align:left;">
y~poly1+poly2
</th>
<th style="text-align:right;">
y~poly1+poly2+poly3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:left;">
-152.66
</td>
<td style="text-align:left;">
-152.66
</td>
<td style="text-align:right;">
-152.66
</td>
</tr>
<tr>
<td style="text-align:left;">
poly1
</td>
<td style="text-align:left;">
-1307.99
</td>
<td style="text-align:left;">
-1307.99
</td>
<td style="text-align:right;">
-1307.99
</td>
</tr>
<tr>
<td style="text-align:left;">
poly2
</td>
<td style="text-align:left;">
<ul>
<li></td>
<td style="text-align:left;">
-876.36
</td>
<td style="text-align:right;">
-876.36
</td>
</tr>
<tr>
<td style="text-align:left;">
poly3
</td>
<td style="text-align:left;">
<ul>
<li></td>
<td style="text-align:left;">
<ul>
<li></td>
<td style="text-align:right;">
-129.26
</td>
</tr>
</tbody>
</table></li>
</ul></li>
</ul></li>
</ul>
<div class="statbox">
<p><strong>Remember what zero is!</strong></p>
<p>With orthogonal polynomials, you need to be careful about interpreting coefficients. For raw polynomials the intercept remains the y-intercept (i.e., where the line hits the y-axis). The higher order terms can then be thought of from that starting point - e.g., “where <span class="math inline">\(x\)</span> is 2, <span class="math inline">\(\widehat{y}\)</span> is <span class="math inline">\(\beta_0 + \beta_1 \cdot 2 + \beta_2 \cdot 2^2 + \beta_3 \cdot 2^3 ...\)</span>”.<br />
<br>
For orthogonal polynomials, the interpretation becomes more tricky. The intercept is the overall average of y, the linear predictor is the linear change pivoting around the mean of <span class="math inline">\(x\)</span> (rather than <span class="math inline">\(x = 0\)</span>), the quadratic term corresponds to the steepness of the quadratic curvature (“how curvy is it?”), the cubic term to the steepness at the inflection points (“how wiggly is it?”), and so on.</p>
</div>
</div>
<div id="some-useful-code-from-dan" class="section level2">
<h2>Some useful code from Dan</h2>
<div class="rtip">
<p>It’s possible to use <code>poly()</code> internally in fitting our linear model, if we want:</p>
<pre class="r"><code>lm(y ~ poly(x, 3, raw = T), data = df)</code></pre>
<p><br>
Unfortunately, the coefficients will end up having long messy names <code>poly(x, 3, raw = T)[1]</code>, <code>poly(x, 3, raw = T)[2]</code> etc.<br />
<br>
It is probably nicer if we add the polynomials to our data itself. As it happens, Dan has provided a nice little function which attaches these as columns to our data, naming them <code>poly1</code>, <code>poly2</code>, etc.</p>
<pre class="r"><code># import Dan&#39;s code and make it available in our own R session
# you must do this in every script you want to use this function
source(&quot;https://uoepsy.github.io/msmr/functions/code_poly.R&quot;)

mydata &lt;- code_poly(df = mydata, predictor = &#39;time&#39;, poly.order = 3, 
                    orthogonal = FALSE, draw.poly = FALSE)
head(mydata)</code></pre>
<pre><code>## # A tibble: 6 × 6
##    time     y time.Index poly1 poly2 poly3
##   &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1  96.8          1     1     1     1
## 2     2 179.           2     2     4     8
## 3     3 234.           3     3     9    27
## 4     4 248.           4     4    16    64
## 5     5 209.           5     5    25   125
## 6     6  97.2          6     6    36   216</code></pre>
<p>Both will produce the same model output (but Dan’s method produces these nice neat names for the coefficients!), and we can just put the terms into our model directly as <code>lm(y ~ poly1 + poly2 + poly3, data = mydata)</code>.</p>
<div class="optional-begin">
<span id="opt-start-3" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-3&#39;, &#39;opt-start-3&#39;)"> Demonstration</span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<p>Our data:</p>
<pre class="r"><code>head(df)</code></pre>
<pre><code>## # A tibble: 6 × 2
##       x     y
##   &lt;int&gt; &lt;dbl&gt;
## 1     1  102.
## 2     2  203.
## 3     3  301.
## 4     4  397.
## 5     5  492.
## 6     6  585.</code></pre>
<p>A messy model:</p>
<pre class="r"><code>m.messy &lt;- lm(y ~ poly(x, 3, raw=T), data = df)</code></pre>
<template id="9d132093-66f3-4d59-a8bd-5cf6029b0e7a"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  border-color: transparent;
  caption-side: top;
}
.tabwid-caption-bottom table{
  caption-side: bottom;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td, .tabwid th {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
.katex-display {
    margin: 0 0 !important;
}
</style><div class="tabwid"><style>.cl-03da3f84{table-layout:auto;}.cl-03d020f8{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-03d4ccde{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-03d4ecbe{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03d4ecc8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03d4ecc9{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-03da3f84'><thead><tr style="overflow-wrap:break-word;"><th class="cl-03d4ecbe"><p class="cl-03d4ccde"><span class="cl-03d020f8">term</span></p></th><th class="cl-03d4ecbe"><p class="cl-03d4ccde"><span class="cl-03d020f8">estimate</span></p></th><th class="cl-03d4ecbe"><p class="cl-03d4ccde"><span class="cl-03d020f8">std.error</span></p></th><th class="cl-03d4ecbe"><p class="cl-03d4ccde"><span class="cl-03d020f8">statistic</span></p></th><th class="cl-03d4ecbe"><p class="cl-03d4ccde"><span class="cl-03d020f8">p.value</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">(Intercept)</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">2.37</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">2.17</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">1.09</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">.317</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">poly(x, 3, raw = T)1</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">99.70</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">1.63</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">61.30</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">&lt; .001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">poly(x, 3, raw = T)2</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">0.32</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">0.34</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">0.96</span></p></td><td class="cl-03d4ecc8"><p class="cl-03d4ccde"><span class="cl-03d020f8">.376</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-03d4ecc9"><p class="cl-03d4ccde"><span class="cl-03d020f8">poly(x, 3, raw = T)3</span></p></td><td class="cl-03d4ecc9"><p class="cl-03d4ccde"><span class="cl-03d020f8">-0.13</span></p></td><td class="cl-03d4ecc9"><p class="cl-03d4ccde"><span class="cl-03d020f8">0.02</span></p></td><td class="cl-03d4ecc9"><p class="cl-03d4ccde"><span class="cl-03d020f8">-6.40</span></p></td><td class="cl-03d4ecc9"><p class="cl-03d4ccde"><span class="cl-03d020f8">.001</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="8402aee6-498f-4a86-a13e-9bddb11a9b37"></div>
<script>
var dest = document.getElementById("8402aee6-498f-4a86-a13e-9bddb11a9b37");
var template = document.getElementById("9d132093-66f3-4d59-a8bd-5cf6029b0e7a");
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p>Dan’s code, and a neat model:</p>
<pre class="r"><code>df &lt;- code_poly(df = df, predictor = &#39;x&#39;, poly.order = 3, 
                orthogonal = FALSE, draw.poly = FALSE)
mDan &lt;- lm(y ~ poly1 + poly2 + poly3, data = df)</code></pre>
<template id="59f100d6-4432-4106-89c9-aa893a9ca919"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  border-color: transparent;
  caption-side: top;
}
.tabwid-caption-bottom table{
  caption-side: bottom;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td, .tabwid th {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
.katex-display {
    margin: 0 0 !important;
}
</style><div class="tabwid"><style>.cl-03f57308{table-layout:auto;}.cl-03edb442{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-03f09cde{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-03f0ae72{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03f0ae7c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03f0ae7d{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-03f57308'><thead><tr style="overflow-wrap:break-word;"><th class="cl-03f0ae72"><p class="cl-03f09cde"><span class="cl-03edb442">term</span></p></th><th class="cl-03f0ae72"><p class="cl-03f09cde"><span class="cl-03edb442">estimate</span></p></th><th class="cl-03f0ae72"><p class="cl-03f09cde"><span class="cl-03edb442">std.error</span></p></th><th class="cl-03f0ae72"><p class="cl-03f09cde"><span class="cl-03edb442">statistic</span></p></th><th class="cl-03f0ae72"><p class="cl-03f09cde"><span class="cl-03edb442">p.value</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">(Intercept)</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">2.37</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">2.17</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">1.09</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">.317</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">poly1</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">99.70</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">1.63</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">61.30</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">&lt; .001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">poly2</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">0.32</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">0.34</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">0.96</span></p></td><td class="cl-03f0ae7c"><p class="cl-03f09cde"><span class="cl-03edb442">.376</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-03f0ae7d"><p class="cl-03f09cde"><span class="cl-03edb442">poly3</span></p></td><td class="cl-03f0ae7d"><p class="cl-03f09cde"><span class="cl-03edb442">-0.13</span></p></td><td class="cl-03f0ae7d"><p class="cl-03f09cde"><span class="cl-03edb442">0.02</span></p></td><td class="cl-03f0ae7d"><p class="cl-03f09cde"><span class="cl-03edb442">-6.40</span></p></td><td class="cl-03f0ae7d"><p class="cl-03f09cde"><span class="cl-03edb442">.001</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="58e668b8-2db5-41ac-a23e-13d07ae0ae4e"></div>
<script>
var dest = document.getElementById("58e668b8-2db5-41ac-a23e-13d07ae0ae4e");
var template = document.getElementById("59f100d6-4432-4106-89c9-aa893a9ca919");
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

</div>
<p class="optional-end">
</p>
</div>
</div>
</div>
<div id="exercises-cognitive-performance" class="section level1">
<h1>Exercises: Cognitive performance</h1>
<div class="imp">
<p><strong>STOP AND THINK: Are you using R effectively?</strong></p>
<p>There are lots of different ways to organise your file system/your life in R. You might be creating a new project each week, or a new folder, or just a new .Rmd. There’s no <em>best</em> way to organise this - it is personal preference.</p>
<p>However, one thing which is common across most approaches is that having a lot of irrelevant stuff in your environment (top right pane) can get confusing and messy.</p>
<p>We encourage you now to clear your environment for this week, and <em>then</em> load in the data.</p>
<p>If you are worried that you are going to lose some of the objects in your environment, then this may be a sign that you are not using R to its full potential. The idea is that we can recreate all of our analyses by just running the relevant code in our script!</p>
<div class="yellow">
<p>Alongside <strong>lme4</strong> and <strong>tidyverse</strong> and possibly <strong>broom.mixed</strong>, we’re going to be using some of Dan’s useful functions for getting p-values and coding polynomials.</p>
<p>The <code>source()</code> function basically takes in R code and evaluates it. You can download an R script with Dan’s code <a href="https://uoepsy.github.io/msmr/functions/code_poly.R">here</a>.</p>
<p>But you can also source this script directly from the URL, which runs the R code and creates the functions in your environment. Typically, we want these at the top of our document, because it’s similar to loading a package:</p>
<pre class="r"><code>library(tidyverse)
library(lme4)
library(broom.mixed)
source(&quot;https://uoepsy.github.io/msmr/functions/code_poly.R&quot;)</code></pre>
</div>
</div>
<div class="frame">
<p><strong>Az.rda Data</strong></p>
<p>30 Participants with probably Alzheimer’s Disease completed 3 tasks over 10 time points: A memory task, and two scales investigating ability to undertake complex activities of daily living (cADL) and simple activities of daily living (sADL). Performance on all of tasks was calculated as a percentage of total possible score, thereby ranging from 0 to 100.</p>
<p>The data is available at <a href="https://uoepsy.github.io/data/Az.rda">https://uoepsy.github.io/data/Az.rda</a>.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:left;">
description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Subject
</td>
<td style="text-align:left;">
Unique Subject Identifier
</td>
</tr>
<tr>
<td style="text-align:left;">
Time
</td>
<td style="text-align:left;">
Time point of the study (1 to 10)
</td>
</tr>
<tr>
<td style="text-align:left;">
Task
</td>
<td style="text-align:left;">
Task type (Memory, cADL, sADL)
</td>
</tr>
<tr>
<td style="text-align:left;">
Performance
</td>
<td style="text-align:left;">
Score on test
</td>
</tr>
</tbody>
</table>
</div>
<div class="question-begin">
Question A1
</div>
<div class="question-body">
<p>Load in the data and examine it.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-4&#39;, &#39;sol-start-4&#39;)"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<pre class="r"><code>load(url(&quot;https://uoepsy.github.io/data/Az.rda&quot;))
summary(Az)</code></pre>
<pre><code>##     Subject         Time          Task      Performance   
##  1      : 30   Min.   : 1.0   cADL  :300   Min.   : 2.00  
##  2      : 30   1st Qu.: 3.0   sADL  :300   1st Qu.:40.00  
##  3      : 30   Median : 5.5   Memory:300   Median :52.00  
##  4      : 30   Mean   : 5.5                Mean   :49.27  
##  5      : 30   3rd Qu.: 8.0                3rd Qu.:61.00  
##  6      : 30   Max.   :10.0                Max.   :85.00  
##  (Other):720</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A2
</div>
<div class="question-body">
<p>No modelling just yet.</p>
<p>Plot the performance over time for each type of task.</p>
<p>Try using <code>stat_summary</code> so that you are plotting the means (and standard errors) of each task, rather than every single data point. Why? Because this way you can get a shape of the overall trajectories of performance over time in each task.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-5&#39;, &#39;sol-start-5&#39;)"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(Az, aes(Time, Performance, color=Task, fill=Task)) + 
  stat_summary(fun.data=mean_se, geom=&quot;ribbon&quot;, color=NA, alpha=0.5) +
  stat_summary(fun=mean, geom=&quot;line&quot;)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-27-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A3
</div>
<div class="question-body">
<p>Why do you think <em>raw/natural</em> polynomials might be more useful than <em>orthogonal</em> polynomials for these data?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-6&#39;, &#39;sol-start-6&#39;)"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>Because we’re likely to be interested in whether there are task differences at the starting baseline point</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A4
</div>
<div class="question-body">
<p>Okay! Let’s do some modeling!</p>
<p>First steps:</p>
<ol style="list-style-type: decimal">
<li>Add 1st and 2nd order raw polynomials to the data using the <code>code_poly()</code> function.</li>
<li>Create a “baseline model”, in which performance varies over time (with both linear and quadratic change), but no differences in Task are estimated.</li>
</ol>
<p>We need to think about our random effect structure. We’ll talk you through this bit because it’s getting a bit more complicated now.</p>
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-7&#39;, &#39;opt-start-7&#39;)"> 1. What are the observations grouped by?</span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>We have multiple observations for each participant. We can see this easily if we plot performance over time, and make a separate facet for each subject:</p>
<pre class="r"><code>ggplot(Az, aes(x=Time,y=Performance))+
  geom_point()+
  facet_wrap(~Subject)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-28-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>We also have multiple observations for each task, and multiple observations for each time point (1 to 10). This is true, but importantly, these things (e.g. effects of time, differences between tasks) are things that we are specifically interested in estimating. The subjects, on the other hand, are simply a random sample of people in the study. We want to account for subject-level variation, but we’re not interested in estimating specific differences between specific subjects. This lends itself perfectly to being a grouping variable in a multi-level model.</p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-8" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-8&#39;, &#39;opt-start-8&#39;)"> 2. Are observations nested?</span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<p>There’s another grouping <em>within</em> each subjects’ data, and that is the task they are measured on:</p>
<pre class="r"><code>ggplot(Az, aes(x=Time,y=Performance,col=Task))+
  geom_point()+
  facet_wrap(~Subject)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-29-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-9&#39;, &#39;opt-start-9&#39;)"> 3. What effects can vary by-groups?</span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>For a given subject, on a given task, we can see that there is “an effect of time”.
So we can conceivably think of the effect of time on performance as varying by subject and tasks within subjects.</p>
<pre class="r"><code>Az %&gt;% filter(Subject == 4) %&gt;%
ggplot(., aes(x=Time,y=Performance,col=Task))+
  geom_point()+
  facet_wrap(~Task)+
  ylim(0,80)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-30-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-10" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-10&#39;, &#39;opt-start-10&#39;)"> 4. What should our random effect structure be?</span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p>So we know that we want to account for subject-level variation, and we also know that within each subjects’ data there are different tasks.<br />
Previously we have just been modelling one-level of grouping. This would be something like <code>(1 + ... | Subject)</code>.</p>
<p>We can extend this to model variation by-tasks-within-subjects, by using <code>(1 + ... | Subject/Task)</code>. This can also be written as: <code>(1 + ... | Subject) + (1 + ... | Subject:Task)</code> (which allows us to include different predictors as random effects in each grouping).</p>
<ul>
<li><code>(1 | Subject/Task)</code> = Allow subjects to vary in their intercepts, and within each subject, allow the tasks to vary in their intercepts.</li>
</ul>
<p>We also know that the trajectories of performance over time could be different for each subject, and it could also be different for each task for each subject.
So we can allow our effects that encode time (<code>poly1</code>, <code>poly2</code>) to vary by-subject/task:</p>
<ul>
<li><code>(1 + poly1 + poly2 | Subject/Task)</code> = Allow subjects to vary in their intercepts and trajectories over time, and within each subject, allow the tasks to vary in their intercepts and trajectories over time.</li>
</ul>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-11&#39;, &#39;sol-start-11&#39;)"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<pre class="r"><code># prep for analysis
Az &lt;- code_poly(Az, predictor=&quot;Time&quot;, poly.order=2, orthogonal=F, draw.poly = F)

# fit the base model
m.base &lt;- lmer(Performance ~ (poly1 + poly2) + 
                 (poly1 + poly2 | Subject/Task),
               data=Az, REML=F, control=lmerControl(optimizer=&quot;bobyqa&quot;))
summary(m.base)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: Performance ~ (poly1 + poly2) + (poly1 + poly2 | Subject/Task)
##    Data: Az
## Control: lmerControl(optimizer = &quot;bobyqa&quot;)
## 
##      AIC      BIC   logLik deviance df.resid 
##   3804.6   3881.5  -1886.3   3772.6      884 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.46383 -0.54482 -0.03605  0.54813  3.09190 
## 
## Random effects:
##  Groups       Name        Variance  Std.Dev. Corr       
##  Task:Subject (Intercept) 8.818e+00 2.969555            
##               poly1       6.344e+00 2.518659 -0.17      
##               poly2       2.923e-02 0.170954  0.09 -0.87
##  Subject      (Intercept) 1.578e+01 3.972260            
##               poly1       2.027e+00 1.423719 -0.57      
##               poly2       3.150e-06 0.001775  0.93 -0.83
##  Residual                 1.040e+00 1.019576            
## Number of obs: 900, groups:  Task:Subject, 90; Subject, 30
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept) 67.60667    0.79995  84.514
## poly1       -4.15943    0.37528 -11.083
## poly2        0.11801    0.01862   6.338
## 
## Correlation of Fixed Effects:
##       (Intr) poly1 
## poly1 -0.424       
## poly2  0.082 -0.639
## optimizer (bobyqa) convergence code: 0 (OK)
## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A5
</div>
<div class="question-body">
<p>Hopefully, you fitted a model like this (or thereabouts)</p>
<pre class="r"><code>m.base &lt;- lmer(Performance ~ (poly1 + poly2) + 
                 (1 + poly1 + poly2 | Subject/Task),
               data=Az, REML=F, control=lmerControl(optimizer=&quot;bobyqa&quot;))</code></pre>
<p>Remember what we learned last week about “singular fits”? It looks like this model might be a too complex for the data to sustain.</p>
<p>What random effect term might we consider removing? (there isn’t necessarily a “right” answer here - many may be defensible, but your decision should be based on multiple considerations/evidence).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-12&#39;, &#39;sol-start-12&#39;)"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<p>I would be inclined to remove the <code>poly2</code> term from either subjects, or tasks within subjects. I probably wouldn’t try removing it from both straight away, so we’ll need to split the random effect terms from <code>(1 + poly1 + poly2| Subject/Task)</code> to <code>(1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)</code>.</p>
<ul>
<li>Removing <code>poly2 | Subject:Task</code> will mean that within each subject, the linear trend will still vary by task, but quadratic trend will not. For a given subject, the model will think that the performance might go up on some tasks and down on others, but the curvature will be the same.<br />
</li>
<li>Removing <code>poly2 | Subject</code> will mean that the linear trend will still vary by subjects, but the quadratic trend will not. The model will assume all Subjects have the same curvature to their trajectories.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="03_nonlin_files/figure-html/unnamed-chunk-33-1.png" alt="Model fits for 6 subjects when excluding different random effect terms" width="100%" />
<p class="caption">
Figure 3: Model fits for 6 subjects when excluding different random effect terms
</p>
</div>
<p>Personally I’m more tempted to remove <code>poly2 | Subject</code>, in part because there is far less estimated variance in this term (see below):</p>
<pre class="r"><code># show the random effects
VarCorr(m.base)</code></pre>
<pre><code>##  Groups       Name        Std.Dev.  Corr         
##  Task:Subject (Intercept) 2.9695550              
##               poly1       2.5186594 -0.171       
##               poly2       0.1709543  0.092 -0.868
##  Subject      (Intercept) 3.9722599              
##               poly1       1.4237191 -0.568       
##               poly2       0.0017747  0.929 -0.832
##  Residual                 1.0195756</code></pre>
<pre class="r"><code>m.base &lt;- lmer(Performance ~ (poly1 + poly2) + 
                 (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task),
               data=Az, REML=F, control=lmerControl(optimizer=&quot;bobyqa&quot;))
summary(m.base)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: Performance ~ (poly1 + poly2) + (1 + poly1 | Subject) + (1 +  
##     poly1 + poly2 | Subject:Task)
##    Data: Az
## Control: lmerControl(optimizer = &quot;bobyqa&quot;)
## 
##      AIC      BIC   logLik deviance df.resid 
##   3798.6   3861.1  -1886.3   3772.6      887 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.46438 -0.54563 -0.03641  0.54710  3.09162 
## 
## Random effects:
##  Groups       Name        Variance Std.Dev. Corr       
##  Subject:Task (Intercept)  8.81922 2.970               
##               poly1        6.34519 2.519    -0.17      
##               poly2        0.02923 0.171     0.09 -0.87
##  Subject      (Intercept) 15.74116 3.968               
##               poly1        1.97414 1.405    -0.56      
##  Residual                  1.03953 1.020               
## Number of obs: 900, groups:  Subject:Task, 90; Subject, 30
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept) 67.60667    0.79917  84.596
## poly1       -4.15943    0.37295 -11.153
## poly2        0.11801    0.01862   6.339
## 
## Correlation of Fixed Effects:
##       (Intr) poly1 
## poly1 -0.418       
## poly2  0.067 -0.633</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A6
</div>
<div class="question-body">
<p>Let’s start adding in our effects of interest.</p>
<ol style="list-style-type: decimal">
<li>Create a new model with a fixed effect of Task</li>
<li>Create a new model in which performance varies linearly over time between Task type.</li>
<li>Create a new model in which linear <em>and</em> quadratic performance over time varies between Task type.</li>
<li>Run model comparisons.</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-13" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-13&#39;, &#39;sol-start-13&#39;)"> Solution </span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<pre class="r"><code>m.0 &lt;- lmer(Performance ~ (poly1 + poly2) + Task +
              (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task),
            data=Az, REML=F, control=lmerControl(optimizer=&quot;bobyqa&quot;))
m.1 &lt;- lmer(Performance ~ poly1*Task + poly2 +
              (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task),
            data=Az, REML=F, control=lmerControl(optimizer=&quot;bobyqa&quot;))
m.Az.full &lt;- lmer(Performance ~ (poly1 + poly2)*Task + 
                  (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task),
                data=Az, REML=F, control=lmerControl(optimizer=&quot;bobyqa&quot;))
anova(m.base, m.0, m.1, m.Az.full)</code></pre>
<pre><code>## Data: Az
## Models:
## m.base: Performance ~ (poly1 + poly2) + (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)
## m.0: Performance ~ (poly1 + poly2) + Task + (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)
## m.1: Performance ~ poly1 * Task + poly2 + (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)
## m.Az.full: Performance ~ (poly1 + poly2) * Task + (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task)
##           npar    AIC    BIC  logLik deviance    Chisq Df Pr(&gt;Chisq)    
## m.base      13 3798.6 3861.1 -1886.3   3772.6                           
## m.0         15 3801.8 3873.8 -1885.9   3771.8   0.8559  2     0.6518    
## m.1         17 3775.4 3857.0 -1870.7   3741.4  30.4129  2  2.488e-07 ***
## m.Az.full   19 3607.8 3699.1 -1784.9   3569.8 171.5323  2  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<p class="solution-end">
</p>
<div class="frame">
<p>We’d like to do some inferential tests of our coefficients values. We could consider computing some confidence intervals with <code>confint(m.Az.full, method="boot")</code>, but this may take quite a long time with such a complex model (if we bootstrap, we’re essentially fitting thousands of models!).</p>
<p>For now, let’s refit the full model and obtain p-values for our coefficients by using the Satterthwaite approximations for the denominator degrees of freedom.<br />
The code below does this for us</p>
<div class="rtip">
<p>By using <code>lmerTest::lmer()</code> we don’t have to load the package <code>library(lmerTest)</code>, and so it is just this single model that’s get fitted this way.</p>
</div>
<pre class="r"><code>m.full_satter &lt;- 
    lmerTest::lmer(Performance ~ (poly1 + poly2) * Task +
                       (1 + poly1 | Subject) + (1 + poly1 + poly2 | Subject:Task),
                   data=Az, REML=F, control=lmerControl(optimizer=&quot;bobyqa&quot;))

tidy(m.full_satter) %&gt;% 
    filter(effect==&quot;fixed&quot;)</code></pre>
<pre><code>## # A tibble: 9 × 8
##   effect group term             estimate std.error statistic    df  p.value
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1 fixed  &lt;NA&gt;  (Intercept)      67.2        0.927     72.5    51.1 3.66e-53
## 2 fixed  &lt;NA&gt;  poly1            -3.29       0.335     -9.80   48.9 3.94e-13
## 3 fixed  &lt;NA&gt;  poly2             0.00947    0.0124     0.762  90.0 4.48e- 1
## 4 fixed  &lt;NA&gt;  TasksADL          0.0950     0.812      0.117  60.0 9.07e- 1
## 5 fixed  &lt;NA&gt;  TaskMemory        1.24       0.812      1.53   60.0 1.32e- 1
## 6 fixed  &lt;NA&gt;  poly1:TasksADL    1.36       0.270      5.05   60.1 4.47e- 6
## 7 fixed  &lt;NA&gt;  poly1:TaskMemory -3.98       0.270    -14.7    60.1 1.32e-21
## 8 fixed  &lt;NA&gt;  poly2:TasksADL   -0.0133     0.0176    -0.754  90.0 4.53e- 1
## 9 fixed  &lt;NA&gt;  poly2:TaskMemory  0.339      0.0176    19.3    90.0 1.07e-33</code></pre>
<div class="optional-begin">
<span id="opt-start-14" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-14&#39;, &#39;opt-start-14&#39;)"> Optional: Quick refresher of scientific notation</span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<p>5.4e-3 = 0.0054<br />
5.4e-2 = 0.054<br />
5.4e-1 = 0.54<br />
5.4e-0 = 5.4<br />
5.4e+1 = 54<br />
5.4e+2 = 540</p>
</div>
<p class="optional-end">
</p>
</div>
<div class="question-begin">
Question A7
</div>
<div class="question-body">
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
67.16
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
72.48
</td>
<td style="text-align:right;">
51.06
</td>
<td style="text-align:left;">
&lt;.001 ***
</td>
</tr>
<tr>
<td style="text-align:left;">
poly1
</td>
<td style="text-align:right;">
-3.29
</td>
<td style="text-align:right;">
0.34
</td>
<td style="text-align:right;">
-9.80
</td>
<td style="text-align:right;">
48.95
</td>
<td style="text-align:left;">
&lt;.001 ***
</td>
</tr>
<tr>
<td style="text-align:left;">
poly2
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
90.00
</td>
<td style="text-align:left;">
.448
</td>
</tr>
<tr>
<td style="text-align:left;">
TasksADL
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
0.81
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
60.05
</td>
<td style="text-align:left;">
.907
</td>
</tr>
<tr>
<td style="text-align:left;">
TaskMemory
</td>
<td style="text-align:right;">
1.24
</td>
<td style="text-align:right;">
0.81
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
60.05
</td>
<td style="text-align:left;">
.132
</td>
</tr>
<tr>
<td style="text-align:left;">
poly1:TasksADL
</td>
<td style="text-align:right;">
1.36
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
5.04
</td>
<td style="text-align:right;">
60.08
</td>
<td style="text-align:left;">
&lt;.001 ***
</td>
</tr>
<tr>
<td style="text-align:left;">
poly1:TaskMemory
</td>
<td style="text-align:right;">
-3.98
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
-14.73
</td>
<td style="text-align:right;">
60.08
</td>
<td style="text-align:left;">
&lt;.001 ***
</td>
</tr>
<tr>
<td style="text-align:left;">
poly2:TasksADL
</td>
<td style="text-align:right;">
-0.01
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
-0.75
</td>
<td style="text-align:right;">
90.00
</td>
<td style="text-align:left;">
.453
</td>
</tr>
<tr>
<td style="text-align:left;">
poly2:TaskMemory
</td>
<td style="text-align:right;">
0.34
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
19.27
</td>
<td style="text-align:right;">
90.00
</td>
<td style="text-align:left;">
&lt;.001 ***
</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li>For the cADL Task, what is the estimated average performance where x = 0?<br />
</li>
<li>For the sADL and Memory Tasks, is the estimated average where x = 0 different to the cADL Task?</li>
<li>For the cADL Task, how does performance change for every increasing time point? (what is the estimated linear slope?)
<ul>
<li>Note, the quadratic term <code>poly2</code> is non-significant, so we’ll ignore it here<br />
</li>
</ul></li>
<li>For the sADL Task, how is the change in performance over time different from the cADL Task?</li>
<li>The answer to c) + the answer to d) will give you the estimated slope for the sADL Task.</li>
<li>For the Memory Task, how is the change in performance over time different from the cADL Task?
<ul>
<li>This is more difficult. The quadratic term is significant.</li>
<li>Recall the direction of the quadratic term (positive/negative) and how this relates to the visual curvature (see back in <a href="#whats-a-polynomial">“What’s a polynomial?”</a>).</li>
</ul></li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-15" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-15&#39;, &#39;sol-start-15&#39;)"> Solution </span>
</div>
<div id="sol-body-15" class="solution-body" style="display: none;">
<ol style="list-style-type: lower-alpha">
<li>For the cADL Task, what is the estimated average performance where x = 0?
<ul>
<li><strong>67.16</strong></li>
</ul></li>
<li>For the sADL and Memory Tasks, is the estimated average where x = 0 different to the cADL Task?
<ul>
<li><strong>No. Neither of the intercept differences are significant.</strong><br />
</li>
</ul></li>
<li>For the cADL Task, how does performance change for every increasing time point? (what is the estimated linear slope?)
<ul>
<li><strong>Note, the quadratic term <code>poly2</code> is non-significant, so we’ll ignore it here</strong><br />
</li>
<li><strong>For every increase in one timepoint, cADL performance changes by -3.29.</strong></li>
</ul></li>
<li>For the sADL Task, how is the change in performance over time different from the cADL Task?
<ul>
<li><strong>For every increase in one timepoint sADL performance change is 1.36 different from change in cADL</strong></li>
</ul></li>
<li>The answer to c) + the answer to d) will give you the estimated slope for the sADL Task.
<ul>
<li><strong>-3.29 + 1.36 = -1.927803</strong></li>
<li><strong>For every increase in one timepoint, sADL performance changes by -1.93</strong></li>
</ul></li>
<li>For the Memory Task, how is the change in performance over time different from the cADL Task?
<ul>
<li><strong>Memory performance declines even more steeply than cADL, with linear change of -3.29 + -3.98 = -7.267803, but it also has a quadratic effect of 0.34. This is positive, which means it is <span class="math inline">\(\cup\)</span>-shaped (rather than <span class="math inline">\(\cap\)</span>-shaped).</strong>_</li>
</ul></li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A8
</div>
<div class="question-body">
<p>Based on your answers above, can you sketch out (on paper) the model fit?</p>
<p>Then provide a written description.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-16" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-16&#39;, &#39;sol-start-16&#39;)"> Solution </span>
</div>
<div class="solution-body" id = "sol-body-16" style="display: none;">



<div class="int">
<p>Performance in all tasks starts out the same [thanks, natural polynomials!]. Linear change over time is different depending on task type: compared to complex ADL tasks, decline in simple ADL tasks is slower and decline in Memory is faster. Decline in cADL and sADL tasks is approximately linear, whereas decline in Memory has more curvature (reaching floor?)</p>
</div>
<center>
<video width="480" height="360" controls>
<source src="images/msmrcogsketch.mp4" type="video/mp4">
</video>
</center>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A9
</div>
<div class="question-body">
<p>To what extent do model comparisons (Question A6) and the parameter-specific p-values (Question A7) yield the same results?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-17" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-17&#39;, &#39;sol-start-17&#39;)"> Solution </span>
</div>
<div id="sol-body-17" class="solution-body" style="display: none;">
<p>Model comparisons suggest:</p>
<ul>
<li>Linear slopes are different: <span class="math inline">\(\chi^2(2)=30.41, p &lt; .001\)</span> (comparison <code>m.0</code> and <code>m.1</code> above).<br />
</li>
<li>Quadratic term is different: <span class="math inline">\(\chi^2(2)=171.53, p &lt; .001\)</span> (comparison <code>m.1</code> and <code>m.Az.full</code> above).</li>
</ul>
<p><em>Note:</em> We can’t investigate the intercept difference via the model comparisons above. Comparison between <code>m.base</code> and <code>m.0</code> indicates difference holding polynomial terms constant (not the conditional effect where poly1 and poly2 are 0).</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A10
</div>
<div class="question-body">
<p>Plot the model fitted values. This might be pretty similar to the plot you created in Question A2, and (hopefully) similar to the one you drew on paper for Question A8.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-18" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-18&#39;, &#39;sol-start-18&#39;)"> Solution </span>
</div>
<div id="sol-body-18" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(Az, aes(Time, Performance, color=Task)) + 
  stat_summary(fun.data=mean_se, geom=&quot;pointrange&quot;) + 
  stat_summary(fun=mean, geom=&quot;line&quot;, aes(y=fitted(m.Az.full)))</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-39-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="frame">
<p>Two quotes</p>
<p>“all models are wrong. some are useful.” <a href="https://www.tandfonline.com/doi/abs/10.1080/01621459.1976.10480949">(George Box, 1976)</a>.</p>
<p>“…it does not seem helpful just to say that all models are wrong. The very word model implies simplification and idealization. The idea that complex physical, biological or sociological systems can be exactly described by a few formulae is patently absurd. The construction of idealized representations that capture important stable aspects of such systems is, however, a vital part of general scientific analysis and statistical models, especially substantive ones, do not seem essentially different from other kinds of model.”<a href="https://twitter.com/richarddmorey/status/1111270300241588225">(Sir David Cox, 1995)</a>.</p>
</div>
<div class="optional-begin">
<span id="opt-start-19" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-19&#39;, &#39;opt-start-19&#39;)"> Optional: TIMTOWTDI</span>
</div>
<div id="opt-body-19" class="optional-body" style="display: none;">
<p><strong>TIMTOWTDI</strong> <em>(There is more than one way to do it)</em></p>
<p>The approach we are learning about in this course is only one of many approaches to studying non-linearity.
Some alternatives, which you may come across in future work, are listed below.</p>
<p><strong>Piecewise linear regression:</strong> fit a linear model with cut point(s) along x (determine cut points by greatest reduction in mean squared error <span class="math inline">\(\sigma\)</span>)
<img src="03_nonlin_files/figure-html/unnamed-chunk-40-1.png" width="350px" style="display: block; margin: auto;" /></p>
<p><strong>Piecewise polynomial</strong> fit the model <span class="math inline">\(y \sim x + x^2 + x^3\)</span> to equal chunks of x.</p>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-41-1.png" width="350px" style="display: block; margin: auto;" /></p>
<p><strong>Splines, penalised splines &amp; GAMS</strong></p>
<p>This begins to open a huge can of worms, but if you foresee yourself needing these sort of tools, then Simon Wood, author of the <strong>mgcv</strong> R package for fitting generalised additive models (GAMS), is now in the maths department at Edinburgh. He has plenty of materials on <a href="https://www.maths.ed.ac.uk/~swood34/talks/snw-Koln.pdf">his webpage</a> (Warning, these are fairly technical). There are also a reasonable number of tutorials <a href="https://www.google.com/search?hl=&amp;site=&amp;q=gam+in+r+tutorial">online which are really good</a>.<br />
<img src="03_nonlin_files/figure-html/unnamed-chunk-42-1.png" width="350px" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
