{
  "hash": "b55e6bf5b708035cffe99cbed01b81d5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 8 Exercises: CFA\"\nparams: \n    SHOW_SOLS: FALSE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n:::frame\n__New packages__  \n\nMake sure you have these packages installed:  \n\n+ lavaan\n+ semPlot\n\n:::\n\n\n# Exercises for the Enthusiastic\n\n:::frame\n__Dataset: radakovic_das.csv__  \n\nApathy is lack of motivation towards goal-directed behaviours. It is pervasive in a majority of psychiatric and neurological diseases, and impacts everyday life. Traditionally, apathy has been measured as a one-dimensional construct but is in fact composed of different types of demotivation.\n\n**The Dimensional Apathy Scale (DAS)** is a multidimensional assessment for demotivation, in which 3 subtypes of apathy are assessed:  \n\n- **Executive:** lack of motivation for planning, attention or organisation\n- **Emotional:** lack of emotional motivation (indifference, affective or emotional neutrality, flatness or blunting)\n- **Initiation:** lack of motivation for self-generation of thoughts and/or actions\n\nThe DAS measures these subtypes of apathy and allows for quick and easy assessment, through self-assessment, observations by informants/carers or administration by researchers or healthcare professionals.  \n\nYou can find data for the DAS when administered to 250 healthy adults at [https://uoepsy.github.io/data/radakovic_das.csv](https://uoepsy.github.io/data/radakovic_das.csv){target=\"_blank\"}, and information on the items is below.  \n\n::: {.callout-note collapse=\"true\"}\n#### DAS Dictionary\n\nAll items are measured on a 6-point Likert scale of Always (0), Almost Always (1), Often (2), Occasionally (3), Hardly Ever (4), and Never (5). Certain items (indicated in the table below with a `-` direction) are reverse scored to ensure that higher scores indicate greater levels of apathy. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"olxkrwvmht\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#olxkrwvmht table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#olxkrwvmht thead, #olxkrwvmht tbody, #olxkrwvmht tfoot, #olxkrwvmht tr, #olxkrwvmht td, #olxkrwvmht th {\n  border-style: none;\n}\n\n#olxkrwvmht p {\n  margin: 0;\n  padding: 0;\n}\n\n#olxkrwvmht .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#olxkrwvmht .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#olxkrwvmht .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#olxkrwvmht .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#olxkrwvmht .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#olxkrwvmht .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#olxkrwvmht .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#olxkrwvmht .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#olxkrwvmht .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#olxkrwvmht .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#olxkrwvmht .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#olxkrwvmht .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#olxkrwvmht .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#olxkrwvmht .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#olxkrwvmht .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olxkrwvmht .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#olxkrwvmht .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#olxkrwvmht .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#olxkrwvmht .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olxkrwvmht .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#olxkrwvmht .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olxkrwvmht .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#olxkrwvmht .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olxkrwvmht .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#olxkrwvmht .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olxkrwvmht .gt_left {\n  text-align: left;\n}\n\n#olxkrwvmht .gt_center {\n  text-align: center;\n}\n\n#olxkrwvmht .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#olxkrwvmht .gt_font_normal {\n  font-weight: normal;\n}\n\n#olxkrwvmht .gt_font_bold {\n  font-weight: bold;\n}\n\n#olxkrwvmht .gt_font_italic {\n  font-style: italic;\n}\n\n#olxkrwvmht .gt_super {\n  font-size: 65%;\n}\n\n#olxkrwvmht .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#olxkrwvmht .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#olxkrwvmht .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#olxkrwvmht .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#olxkrwvmht .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#olxkrwvmht .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#olxkrwvmht .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#olxkrwvmht .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#olxkrwvmht div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"item\">item</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"direction\">direction</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dimension\">dimension</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"question\">question</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">1</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I need a bit of encouragement to get things started</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">2</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I contact my friends</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">3</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I express my emotions</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">4</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I think of new things to do during the day</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">5</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I am concerned about how my family feel</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">6</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I find myself staring in to space</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">7</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">Before I do something I think about how others would feel about it</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">8</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I plan my days activities in advance</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">9</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">When I receive bad news I feel bad about it</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">10</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I am unable to focus on a task until it is finished</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">11</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I lack motivation</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">12</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I struggle to empathise with other people</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">13</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I set goals for myself</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">14</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I try new things</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">15</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I am unconcerned about how others feel about my behaviour</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">16</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I act on things I have thought about during the day</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">17</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">When doing a demanding task, I have difficulty working out what I have to do</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">18</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I keep myself busy</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">19</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I get easily confused when doing several things at once</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">20</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I become emotional easily when watching something happy or sad on TV</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">21</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I find it difficult to keep my mind on things</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">22</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">-</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Initiation</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I am spontaneous</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">23</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Executive</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I am easily distracted</td></tr>\n    <tr><td headers=\"item\" class=\"gt_row gt_right\">24</td>\n<td headers=\"direction\" class=\"gt_row gt_right\">+</td>\n<td headers=\"dimension\" class=\"gt_row gt_left\">Emotional</td>\n<td headers=\"question\" class=\"gt_row gt_left\">I feel indifferent to what is going on around me</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nHere are the item numbers that correspond to each dimension.\n\n- Executive: 1, 6, 10, 11, 17, 19, 21, 23\n- Emotional: 3, 5, 7, 9, 12, 15, 20, 24\n- Initiation: 2, 4, 8, 13, 14, 16, 18, 22\n\n:::\n\n:::\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nRead in the data. \nIt will need a little bit of tidying before we can get to fitting a CFA.  \n\nRemember that most of the actions needed for working with those sort of data are described in the [Chapter on Data Wrangling for Questionnaires](https://uoepsy.github.io/lv/00_datawrangle.html){target=\"_blank\"}.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nBy the looks of things, this is what I would consider doing:\n\n- Rename the variables to easy-to-read strings like `q1`, `q2`, `q3`, etc.\n- Set up a data dictionary that records the text of the item `q1` corresponds to, the text that `q2` corresponds to, etc.\n- Recode the Likert scale labels to numbers.\n- Reverse-code the questions with a negative direction. Note, you don't **need** to this, as they'll just end up with loadings in the opposite direction, but I would strongly recommend it for interpretation purposes.  \n- Check if there is missing data and if there is, removing those observations.\n\n\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  1 - Read and check</button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\nFirst let's just read in the dataset:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lavaan)\nlibrary(semPlot)\n\nrdas <- read_csv(\"https://uoepsy.github.io/data/radakovic_das.csv\")\nhead(rdas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 24\n  I need a bit of encouragement …¹ `I contact my friends` I express my emotion…²\n  <chr>                            <chr>                  <chr>                 \n1 Often                            Almost Always          Almost Always         \n2 Almost Always                    Hardly Ever            Occasionally          \n3 Often                            Occasionally           Occasionally          \n4 Hardly Ever                      Occasionally           Almost Always         \n5 Occasionally                     Hardly Ever            Occasionally          \n6 Occasionally                     Occasionally           Almost Always         \n# ℹ abbreviated names: ¹​`I need a bit of encouragement to get things started`,\n#   ²​`I express my emotions`\n# ℹ 21 more variables: `I think of new things to do during the day` <chr>,\n#   `I am concerned about how my family feel` <chr>,\n#   `I find myself staring in to space` <chr>,\n#   `Before I do something I think about how others would feel about it` <chr>,\n#   `I plan my days activities in advance` <chr>, …\n```\n\n\n:::\n:::\n\n\n\n\nThe names we're getting are useful in that they show the items, but they're horrible to have to use in R, so we will ideally replace them with easy to use names. \nNote also that the data is being read in as the actual response option - e.g., \"Almost Always\" - and we want to treat these as a numeric scale. So those will have to change too.  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  2 - Renaming variables</button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\nI like to make a \"data dictionary\" whenever I get data like this. While I want to rename the variables to make it easier for me to use, I also want to keep track of what the questions were.  \nHere I make a \"tibble\" (the function `data.frame()` would work too, tibble is just tidyverse version). I indicate what I am going to rename things as (\"q1\",\"q2\", ..., \"q24\"), and then I have the current names of the variables\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrdas_dict <- tibble(\n  variable = paste0(\"q\",1:24),\n  item = names(rdas)\n)\n```\n:::\n\n\n\n\nDoing this is really useful because I can't keep track in my head of what \"q5\" was.  \nIf I want to know, then I can just do: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrdas_dict[5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  variable item                                   \n  <chr>    <chr>                                  \n1 q5       I am concerned about how my family feel\n```\n\n\n:::\n:::\n\n\n\n\nNow let's actually change the names in our data to what we said we would:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnames(rdas) <- paste0(\"q\", 1:24)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  3 - Recoding responses</button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\nOkay, so we have all our data in words, not numbers. Views on how to treat Likert data are mixed, but it's very common to treat it as continuous in Psychology.  \n\nLet's check the response values we have. Just in question 1 for now:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nunique(rdas$q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Often\"         \"Almost Always\" \"Hardly Ever\"   \"Occasionally\" \n[5] \"Always\"        NA              \"Never\"        \n```\n\n\n:::\n:::\n\n\n\n\nA little trick that we can use to find the unique values in an entire dataset is to quickly convert the dataframe into one big long vector. Technically, a dataframe is a \"list of vectors\", and the function `unlist()` will remove this structure.  \nSo we can find all the unique values in all the questions with:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nunique(unlist(rdas))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Often\"         \"Almost Always\" \"Hardly Ever\"   \"Occasionally\" \n[5] \"Always\"        NA              \"Never\"         \"[NO ENTRY]\"   \n```\n\n\n:::\n:::\n\n\n\n\nPerfect. So we know we have uniformity of spelling. It happens less often these days as questionnaire software is improving, but you might occasionally encounter typos in _some_ of the questions, or things with and without capital letters (R is a bit thick, and doesn't recognise that \"Often\" and \"often\" are the same thing).  \nNote that we have the 6 responses that we would expect given the description of the scale, but we also have some `NA` values, and some `[NO ENTRY]` values. Not sure how those got there.  \nWe want to turn each \"Always\" in to 0, each \"Almost Always\" in to 1, \"Often\" in to 2, and so on. If we simply leave out the \"[NO ENTRY]\", then this will be turned into a missing value `NA`, which is handy.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrdas <- rdas |> \n  mutate(across(q1:q24, ~case_match(.,\n    \"Always\" ~ 0,\n    \"Almost Always\" ~ 1,\n    \"Often\" ~ 2,\n    \"Occasionally\" ~ 3,\n    \"Hardly Ever\" ~ 4,\n    \"Never\" ~ 5\n  )))\nhead(rdas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 24\n     q1    q2    q3    q4    q5    q6    q7    q8    q9   q10   q11   q12   q13\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1     2     1     1     4     1     3     1     4     2     2     3     2     3\n2     1     4     3     4    NA     0    NA     2    NA     2     1     2     3\n3     2     3     3     4     3     3     2     2     4     1     3     2     3\n4     4     3     1     3     1    NA     2     2    NA     2     3     4     2\n5     3     4     3     5     2     2     2     3     3     2     2     2     1\n6     3     3     1     0     1     2     1     1     0     2     1     4     3\n# ℹ 11 more variables: q14 <dbl>, q15 <dbl>, q16 <dbl>, q17 <dbl>, q18 <dbl>,\n#   q19 <dbl>, q20 <dbl>, q21 <dbl>, q22 <dbl>, q23 <dbl>, q24 <dbl>\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  4 - Reverse Coding</button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\nAccording to the table of items, the ones which need to be reverse scored are:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreversed <- c(2,3,4,5,7,8,9,10,13,14,16,18,20,22)\n```\n:::\n\n\n\n\nFor these items, we want 5s to become 0s, 4s become 1s, and so on. \n\nThe tidyverse solution shown in the readings and solutions to previous labs will work just fine, but if you're curious, here's a different way to accomplish the same thing using functions from base R:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrdas[, reversed] <- apply(\n  rdas[, reversed], MARGIN = 2, function(x) 5-x)\n```\n:::\n\n\n\n\n__Note:__ The above code works nicely because our dataset is currently ordered such that the first column is item 1, 2nd column is item 2, and so on. This means we can use _numbers_ to index the appropriate variables, rather than _names_. It would need adjusting if, for instance, our first column contained \"participant ID\", and our items only began later.  \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  5 - Removing missingness</button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\nWe haven't learned about more sophisticated methods of handling missing data, so for now we will just remove any rows in which there is missingness - i.e., we'll do \"listwise deletion\":  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncompl_rdas <- na.omit(rdas)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nSpecify the theoretical model proposed by Radakovic et al.   \n\nFor reference, check out [the example in the readings](https://uoepsy.github.io/lv/04_cfa.html#cfa-in-r---the-lavaan-package).\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndasmod <- \"\n\n\n\n\n\n\"\n```\n:::\n\n\n\n\nChallenge: Before you estimate the model, how many degrees of freedom do you think the model will have?\n([The readings](https://uoepsy.github.io/lv/04_cfa.html#degrees-of-freedom) will help here!)\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nYou'll have to use the data dictionary to see which items are associated with which dimensions. \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nHere is the model structure, according to the list of items in the dictionary.  \nI'm calling my factors \"Em\", \"Ex\", and \"BCI\" for \"emotional\", \"executive\" and \"behavioural/cognitive initiation\" respectively. The factor correlations will be estimated by default, but I like to write things explicitly. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndasmod = \"\nEx =~ q1 + q6 + q10 + q11 + q17 + q19 + q21 + q23\nEm =~ q3 + q5 + q7 + q9 + q12 + q15 + q20 + q24\nBCI =~ q2 + q4 + q8 + q13 + q14 + q16 + q18 + q22\nEm ~~ Ex\nEm ~~ BCI\nEx ~~ BCI\n\"\n```\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nDegrees of freedom is computed as the number of \"knowns\" minus the number of \"unknowns\".\n\nLet's start with figuring out the number of \"knowns\": the number of values in the dataset.\nThis number comes from the observed covariance matrix.\nLet's imagine a smaller dataset with only five items.\nIt'll create a covariance matrix like this:\n\n```\nvar\ncovar   var\ncovar   covar   var\ncovar   covar   covar   var\ncovar   covar   covar   covar   var\n```\n\n\nHow many values are in this matrix?\nIn the first row, there's 1, plus the second row with 2, plus the third row with 3, plus the fourth row with 4, plus the fifth row with 5.\nIn other words, there are\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n:::\n\n\n\n\nvalues in this covariance matrix.  \n\nFor the present scenario with 24 items, we will have\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum(1:24)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 300\n```\n\n\n:::\n:::\n\n\n\n\nvalues in the covariance matrix.\n(Twenty-four of these will be each item's own variance, and the other 276 will be covariances between items.)  \n\nThe alternative formula to calculate this is $\\frac{k \\cdot (k+1)}{2}$, and we get the same number by plugging in the number of variables for $k$: $\\frac{24 \\cdot (24+1)}{2} = \\frac{600}{2} = 300$\n\nNow let's look at the number of \"unknowns\": the number of parameters the model has to estimate.\nThis number comes from the number of latent variables and how they relate to each item.\n\n- Each latent variable has its own variance, and there are three latent variables, so the model will have three latent factor variances.\n- Each item will load onto one latent variable, and there are 24 items, so the model will have 24 factor loadings.\n- Each item will have residual factor variances, and there are 24 items, so the model will have 24 residual factor variances.\n\nAdding these up, we get\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n3 + 24 + 24\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 51\n```\n\n\n:::\n:::\n\n\n\n\nunknown parameters.\n\nFinally, let's subtract the knowns from the unknowns to get the degrees of freedom:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n300 - 51\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 249\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nEstimate the model using `cfa()`.  \nYou can choose whether you want to standardise the latent factors or fix the first loading of each factor to be 1 (it's the same model, just scaled differently).  \n\nExamine the model fit - does it fit well?\n\nWhat modifications do the modification indices suggest? Are the top three suggestions theoretically reasonable, in your opinion?  \n\nRemember, we don't really _want_ to have to make modifications to our models. If you don't need to (if the model fits well) then don't bother! (It's still worth _looking_ at the modification indices though).  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nThere's a whole section on \"model fit\" in the [CFA chapter](https://uoepsy.github.io/lv/04_cfa.html#model-fit){target=\"_blank\"}!  \n\nAnd there's also a whole section on [model modifications](https://uoepsy.github.io/lv/04_cfa.html#model-modifications).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nLet's fit the model!  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndasmod.est = cfa(dasmod, compl_rdas)\n```\n:::\n\n\n\n\n\nThe standard test of model fit is a chi-squared test which compares the observed covariance matrix to the model-implied covariance matrix.\nIdeally, these two matrices will be fairly similar, so we want a non-significant result.\n\nWe can get the test statistic and p-value from the model's chi-squared test as follows:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(dasmod.est)$test$standard\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$test\n[1] \"standard\"\n\n$stat\n[1] 274.8334\n\n$stat.group\n[1] 274.8334\n\n$df\n[1] 249\n\n$refdistr\n[1] \"chisq\"\n\n$pvalue\n[1] 0.1251793\n```\n\n\n:::\n:::\n\n\n\n\nSo a chi-squared test with 249 degrees of freedom results in a test statistic of 274.8, associated with a p-value of 0.125.\nThe take-away is that our observed covariance matrix is not significantly different from the model-implied covariance matrix—yay!\n\nNext, let's check the additional measures of global fit: \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfitmeasures(dasmod.est)[c(\"srmr\",\"rmsea\",\"tli\",\"cfi\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      srmr      rmsea        tli        cfi \n0.05364507 0.02171599 0.96913532 0.97215469 \n```\n\n\n:::\n:::\n\n\n\n\nAll looks pretty good! Cut-offs for SRMR tend to vary, with some using <0.08, or <0.09, and some being stricter with <0.05. Remember, these criteria are somewhat arbitrary.  \n\nModification indices suggest a whole bunch of items that could have some associations beyond that modelled in the factors, but these are all weak correlations at around 0.2.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodindices(dasmod.est, sort=TRUE) |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lhs op rhs     mi    epc sepc.lv sepc.all sepc.nox\n132  q6 ~~  q3 15.896  0.222   0.222    0.284    0.284\n113  q1 ~~  q9 11.929 -0.172  -0.172   -0.267   -0.267\n216 q19 ~~ q20 10.887  0.168   0.168    0.256    0.256\n103  q1 ~~  q6  7.447  0.149   0.149    0.220    0.220\n358  q4 ~~  q8  7.417  0.199   0.199    0.207    0.207\n105  q1 ~~ q11  6.757 -0.149  -0.149   -0.237   -0.237\n```\n\n\n:::\n:::\n\n\n\n\nThese are the top 3 being suggested. I can't see any obvious link between any of these that would make me think they are related beyond their measuring of 'apathy'.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrdas_dict[c(3,6),]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  variable item                             \n  <chr>    <chr>                            \n1 q3       I express my emotions            \n2 q6       I find myself staring in to space\n```\n\n\n:::\n\n```{.r .cell-code}\nrdas_dict[c(1,9),]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  variable item                                               \n  <chr>    <chr>                                              \n1 q1       I need a bit of encouragement to get things started\n2 q9       When I receive bad news I feel bad about it        \n```\n\n\n:::\n\n```{.r .cell-code}\nrdas_dict[c(19,20),]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  variable item                                                                \n  <chr>    <chr>                                                               \n1 q19      I get easily confused when doing several things at once             \n2 q20      I become emotional easily when watching something happy or sad on TV\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nAre the (*standardised*) loadings all \"big enough\"?  \nThere's no clear threshold that people use here - it depends a lot on the field, and on the wordings of specific items. Ideally, the same value we used in EFA ($\\geq|0.3|$) would be nice, but not crucial.  \n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nTo get out standardised loadings, we can do:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod.est <- cfa(model_syntax, data = ...)\nsummary(mod.est, std=TRUE)\n```\n:::\n\n\n\n\nAnd you'll get out an extra 2 columns in the summary output.  \n\nPay attention to the `Estimate`, `Std.lv` and `Std.all` columns in your output. The way I think of these columns is just to think of how we scale things in regression models:  \n\n- `Estimate` column : `item ~ Factor`  \n- `Std.lv` column : `item ~ scale(Factor)`  \n- `Std.all` column: `scale(item) ~ scale(Factor)`  \n\nSo if, when we fitted the model, we had specified `cfa(model, data, std.lv = TRUE)`, then the factor _already has a variance of 1_, so `Scale(Factor)` doesn't do anything.  \n\nSee [Chapter 4#interpretation](https://uoepsy.github.io/lv/04_cfa.html#interpretation){target=\"_blank\"}.  \n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nI'm not going to print all of this right now because there's so much output, but here's how we would find standardised loadings. We can find them in the `Std.all` column.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(dasmod.est, std = TRUE)\n```\n:::\n\n\n\n```\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  Ex =~                                                                 \n    q1                1.000                               0.679    0.694\n    q6                0.679    0.121    5.607    0.000    0.461    0.433\n    ...\n    ...\n```\n\nThe standardised loadings are all (*just*) greater than $|0.3|$. Questions 13 and 15 are very close... \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrdas_dict[c(13,15),]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  variable item                                                     \n  <chr>    <chr>                                                    \n1 q13      I set goals for myself                                   \n2 q15      I am unconcerned about how others feel about my behaviour\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nDo the factors correlate in the way you would expect?  \n\nIs more emotional apathy associated with more executive apathy? and with more initiation apathy?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nIf you *didn't* reverse code the appropriate items, then this might get confusing, because we'd have to look at factor loadings to know in which direction the factor is going (i.e., are higher numbers \"more apathy\" or \"less apathy\"?).  \n\nIf you *did* reverse code the appropriate items, then you're golden, because you made them all point towards \"more\" apathy.   \n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\nHere are the correlations we're interested in. Note that what we are seeing is that the three factors are all positively correlated, but for `Em` and `Ex` this is only weak (and not significant).   \n\nThis isn't necessary a problem, it just means that these two factors are fairly distinct/orthogonal. We might want to check back in the original paper to see what they proposed! \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(dasmod.est, std = TRUE)\n```\n:::\n\n\n\n```\n...\nCovariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  Ex ~~                                                                 \n    Em                0.051    0.028    1.807    0.071    0.159    0.159\n  Em ~~                                                                 \n    BCI               0.043    0.018    2.369    0.018    0.263    0.263\n  Ex ~~                                                                 \n    BCI               0.151    0.040    3.746    0.000    0.642    0.642\n```\n\n\n<!-- If we look at the loadings for the Executive apathy factor, they are all positive other than `q10`. According to our data dictionary, this `q10` is negatively worded, and the others are all positively worded. So being higher on the `Ex` factor means more Executive Apathy, which is what we want.   -->\n\n<!-- By contrast, both `Em` and `BCI` have positive loadings for the questions that are negatively worded according to the data dictionary. Note that **all** of the initiation apathy questions in the data dictionary are in the other direction. So what we are getting is that being higher the `BCI` factor means having *less* Initiation Apathy. So it's back to front. The same applies to the `Em` factor.   -->\n\n<!-- So actually, all forms of apathy are *positively* correlated (because more of each type is associated with more of the other types).   -->\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nMake a diagram of the model.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nFor a quick look at the structure of the model, try the `semPaths()` function from the **semPlot** package [Chapter 4 CFA#making diagrams](https://uoepsy.github.io/lv/04_cfa.html#making-diagrams){target=\"_blank\"}.\n\nIf you were going to use this sort of diagram in a proper write-up, though, it'd be better to make a nicer graphic manually (e.g., in Powerpoint, your favourite graphics software, or [semdiag](https://semdiag.psychstat.org)).\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nHere's one example:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(semPlot)\nsemPaths(dasmod.est, whatLabels = \"std\", rotation=2)\n```\n\n::: {.cell-output-display}\n![](08ex_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThere are lots of options in `semPaths()`, so if you can make your graphic more elaborate than this one, then be our guest!\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Optional Question 7</div><div class='question-body'>\n\n\n<!-- Much like for EFA, we can estimate individuals' scores on the latent factors. In lavaan, the function `lavPredict()` will get us some estimates.   -->\n\n<!-- However, for a clinician administering the DAS to a patient, this option is not available. Instead, it is common that scores on the individual items associated with a given factor are used to create a sum score or a mean score which can be used in a practical setting (e.g., scores above a given threshold might indicate cause for concern).   -->\n\nImagine that you're a clinician administering the DAS to a patient.\nIn clinical settings, it's common practice to skip the complex factor analysis we've been doing here and just create a sum score or a mean score that describe a patient's responses.\nThen clinicians can check whether the score is above some threshold to see whether there's cause for concern.\n\nFor each of the dimensions of apathy in the data, calculate sum scores for each of the 250 participants.\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nGood ol' `rowSums()` to the rescue!  \n\n:::\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\nHere are the sets of items associated with each dimension: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nExitems <- c(1,6,10,11,17,19,21,23)\nEmitems <- c(3,5,7,9,12,15,20,24)\nBCIitems <- c(2,4,8,13,14,16,18,22)\n```\n:::\n\n\n\n\nAgain, because the item numbers correspond to the column positions in our data, we can just do rowSums indexing on those column numbers to get our scores:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncompl_rdas$ExSCORE <- rowSums(compl_rdas[,Exitems])\ncompl_rdas$EmSCORE <- rowSums(compl_rdas[,Emitems])\ncompl_rdas$BCIScore <- rowSums(compl_rdas[,BCIitems])\n```\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Optional Question 8</div><div class='question-body'>\n\n\nHow might you think about a sum/mean score in terms of a diagram?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nWhat does a sum or mean score imply about how each item is weighted compared to the others?\nHow is this different from what a more sophisticated method like EFA or CFA can do?\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\nComputing sum scores can feel like a 'model free' calculation, but actually it **does** pre-suppose a factor structure, and a much more constrained one than those we have been estimating.\nSpecifically, we're assuming that all items contribute equally to an underlying factor, rather than being weighted differently, and that all items also have the same variance as one another.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/diag_sumscore.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\nFor a full explanation of this idea, see [\"Thinking twice about sum scores\", McNeish & Wolf 2020](https://doi.org/10.3758/s13428-020-01398-0){target=\"_blank\"}. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n<br>\n\n\n\n# \"DOOM\" Scrolling \n\n\n:::frame\n__Dataset: doom.csv__  \n\nThe \"Domains of Online Obsession Measure\" (DOOM) is a fictitious scale that aims to assess the sub types of addictions to online content. It was developed to measure 2 separate domains of online obsession: items 1 to 9 are representative of the \"emotional\" relationships people have with their internet usage (i.e. how it makes them feel), and items 10 to 15 reflect \"practical\" relationship (i.e., how it connects or interferes with their day-to-day life). Each item is measured on a 7-point likert scale from \"strongly disagree\" to \"strongly agree\".  \n\nWe administered this scale to 476 participants in order to assess the validity of the 2 domain structure of the online obsession measure that we obtained during scale development.  \n\nThe data are available at [https://uoepsy.github.io/data/doom.csv](https://uoepsy.github.io/data/doom.csv){target=\"_blank\"}, and the table below shows the individual item wordings.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mzzswjtibl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mzzswjtibl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mzzswjtibl thead, #mzzswjtibl tbody, #mzzswjtibl tfoot, #mzzswjtibl tr, #mzzswjtibl td, #mzzswjtibl th {\n  border-style: none;\n}\n\n#mzzswjtibl p {\n  margin: 0;\n  padding: 0;\n}\n\n#mzzswjtibl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mzzswjtibl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mzzswjtibl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mzzswjtibl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mzzswjtibl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mzzswjtibl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mzzswjtibl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mzzswjtibl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mzzswjtibl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mzzswjtibl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mzzswjtibl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mzzswjtibl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mzzswjtibl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mzzswjtibl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mzzswjtibl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzzswjtibl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mzzswjtibl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mzzswjtibl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mzzswjtibl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzzswjtibl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mzzswjtibl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzzswjtibl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mzzswjtibl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzzswjtibl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mzzswjtibl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzzswjtibl .gt_left {\n  text-align: left;\n}\n\n#mzzswjtibl .gt_center {\n  text-align: center;\n}\n\n#mzzswjtibl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mzzswjtibl .gt_font_normal {\n  font-weight: normal;\n}\n\n#mzzswjtibl .gt_font_bold {\n  font-weight: bold;\n}\n\n#mzzswjtibl .gt_font_italic {\n  font-style: italic;\n}\n\n#mzzswjtibl .gt_super {\n  font-size: 65%;\n}\n\n#mzzswjtibl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mzzswjtibl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mzzswjtibl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mzzswjtibl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mzzswjtibl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mzzswjtibl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mzzswjtibl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mzzswjtibl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mzzswjtibl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"question\">question</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_1</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i just can't stop watching videos of animals</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_2</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i spend hours scrolling through tutorials but never actually attempt any projects.</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_3</td>\n<td headers=\"question\" class=\"gt_row gt_left\">cats are my main source of entertainment.</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_4</td>\n<td headers=\"question\" class=\"gt_row gt_left\">life without the internet would be boring, empty, and joyless</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_5</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i try to hide how long i’ve been online</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_6</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i avoid thinking about things by scrolling on the internet</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_7</td>\n<td headers=\"question\" class=\"gt_row gt_left\">everything i see online is either sad or terrifying</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_8</td>\n<td headers=\"question\" class=\"gt_row gt_left\">all the negative stuff online makes me feel better about my own life</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_9</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i feel better the more 'likes' i receive</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_10</td>\n<td headers=\"question\" class=\"gt_row gt_left\">most of my time online is spent communicating with others</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_11</td>\n<td headers=\"question\" class=\"gt_row gt_left\">my work suffers because of the amount of time i spend online</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_12</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i spend a lot of time online for work</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_13</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i check my emails very regularly</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_14</td>\n<td headers=\"question\" class=\"gt_row gt_left\">others in my life complain about the amount of time i spend online</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">item_15</td>\n<td headers=\"question\" class=\"gt_row gt_left\">i neglect household chores to spend more time online</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nAssess whether the 2 domain model of online obsession provides a good fit to the validation sample of 476 participants.   \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nFrom the visual of the correlation matrix, you can see the vague outline of two groups of items correlations. Note there's a little overlap.. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndoom <- read_csv(\"https://uoepsy.github.io/data/doom.csv\")\nheatmap(cor(doom))\n```\n\n::: {.cell-output-display}\n![](08ex_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nfirst we write our model: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoddoom <- \"\n# emotional domain\nemot =~ item_1 + item_2 + item_3 + item_4 + item_5 + item_6 + item_7 + item_8 + item_9\n# practical domain\npract =~ item_10 + item_11 + item_13 + item_14 + item_15\n# correlated domains (will be estimated by default)\nemot ~~ pract\n\"\n```\n:::\n\n\n\nThen we fit it to the data:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoddoom.est <- cfa(moddoom, data = doom)\n```\n:::\n\n\n\nThen we inspect that fitted model object.   \nI'm just going to extract the fit indices here first.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfitmeasures(moddoom.est)[c(\"rmsea\",\"srmr\",\"cfi\",\"tli\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     rmsea       srmr        cfi        tli \n0.07331272 0.06227484 0.84791972 0.81790388 \n```\n\n\n:::\n:::\n\n\n\nUh-oh.. they don't look great. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nAre there any areas of local misfit (certain parameters that are not in the model (and are therefore fixed to zero) but that could improve model fit _if they were_ estimated?).  \n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nI'm printing out just the `head()`, so that I can look at the few parameters with the greatest modification indices.  \nThe top three parameters jump out immediately to me.  \n`item_1` and `item_3` have a suggested correlation of c0.5, as do `item_7` and `item_8`. In addition, it's suggested that including a loading (estimated to be about 0.6) from `item_10` to the `emot` factor would improve the model fit.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodindices(moddoom.est, sort=TRUE) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        lhs op     rhs     mi    epc sepc.lv sepc.all sepc.nox\n47   item_1 ~~  item_3 88.700  0.560   0.560    0.459    0.459\n32     emot =~ item_10 74.374  1.690   0.817    0.640    0.640\n109  item_7 ~~  item_8 61.930  0.370   0.370    0.432    0.432\n34     emot =~ item_13 14.824 -0.655  -0.317   -0.275   -0.275\n122  item_9 ~~ item_10 12.634  0.145   0.145    0.217    0.217\n135 item_13 ~~ item_15  8.956  0.178   0.178    0.171    0.171\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n\n__Beware:__ there's a slightly blurred line here that we're about to step over, and move from confirmatory back to 'exploratory'.  \n\nLook carefully at the item wordings,do any of the suggested modifications make theoretical sense? Add them to the model and re-fit it. Does this new model fit well?  \n\n\n\nIn this case, the likely reason for the poor fit of the \"DOOM\" scale, is that the person who made the items (ahem, me) doesn't really know anything about the construct they are talking about, and didn't put much care into constructing the items!  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nThere are three main proposed adjustments from our initial model:  \n\n1. `item_1 ~~ item_3`. These questions are both about animals. It would make sense that these are related over and above the underlying \"emotional internet usage\" factor. \n2. `item_7 ~~ item_8`. These are both about viewing negative content online, so it makes sense here that they would be related beyond the 'emotional' factor. \n\n3. `emot =~ item_10`. This item is about communicating with others. It currently loads highly on the `pract` factor too. It maybe makes sense here that \"communicating with others\" will capture both a practical element of internet useage _and_ an emotional one. \n\n\nPutting them all in at once could be a mistake - if we added in `emot =~ item_10`, then we change slightly the underlying construct of the `emot` factor, meaning it might make other suggested modifications (`item_7 ~~ item_8`) less important. It's a bit like [Whac-A-Mole](https://en.wikipedia.org/wiki/Whac-A-Mole){target=\"_blank\"} - you make one modification and then a whole new area of misfits appears!  \n\nLet's adjust our model:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoddoom2 <- \"\n# emotional domain\nemot =~ item_1 + item_2 + item_3 + item_4 + item_5 + item_6 + item_7 + item_8 + item_9 + item_10\n# practical domain\npract =~ item_10 + item_11 + item_13 + item_14 + item_15\n# correlated domains (will be estimated by default)\nemot ~~ pract\n\"\n```\n:::\n\n\n\nThen fit it to the data:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoddoom2.est <- cfa(moddoom2, data = doom)\n\nfitmeasures(moddoom2.est)[c(\"rmsea\",\"srmr\",\"cfi\",\"tli\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     rmsea       srmr        cfi        tli \n0.06013775 0.05147585 0.89901514 0.87747171 \n```\n\n\n:::\n:::\n\n\n\n\nThe fit is still not great, and the same suggested correlations are present in modification indices:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodindices(moddoom2.est, sort=TRUE) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       lhs op     rhs     mi    epc sepc.lv sepc.all sepc.nox\n47  item_1 ~~  item_3 87.679  0.553   0.553    0.455    0.455\n109 item_7 ~~  item_8 61.827  0.365   0.365    0.421    0.421\n43   pract =~  item_7  7.117 -0.300  -0.178   -0.159   -0.159\n48  item_1 ~~  item_4  6.264 -0.139  -0.139   -0.128   -0.128\n117 item_8 ~~ item_10  6.072 -0.110  -0.110   -0.151   -0.151\n44   pract =~  item_8  5.065 -0.244  -0.145   -0.130   -0.130\n```\n\n\n:::\n:::\n\n\n\n\nLet's go ahead and put the covariance between `item_1` and `item_3` in. I personally went for this first because they seem more similar to me than `item_7` and `item_8` do. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoddoom3 <- \"\n# emotional domain\nemot =~ item_1 + item_2 + item_3 + item_4 + item_5 + item_6 + item_7 + item_8 + item_9 + item_10\n# practical domain\npract =~ item_10 + item_11 + item_13 + item_14 + item_15\n# correlated domains (will be estimated by default)\nemot ~~ pract\nitem_1 ~~ item_3\n\"\n\nmoddoom3.est <- cfa(moddoom3, data = doom)\n\nfitmeasures(moddoom3.est)[c(\"rmsea\",\"srmr\",\"cfi\",\"tli\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     rmsea       srmr        cfi        tli \n0.03282045 0.03830848 0.97032291 0.96350520 \n```\n\n\n:::\n:::\n\n\n\n\nWhoop! It fits well! It may well be that if we inspect modification indices again, we still see that `item_7 ~~ item_8` would improve our model fit. The thing to remember however, is that we could simply keep adding parameters until we run out of degrees of freedom, and our model would \"fit better\". But such a model would not be useful. It would not generalise well, because it runs the risk of being overfitted to the nuances of this specific sample.\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n\n\nmcq style\n\nwhich do you think reflects where we're at now with our analysis\n\n- we have confirmed our theoretical measurement model of DOOM scrolling\n- we have confirmed our theoretical measurement model, but with some caveats\n- the measure of doom scrolling is crap\n- \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n# More Conduct Problems \n\n:::frame\n__Data: conduct_problems_2.csv__  \n\nLast week we conducted an exploratory factor analysis of a dataset to try and identify an optimal factor structure for a new measure of conduct (i.e., antisocial behavioural) problems. \n\nThis week, we'll conduct some confirmatory factor analyses (CFA) of the same inventory to assess the extent to which this 2-factor structure fits an independent sample. To do this, we have administered our measure to a new sample of n=600 adolescents. \n\nWe have re-ordered the questionnaire items to be grouped into the two types of behaviours:\n\n::::{.columns}\n:::{.column width=\"47.5%\"}\n__Non-Aggressive Behaviours__  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> item </th>\n   <th style=\"text-align:left;\"> behaviour </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> item 1 </td>\n   <td style=\"text-align:left;\"> Stealing </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 2 </td>\n   <td style=\"text-align:left;\"> Lying </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 3 </td>\n   <td style=\"text-align:left;\"> Skipping school </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 4 </td>\n   <td style=\"text-align:left;\"> Vandalism </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 5 </td>\n   <td style=\"text-align:left;\"> Breaking curfew </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n:::\n:::{.column width=\"5%\"}\n:::\n:::{.column width=\"47.5%\"}\n__Aggressive Behaviours__  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> item </th>\n   <th style=\"text-align:left;\"> behaviour </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> item 6 </td>\n   <td style=\"text-align:left;\"> Threatening others </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 7 </td>\n   <td style=\"text-align:left;\"> Bullying </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 8 </td>\n   <td style=\"text-align:left;\"> Spreading malicious rumours </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 9 </td>\n   <td style=\"text-align:left;\"> Using a weapon </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> item 10 </td>\n   <td style=\"text-align:left;\"> Fighting </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n:::\n::::\n\nThe data are available as a **.csv** at [https://uoepsy.github.io/data/conduct_problems_2.csv](https://uoepsy.github.io/data/conduct_problems_2.csv) \n\n:::\n\n\n\n\n<div class='question-begin'>Question 13</div><div class='question-body'>\n\n\n\n- Read in the data, and take a quick look around (e.g., cor matrix, quick pairs.panels plots etc). \n- Fit the proposed 2 factor model\n- Examine the fit of the 2-factor model of conduct problems to this new sample of 600 adolescents.  \n- Evaluate the fit, and make any model modifications if necessary (and only if you feel that there is substantive support for the modification given the items).  \n- Make a diagram of your model, using the standardised factor loadings as labels.  \n- Make a bullet point list of everything you have done so far, and the resulting conclusions. Then, if you feel like it, turn the bulleted list into written paragraphs, and you'll have a write-up of your analyses!  \n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div style=\"display:none;\">\n\n\n\nHere's the data:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ncp2 <- read_csv(\"https://uoepsy.github.io/data/conduct_problems_2.csv\")\n\ncor(cp2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           item1     item2      item3     item4     item5      item6     item7\nitem1  1.0000000 0.5254249 0.43498606 0.4831121 0.5644047 0.13450795 0.2806369\nitem2  0.5254249 1.0000000 0.50099054 0.5119842 0.6740107 0.15239358 0.3031997\nitem3  0.4349861 0.5009905 1.00000000 0.4897339 0.5990709 0.09463966 0.2557407\nitem4  0.4831121 0.5119842 0.48973386 1.0000000 0.6199783 0.14847703 0.2492471\nitem5  0.5644047 0.6740107 0.59907089 0.6199783 1.0000000 0.11353641 0.3112458\nitem6  0.1345080 0.1523936 0.09463966 0.1484770 0.1135364 1.00000000 0.5461757\nitem7  0.2806369 0.3031997 0.25574075 0.2492471 0.3112458 0.54617567 1.0000000\nitem8  0.2576481 0.2748175 0.19355398 0.2553712 0.2463290 0.59441335 0.8009591\nitem9  0.2444337 0.2759875 0.20798523 0.2260156 0.2333758 0.36915878 0.5988582\nitem10 0.1783069 0.1618631 0.12924914 0.1433759 0.1394748 0.46316014 0.5316143\n           item8     item9    item10\nitem1  0.2576481 0.2444337 0.1783069\nitem2  0.2748175 0.2759875 0.1618631\nitem3  0.1935540 0.2079852 0.1292491\nitem4  0.2553712 0.2260156 0.1433759\nitem5  0.2463290 0.2333758 0.1394748\nitem6  0.5944133 0.3691588 0.4631601\nitem7  0.8009591 0.5988582 0.5316143\nitem8  1.0000000 0.6169829 0.5557168\nitem9  0.6169829 1.0000000 0.3613253\nitem10 0.5557168 0.3613253 1.0000000\n```\n\n\n:::\n:::\n\n\n\n\nJust from the visual, it looks like the same factor structure is present in this sample.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheatmap(cor(cp2), scale = \"none\")\n```\n\n::: {.cell-output-display}\n![](08ex_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThis is our proposed model:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lavaan)\ncpmod <- \"\n  # the non-aggressive problems factor\n  nonagg =~ item1 + item2 + item3 + item4 + item5\n\n  # the aggressive problems factor\n  agg =~ item6 + item7 + item8 + item9 + item10\n\n  # covariance between the two factors\n  # (this is included by default in cfa)\n  agg ~~ nonagg\n\"\n\ncpmod.est <- cfa(cpmod, data = cp2)\n```\n:::\n\n\n\n\nAnd it appears to fit pretty well! \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfitmeasures(cpmod.est)[c(\"srmr\",\"rmsea\",\"cfi\",\"tli\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      srmr      rmsea        cfi        tli \n0.03454489 0.03945991 0.98862263 0.98494172 \n```\n\n\n:::\n:::\n\n\n\n\nWe can check modification indices anyway, but I don't plan on making any adjustments given that it already fits well:  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodindices(cpmod.est, sort = TRUE) |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      lhs op    rhs     mi    epc sepc.lv sepc.all sepc.nox\n72  item6 ~~ item10 10.747  0.082   0.082    0.144    0.144\n25 nonagg =~  item7  8.106  0.119   0.080    0.080    0.080\n65  item5 ~~  item7  6.720  0.039   0.039    0.160    0.160\n71  item6 ~~  item9  6.675 -0.065  -0.065   -0.115   -0.115\n24 nonagg =~  item6  6.100 -0.136  -0.092   -0.094   -0.094\n33    agg =~  item5  5.273 -0.122  -0.075   -0.072   -0.072\n```\n\n\n:::\n:::\n\n\n\n\nIt maybe makes sense that there is some residual covariance between item6 (\"threatening others\") and item10 (\"fighting\"), but it's only a weak correlation (0.14). Not worth adding.  \n\nSo let's get on with making a diagram.\nWe can rotate this however you like. Convention is typically to have it downwards but I like it left to right (not sure why!)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(semPlot)\nsemPaths(cpmod.est, \n        whatLabels = \"std\", \n        rotation = 2)\n```\n\n::: {.cell-output-display}\n![](08ex_files/figure-html/unnamed-chunk-48-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nThe lines from `agg =~ item6` and `nonagg =~ item1` are dotted to indicate that the model was initially fitted with the loading fixed to 1. \n\nBecause we're showing standardised loadings, we could just use the model when fitted with `std.lv=TRUE` just to stop these dotted lines from appearing: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncpmod.est2 <- cfa(cpmod, data = cp2, std.lv = TRUE)\n\nsemPaths(cpmod.est2, \n        whatLabels = \"std\", \n        rotation = 2)\n```\n\n::: {.cell-output-display}\n![](08ex_files/figure-html/unnamed-chunk-49-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nAnd let's give a brief write-up:  \n\n\n*A two-factor model was tested. Items 1-5 loaded on a 'non-aggressive conduct problems' factor and items 6-10 loaded on an 'aggression' factor and these factors were allowed to correlate. Scaling and identification were achieved by fixing the loading of item 1 on the non-aggressive conduct problems factor and item 6 on the aggression factor to 1. The model was estimated using maximum likelihood estimation. The model fit well with CFI=.99, TLI=0.99,  RMSEA=.04, and SRMR=.04 (Hu & Bentler, 1999).  All loadings were statistically significant and >|.3| on the standardised scale. Overall, therefore, a two-factor oblique model was supported for the conduct problems items. The correlation between the factors was $r=.38\\,\\, (p<.001)$.*\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|parameter      |   est| std.est|    se|z      |pvalue  |\n|:--------------|-----:|-------:|-----:|:------|:-------|\n|nonagg=~item1  | 1.000|   0.664| 0.000|       |        |\n|nonagg=~item2  | 1.217|   0.765| 0.076|15.965 |< 0.001 |\n|nonagg=~item3  | 1.012|   0.676| 0.070|14.424 |< 0.001 |\n|nonagg=~item4  | 1.146|   0.706| 0.077|14.967 |< 0.001 |\n|nonagg=~item5  | 1.360|   0.872| 0.078|17.412 |< 0.001 |\n|agg=~item6     | 1.000|   0.636| 0.000|       |        |\n|agg=~item7     | 1.419|   0.878| 0.082|17.331 |< 0.001 |\n|agg=~item8     | 1.437|   0.915| 0.081|17.662 |< 0.001 |\n|agg=~item9     | 1.093|   0.668| 0.077|14.125 |< 0.001 |\n|agg=~item10    | 0.950|   0.608| 0.073|13.073 |< 0.001 |\n|nonagg~~agg    | 0.156|   0.375| 0.023|6.856  |< 0.001 |\n|item1~~item1   | 0.574|   0.559| 0.037|15.398 |< 0.001 |\n|item2~~item2   | 0.477|   0.416| 0.035|13.778 |< 0.001 |\n|item3~~item3   | 0.551|   0.543| 0.036|15.262 |< 0.001 |\n|item4~~item4   | 0.597|   0.501| 0.040|14.867 |< 0.001 |\n|item5~~item5   | 0.264|   0.239| 0.028|9.537  |< 0.001 |\n|item6~~item6   | 0.561|   0.595| 0.035|16.193 |< 0.001 |\n|item7~~item7   | 0.228|   0.229| 0.021|10.767 |< 0.001 |\n|item8~~item8   | 0.153|   0.162| 0.019|8.122  |< 0.001 |\n|item9~~item9   | 0.566|   0.554| 0.035|15.978 |< 0.001 |\n|item10~~item10 | 0.587|   0.630| 0.036|16.351 |< 0.001 |\n|nonagg~~nonagg | 0.453|   1.000| 0.052|8.701  |< 0.001 |\n|agg~~agg       | 0.381|   1.000| 0.045|8.396  |< 0.001 |\n\n\n:::\n:::\n\n\n\n\n<!-- Modification indices and expected parameter changes were inspected but no modifications were made because no expected parameter changes were judged large enough to merit the inclusion of additional parameters given that there was little theoretical rationale for their inclusion. -->\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n",
    "supporting": [
      "08ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}