<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Longitudinal (non-linear)</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>MSMR</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Mixed Effects Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_intromlm.html">1: Intro to Multi-Level Modelling</a>
    </li>
    <li>
      <a href="02_lmm_log.html">2: Logistic | Longitudinal (linear)</a>
    </li>
    <li>
      <a href="03_nonlin.html">3: Longitudinal (non-linear)</a>
    </li>
    <li>
      <a href="04_other_ranef.html">4: Other Random Effect Structures</a>
    </li>
    <li>
      <a href="05_multilevel_recap.html">5: Recap | Individual Differences</a>
    </li>
    <li>
      <a href="06_rev.html">Break Week</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Data Reduction &amp; SEM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_efapca.html">PCA | EFA</a>
    </li>
    <li>
      <a href="08_cfa.html">CFA</a>
    </li>
    <li>
      <a href="09_path.html">Path Analysis</a>
    </li>
    <li>
      <a href="10_sem1.html">SEM 1</a>
    </li>
    <li>
      <a href="11_sem2.html">SEM 2</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa-info-circle"></span>
     
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="00_tidyverse_markdown.html">Recap - Tidyverse &amp; Markdown</a>
    </li>
    <li>
      <a href="zz_writeuplogistic.html">Write-up &amp; Logistic GCA</a>
    </li>
    <li>
      <a href="zz_assumpts.html">MLM Assumptions &amp; Diagnostics</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Longitudinal (non-linear)</h1>

</div>


<div class="red">
<p><strong>Preliminaries</strong></p>
<ol style="list-style-type: decimal">
<li>Open Rstudio, and create a new RMarkdown document (giving it a title for this week).</li>
</ol>
</div>
<div id="background-reading" class="section level1">
<h1>Background &amp; Reading</h1>
<ul>
<li><a href="https://doi.org/10.1080/15248371003699969">Curran et al., 2010</a><br />
</li>
<li><a href="https://doi.org/10.1093/jole/lzv003">Winter &amp; Wieling, 2016</a></li>
</ul>
</div>
<div id="linear-vs-non-linear" class="section level1">
<h1>Linear vs Non-Linear</h1>
<p>We have already seen in the last couple of weeks that we can use MLM to study something ‘over the course of X.’ For instance in Week 1’s weight change data, which was measured over the course of several assessments (Figure <a href="#fig:weightlin">1</a>), and in the novel word learning experiment from Week 2 our analysis was interested in change over the course of the experimental blocks.</p>
<div class="figure" style="text-align: center"><span id="fig:weightlin"></span>
<img src="images/gca/weightchangelin.png" alt="Weight Maintain Model fitted values, from [Week 1 exercises](https://uoepsy.github.io/msmr/labs/01_intromlm.html#Some_Less_Guided_Exercises)" width="300px" />
<p class="caption">
Figure 1: Weight Maintain Model fitted values, from <a href="https://uoepsy.github.io/msmr/labs/01_intromlm.html#Some_Less_Guided_Exercises">Week 1 exercises</a>
</p>
</div>
<p><strong>Longitudinal data</strong> is the term commonly used to refer to any data in which repeated measurements are taken over a continuous domain. This opens up the potential for observations to be unevenly spaced, or missing at certain points, as well as the fact that many effects of interest are likely to display <strong>non-linear patterns</strong>. These exercises focus on including higher-order polynomials in MLM to capture non-linearity.</p>
<div id="motivation" class="section level2">
<h2>Motivation</h2>
Suppose we had collected the data in Figure <a href="#fig:mcycle">2</a>, and we wanted to fit a model to predict <span class="math inline">\(y\)</span> based on the values of <span class="math inline">\(x\)</span>.<br />

<div class="figure" style="text-align: center"><span id="fig:mcycle"></span>
<img src="03_nonlin_files/figure-html/mcycle-1.png" alt="A clearly non-linear pattern" width="80%" />
<p class="caption">
Figure 2: A clearly non-linear pattern
</p>
</div>
<p>A model? <a href="https://youtu.be/7mAFiPVs3tM">Easy, peasy, lemon squeezy!</a> Let’s use our old friend linear regression.
Expand the box below to see the model estimates and plot of model fit.</p>
<div class="optional-begin">
Optional My lovely linear model is the best linear model.<span id="opt-start-53" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-53&#39;, &#39;opt-start-53&#39;)"></span>
</div>
<div id="opt-body-53" class="optional-body" style="display: none;">
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = .)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -81.519 -34.562  -5.292  34.405 101.421 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -110.2848    19.5442  -5.643 3.09e-07 ***
## x              2.7053     0.5456   4.958 4.58e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 46.26 on 72 degrees of freedom
## Multiple R-squared:  0.2545, Adjusted R-squared:  0.2442 
## F-statistic: 24.58 on 1 and 72 DF,  p-value: 4.576e-06</code></pre>
<p><img src="03_nonlin_files/figure-html/mcycle2-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
Job done? Clearly not - we need only overlay model upon raw data (Figure <a href="#fig:mcycle3">3</a>) to see we are missing some key parts of the pattern.
<div class="figure" style="text-align: center"><span id="fig:mcycle3"></span>
<img src="03_nonlin_files/figure-html/mcycle3-1.png" alt="Uh-oh... " width="80%" />
<p class="caption">
Figure 3: Uh-oh…
</p>
</div>
<div class="frame">
<p><strong>Thoughts about Model + Error</strong></p>
<p>All our work here is in aim of making models of the world.</p>
<ol style="list-style-type: decimal">
<li>Models are just models. They are simplifications, and so they don’t perfectly fit to the observed world (indeed, how well a model fits to the world is often our metric for comparing models).<br />
</li>
<li><span class="math inline">\(y - \hat y\)</span>. Our observed data minus our model predicted values (i.e. in linear regression our “residuals”) reflect everything that we don’t account for in our model</li>
<li>In an ideal world, our model accounts for all the systematic relationships, and what is left over (our residuals) is just randomness. If our model is mis-specified, or misses out something systematic, then our residuals will reflect this.</li>
<li>We check for this by examining how much like randomness the residuals appear to be (zero mean, normally distributed, constant variance, i.i.d (“independent and identically distributed”) - i.e., what gets referred to as the “assumptions”).</li>
<li>We will <strong>never</strong> know whether our residuals contain only randomness, because we can never observe <em>everything</em>.</li>
</ol>
<p><h/></p>
<p>Let’s just do a quick <code>plot(model)</code> for some diagnostic plots of my linear model:
<img src="03_nonlin_files/figure-html/unnamed-chunk-2-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Does it look like the residuals are independently distributed? Not really.
We need to find some way of incorporating the non-linear relationship between y and x into our model.</p>
</div>
</div>
</div>
<div id="whats-a-polynomial" class="section level1">
<h1>What’s a polynomial?</h1>
<div class="yellow">
<p>Polynomials are mathematical expressions which involve a sum of powers. For instance:</p>
<p><span class="math inline">\(y = x^2 + 4\)</span><br />
<span class="math inline">\(y = 4x^3 + 2x^2 + 9x\)</span><br />
<span class="math inline">\(y = x^6\)</span></p>
</div>
<p>For our purposes, extending our model to include higher-order terms can fit non-linear relationships between two variables, for instance, fitting models with linear and quadratic terms (<span class="math inline">\(\color{red}{y_i} = \color{blue}{\beta_0 + \beta_1 x_{i} \ + \beta_2 x^2_i} + \varepsilon_i\)</span>) and extending these to cubic (<span class="math inline">\(\color{red}{y_i} = \color{blue}{\beta_0 + \beta_1 x_{i} \ + \beta_2 x^2_i + \beta_3 x^3_i} + \varepsilon_i\)</span>) and beyond.</p>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-3-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div id="rawnatural-polynomials" class="section level2">
<h2>Raw/Natural Polynomials</h2>
<div style="display:inline-block; width: 60%; vertical-align: top">
<p>There are two types of polynomial we can construct. “Raw” (or “Natural”) polynomials are the straightforward ones you might be expecting the table to the right to be filled with.</p>
<p>These are simply the original values of the x variable to the power of 2, 3 and so on.</p>
<p>We can quickly get these in R using the <code>poly()</code> function, with <code>raw = TRUE</code>.</p>
</div>
<div style="display:inline-block; width: 30%;">
<center>
<table style="width:25%;">
<colgroup>
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">x</th>
<th align="center">x^2</th>
<th align="center">x^3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">?</td>
<td align="center">?</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">?</td>
<td align="center">?</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">?</td>
<td align="center">?</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">?</td>
<td align="center">?</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">?</td>
<td align="center">?</td>
</tr>
<tr class="even">
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
</tr>
</tbody>
</table>
</center>
</div>
<pre class="r"><code>poly(1:10, degree = 3, raw=TRUE)</code></pre>
<pre><code>##        1   2    3
##  [1,]  1   1    1
##  [2,]  2   4    8
##  [3,]  3   9   27
##  [4,]  4  16   64
##  [5,]  5  25  125
##  [6,]  6  36  216
##  [7,]  7  49  343
##  [8,]  8  64  512
##  [9,]  9  81  729
## [10,] 10 100 1000
## attr(,&quot;degree&quot;)
## [1] 1 2 3
## attr(,&quot;class&quot;)
## [1] &quot;poly&quot;   &quot;matrix&quot;</code></pre>
<p>We can actually use <code>poly()</code> internally in fitting our linear model, if we want:</p>
<pre class="r"><code>lm(y ~ poly(x, 3, raw = T), data = df)</code></pre>
<p>But note that the coefficients get named <code>poly(x, 3, raw = T)[1]</code>, <code>poly(x, 3, raw = T)[2]</code> etc.<br />
We can alternatively use Dan’s code, which attaches these as columns to our data, named <code>poly1</code>, <code>poly2</code>, etc.</p>
<p>Both will produce the same model output (but Dan’s method produces these nice neat names for the coefficients!):</p>
<pre><code>## 
## Call:
## lm(formula = y ~ poly1 + poly2 + poly3, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -78.749 -16.352  -1.201  20.744  61.827 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.528e+03  1.774e+02  -8.612 1.36e-12 ***
## poly1        1.147e+02  1.512e+01   7.588 1.05e-10 ***
## poly2       -2.764e+00  4.111e-01  -6.724 3.97e-09 ***
## poly3        2.151e-02  3.578e-03   6.013 7.43e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 29.02 on 70 degrees of freedom
## Multiple R-squared:  0.7146, Adjusted R-squared:  0.7024 
## F-statistic: 58.44 on 3 and 70 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>With raw/natural polynomials, the terms <code>poly1</code>, <code>poly2</code> and <code>poly3</code> are correlated.<br />
Think think about why this might be - by definition, as <span class="math inline">\(x^1\)</span> increases, so will <span class="math inline">\(x^2\)</span>, and so will <span class="math inline">\(x^4\)</span> and so on.
We can visualise them:</p>
<pre class="r"><code>matplot(poly(1:10, 3, raw=T), type=&quot;l&quot;)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-9-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>And measure the correlation coefficients</p>
<pre class="r"><code>cor(poly(1:10, 3, raw=T)) %&gt;% round(2)</code></pre>
<pre><code>##      1    2    3
## 1 1.00 0.97 0.93
## 2 0.97 1.00 0.99
## 3 0.93 0.99 1.00</code></pre>
<p>Why might this be a problem?
Well, this multicollinearity can lead to estimation problems, and means that our parameter estimates may change considerably depending upon what terms we include in our model, and it becomes more difficult to determine which ones are important, and what the effect sizes are.
The table below shows the coefficients for models fitted to a randomly generated dataset, with <code>poly1</code>, <code>poly1+poly2</code>, and <code>poly1+poly2+poly3</code> as predictors (where <code>poly1</code>-<code>poly3</code> are <strong>natural</strong> polynomials). Notice that they change with the addition of each term.</p>
<table style="width:86%;">
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="22%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">term</th>
<th align="center">y~poly1</th>
<th align="center">y~poly1+poly2</th>
<th align="center">y~poly1+poly2+poly3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">189.61</td>
<td align="center">-58.78</td>
<td align="center">1.64</td>
</tr>
<tr class="even">
<td align="center">poly1</td>
<td align="center">27.98</td>
<td align="center">152.17</td>
<td align="center">98.58</td>
</tr>
<tr class="odd">
<td align="center">poly2</td>
<td align="center">-</td>
<td align="center">-11.29</td>
<td align="center">0.33</td>
</tr>
<tr class="even">
<td align="center">poly3</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-0.7</td>
</tr>
</tbody>
</table>
</div>
<div id="orthogonal-polynomials" class="section level2">
<h2>Orthogonal Polynomials</h2>
<p>“Orthogonal” polynomials are uncorrelated (hence the name).
We can get these for <span class="math inline">\(x = 1,2,...,9,10\)</span> using the following code:</p>
<pre class="r"><code>poly(1:10, 3, raw = FALSE)</code></pre>
<pre><code>##                 1           2          3
##  [1,] -0.49543369  0.52223297 -0.4534252
##  [2,] -0.38533732  0.17407766  0.1511417
##  [3,] -0.27524094 -0.08703883  0.3778543
##  [4,] -0.16514456 -0.26111648  0.3346710
##  [5,] -0.05504819 -0.34815531  0.1295501
##  [6,]  0.05504819 -0.34815531 -0.1295501
##  [7,]  0.16514456 -0.26111648 -0.3346710
##  [8,]  0.27524094 -0.08703883 -0.3778543
##  [9,]  0.38533732  0.17407766 -0.1511417
## [10,]  0.49543369  0.52223297  0.4534252
## attr(,&quot;coefs&quot;)
## attr(,&quot;coefs&quot;)$alpha
## [1] 5.5 5.5 5.5
## 
## attr(,&quot;coefs&quot;)$norm2
## [1]    1.0   10.0   82.5  528.0 3088.8
## 
## attr(,&quot;degree&quot;)
## [1] 1 2 3
## attr(,&quot;class&quot;)
## [1] &quot;poly&quot;   &quot;matrix&quot;</code></pre>
<p>Notice that the first order term has been scaled, so instead of the values 1 to 10, we have values ranging from -0.5 to +0.5, centered on 0.
Think about what this means for <span class="math inline">\(x^2\)</span>.<br />
It will be uncorrelated with <span class="math inline">\(x\)</span> (because <span class="math inline">\(-0.5^2 = 0.5^2\)</span>)!</p>
<pre class="r"><code>matplot(poly(1:10, 3, raw=F), type=&quot;l&quot;)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-13-1.png" width="80%" style="display: block; margin: auto;" />
The correlations are zero!</p>
<pre class="r"><code>cor(poly(1:10, 3, raw=F)) %&gt;% round(2)</code></pre>
<pre><code>##   1 2 3
## 1 1 0 0
## 2 0 1 0
## 3 0 0 1</code></pre>
<p>With some minor edits to Dan’s code (<code>orthogonal = TRUE</code>):</p>
<pre class="r"><code>df &lt;- code_poly(df = df, predictor = &#39;x&#39;, poly.order = 3, orthogonal = TRUE, draw.poly = FALSE)</code></pre>
<p>We can then fit the same models <code>y~poly1</code>, <code>y~poly1+poly2</code>, and <code>y~poly1+poly2+poly3</code> as predictors (where <code>poly1</code>-<code>poly3</code> are now <strong>orthogonal</strong> polynomials), and see that estimated coefficients do not change between models:</p>
<table style="width:86%;">
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="22%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">term</th>
<th align="center">y~poly1</th>
<th align="center">y~poly1+poly2</th>
<th align="center">y~poly1+poly2+poly3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">343.49</td>
<td align="center">343.49</td>
<td align="center">343.5</td>
</tr>
<tr class="even">
<td align="center">poly1</td>
<td align="center">254.12</td>
<td align="center">254.12</td>
<td align="center">254.1</td>
</tr>
<tr class="odd">
<td align="center">poly2</td>
<td align="center">-</td>
<td align="center">-259.44</td>
<td align="center">-259.4</td>
</tr>
<tr class="even">
<td align="center">poly3</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-39.14</td>
</tr>
</tbody>
</table>
<div class="green">
<p><strong>Remember what zero is!</strong></p>
<p>With orthogonal polynomials, you need to be careful about interpreting coefficients. For raw polynomials the intercept remains the y-intercept (i.e., where the line hits the y-axis). The higher order terms can then be thought of from that starting point - e.g., “where <span class="math inline">\(x\)</span> is 2, <span class="math inline">\(\hat y\)</span> is <span class="math inline">\(\beta_0 + \beta_1 \cdot 2 + \beta_2 \cdot 2^2 + \beta_3 \cdot 2^3 ...\)</span>”<br />
For orthogonal polynomials, the interpretation becomes more tricky. The intercept is the overall average of y, the linear predictor is the linear change pivoting around the mean of <span class="math inline">\(x\)</span> (rather than <span class="math inline">\(x = 0\)</span>), the quadratic term corresponds to the steepness of the quadratic curvature (“how curvy is it?”), the cubic term to the steepness at the inflection points (“how wiggly is it?”), and so on.</p>
</div>
<div class="yellow">
<p><strong>Quadratic curves</strong></p>
<div class="figure" style="text-align: center"><span id="fig:quadfig"></span>
<img src="03_nonlin_files/figure-html/quadfig-1.png" alt="Positive and negative quadratic terms" width="80%" />
<p class="caption">
Figure 4: Positive and negative quadratic terms
</p>
</div>
<div class="optional-begin">
Code to create plot<span id="opt-start-54" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-54&#39;, &#39;opt-start-54&#39;)"></span>
</div>
<div id="opt-body-54" class="optional-body" style="display: none;">
<pre class="r"><code>tibble(
  x = -10:10,
  y = x^2,
  y1 = -x^2
) %&gt;% pivot_longer(y:y1) %&gt;%
  mutate(name = ifelse(name==&quot;y&quot;,&quot;quadratic term is positive \n Y = X^2&quot;, &quot;quadratic term is negative \n Y = -X^2&quot;)) %&gt;%
  ggplot(.,aes(x=x,y=value,col=name)) +
  geom_line()+
  guides(col=FALSE)+
  facet_wrap(~name, scales=&quot;free_y&quot;)</code></pre>
</div>
<p class="optional-end">
</p>
</div>
</div>
</div>
<div id="exercises-cognitive-performance" class="section level1">
<h1>Exercises: Cognitive performance</h1>
<div class="optional-begin">
Az.rda Data codebook<span id="opt-start-55" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-55&#39;, &#39;opt-start-55&#39;)"></span>
</div>
<div id="opt-body-55" class="optional-body" style="display: none;">
<p>30 Participants with probably Alzheimer’s Disease completed 3 tasks over 10 time points: A memory task, and two scales investigating ability to undertake complex activities of daily living (cADL) and simple activities of daily living (sADL). Performance on all of tasks was calculated as a percentage of total possible score, thereby ranging from 0 to 100.</p>
<p>The data is available at <a href="https://uoepsy.github.io/data/Az.rda">https://uoepsy.github.io/data/Az.rda</a>.</p>
<table style="width:65%;">
<colgroup>
<col width="19%" />
<col width="45%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">variable</th>
<th align="center">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Subject</td>
<td align="center">Unique Subject Identifier</td>
</tr>
<tr class="even">
<td align="center">Time</td>
<td align="center">Time point of the study (0 to
10)</td>
</tr>
<tr class="odd">
<td align="center">Task</td>
<td align="center">Task type (Memory, cADL, sADL)</td>
</tr>
<tr class="even">
<td align="center">Performance</td>
<td align="center">Score on test</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question A1
</div>
<div class="question-body">
<p>There are lots of different ways to organise your file system/your life in R.<br />
You might be creating a new project each week, or a new folder, or just a new .Rmd.</p>
<p>There’s no <em>best</em> way to organise this - it is personal preference.
However, one thing which appears to be common across most approaches is that having a lot of irrelevant stuff in your environment (top right pane) can get confusing and messy.</p>
<p>We encourage you now to clear your environment for this week, and <em>then</em> load in the data.</p>
<p>If you are worried that you are going to lose some of the objects in your environment, then this may be a sign that you are not using R to its full potential. The idea is that we can recreate all of our analyses by just running the relevant script!</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-56" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-56&#39;, &#39;sol-start-56&#39;)"></span>
</div>
<div id="sol-body-56" class="solution-body" style="display: none;">
<pre class="r"><code>load(url(&quot;https://uoepsy.github.io/data/Az.rda&quot;))
summary(Az)</code></pre>
<pre><code>##     Subject         Time          Task      Performance   
##  1      : 30   Min.   : 1.0   cADL  :300   Min.   : 2.00  
##  2      : 30   1st Qu.: 3.0   sADL  :300   1st Qu.:40.00  
##  3      : 30   Median : 5.5   Memory:300   Median :52.00  
##  4      : 30   Mean   : 5.5                Mean   :49.27  
##  5      : 30   3rd Qu.: 8.0                3rd Qu.:61.00  
##  6      : 30   Max.   :10.0                Max.   :85.00  
##  (Other):720</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Packages &amp; Functions
</div>
<div class="question-body">
<p>Alongside <strong>lme4</strong> and <strong>tidyverse</strong> and possibly <strong>broom.mixed</strong>, we’re going to be using some of Dan’s useful functions for getting p-values and coding polynomials. Load these now.</p>
<div class="yellow">
<p><strong>The secret source()</strong></p>
<p>The <code>source()</code> function basically takes in R code and evaluates it. You can download R scripts with Dan’s code <a href="https://uoepsy.github.io/msmr/functions/get_pvalues.R">here</a> and <a href="https://uoepsy.github.io/msmr/functions/code_poly.R">here</a>.</p>
<p>But you can also source them directly from the URLs, which runs the R code and creates the functions in your environment:</p>
<pre class="r"><code>library(tidyverse)
library(lme4)
library(broom.mixed)
source(&#39;https://uoepsy.github.io/msmr/functions/get_pvalues.R&#39;)
source(&quot;https://uoepsy.github.io/msmr/functions/code_poly.R&quot;)</code></pre>
</div>
<p class="question-end">
</p>
</div>
<div class="question-begin">
Question A2
</div>
<div class="question-body">
<p>No modelling just yet.<br />
Plot the performance over time for each type of task.</p>
<p>Try using <code>stat_summary</code> so that you are plotting the means (and standard errors) of each task, rather than every single data point. Why? Because this way you can get a shape of the overall trajectories of performance over time in each task.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-57" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-57&#39;, &#39;sol-start-57&#39;)"></span>
</div>
<div id="sol-body-57" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(Az, aes(Time, Performance, color=Task, fill=Task)) + 
  stat_summary(fun.data=mean_se, geom=&quot;ribbon&quot;, color=NA, alpha=0.5) +
  stat_summary(fun=mean, geom=&quot;line&quot;)</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-21-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A3
</div>
<div class="question-body">
<p>Why do you think <em>natural</em> polynomials might be more useful for these data?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-58" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-58&#39;, &#39;sol-start-58&#39;)"></span>
</div>
<div id="sol-body-58" class="solution-body" style="display: none;">
<p>Because we’re likely to be interested in whether there are task differences at the starting baseline point</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A4
</div>
<div class="question-body">
<p>Fit a model!</p>
<p>Steps:</p>
<ol style="list-style-type: decimal">
<li><p>Add 1st and 2nd order natural polynomials to the data using the <code>code_poly()</code> function.</p></li>
<li><p>Create a “baseline model,” in which performance varies over time (with both linear and quadratic change), but no differences in Task are estimated.</p>
<ul>
<li>Think about your random effect structure - what are the observations grouped by? Are observations nested? What is the maximal model?</li>
</ul></li>
<li><p>Create a new model with a fixed effect of Task</p></li>
<li><p>Create a new model in which performance varies linearly over time between Task type.</p></li>
<li><p>Create a new model in which linear and quadratic performance over time varies between Task type.</p></li>
<li><p>Run model comparisons.</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-59" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-59&#39;, &#39;sol-start-59&#39;)"></span>
</div>
<div id="sol-body-59" class="solution-body" style="display: none;">
<pre class="r"><code># prep for analysis
Az &lt;- code_poly(Az, predictor=&quot;Time&quot;, poly.order=2, orthogonal=F, draw.poly = F)

# fit the full model incrementally
m.base &lt;- lmer(Performance ~ (poly1 + poly2) +
                 (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task),
               data=Az, REML=F)
m.0 &lt;- lmer(Performance ~ (poly1 + poly2) + Task +
              (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task),
            data=Az, REML=F)
m.1 &lt;- lmer(Performance ~ poly1*Task + poly2 +
              (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task),
            data=Az, REML=F)
m.Az.full &lt;- lmer(Performance ~ (poly1 + poly2)*Task + 
                  (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task), 
                data=Az, REML=F)
anova(m.base, m.0, m.1, m.Az.full)</code></pre>
<pre><code>## Data: Az
## Models:
## m.base: Performance ~ (poly1 + poly2) + (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task)
## m.0: Performance ~ (poly1 + poly2) + Task + (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task)
## m.1: Performance ~ poly1 * Task + poly2 + (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task)
## m.Az.full: Performance ~ (poly1 + poly2) * Task + (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task)
##           npar    AIC    BIC  logLik deviance    Chisq Df Pr(&gt;Chisq)    
## m.base      16 3804.6 3881.5 -1886.3   3772.6                           
## m.0         18 3807.8 3894.2 -1885.9   3771.8   0.8565  2     0.6517    
## m.1         20 3781.2 3877.3 -1870.6   3741.2  30.5288  2  2.348e-07 ***
## m.Az.full   22 3612.9 3718.5 -1784.4   3568.9 172.3610  2  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A5
</div>
<div class="question-body">
<p>Look at the <code>summary()</code> of your full model, and try using the <code>get_pvalues()</code> function on it.</p>
<p>Which terms show significant differences between task types?</p>
<div class="optional-begin">
Hint: if you want to see the full model we fitted in Question A4 above<span id="opt-start-60" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-60&#39;, &#39;opt-start-60&#39;)"></span>
</div>
<div id="opt-body-60" class="optional-body" style="display: none;">
<p>This is the model we fitted for Question 4, step 5 (“in which linear and quadratic performance over time varies between Task type.”).</p>
<p>If you don’t understand how we got here, come to a drop-in session!</p>
<pre class="r"><code>m.Az.full &lt;- lmer(Performance ~ (poly1 + poly2)*Task + 
                  (poly1 + poly2 | Subject) + (poly1 + poly2 | Subject:Task), 
                data=Az, REML=F)</code></pre>
</div>
<p class="optional-end">
</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-61" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-61&#39;, &#39;sol-start-61&#39;)"></span>
</div>
<div id="sol-body-61" class="solution-body" style="display: none;">
<p>Get p-values for your full model:</p>
<pre class="r"><code>get_pvalues(m.Az.full)</code></pre>
<pre><code>##                      Estimate Std..Error     t.value     p.normal p.normal.star
## (Intercept)      67.161666667 0.92644546  72.4939242 0.000000e+00           ***
## poly1            -3.287803030 0.34117668  -9.6366581 0.000000e+00           ***
## poly2             0.009469697 0.01243445   0.7615693 4.463171e-01              
## TasksADL          0.095000000 0.81156449   0.1170579 9.068142e-01              
## TaskMemory        1.240000000 0.81156449   1.5279131 1.265341e-01              
## poly1:TasksADL    1.362196970 0.26755380   5.0913012 3.556146e-07           ***
## poly1:TaskMemory -3.977070707 0.26755380 -14.8645646 0.000000e+00           ***
## poly2:TasksADL   -0.013257576 0.01747758  -0.7585476 4.481232e-01              
## poly2:TaskMemory  0.338888889 0.01747758  19.3899219 0.000000e+00           ***</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A6
</div>
<div class="question-body">
<table>
<colgroup>
<col width="27%" />
<col width="12%" />
<col width="15%" />
<col width="11%" />
<col width="14%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std..Error</th>
<th align="center">t.value</th>
<th align="center">p.normal</th>
<th align="center">p.normal.star</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">67.16</td>
<td align="center">0.9264</td>
<td align="center">72.49</td>
<td align="center">0</td>
<td align="center">***</td>
</tr>
<tr class="even">
<td align="center"><strong>poly1</strong></td>
<td align="center">-3.288</td>
<td align="center">0.3412</td>
<td align="center">-9.637</td>
<td align="center">0</td>
<td align="center">***</td>
</tr>
<tr class="odd">
<td align="center"><strong>poly2</strong></td>
<td align="center">0.00947</td>
<td align="center">0.01243</td>
<td align="center">0.7616</td>
<td align="center">0.4463</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center"><strong>TasksADL</strong></td>
<td align="center">0.095</td>
<td align="center">0.8116</td>
<td align="center">0.1171</td>
<td align="center">0.9068</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center"><strong>TaskMemory</strong></td>
<td align="center">1.24</td>
<td align="center">0.8116</td>
<td align="center">1.528</td>
<td align="center">0.1265</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center"><strong>poly1:TasksADL</strong></td>
<td align="center">1.362</td>
<td align="center">0.2676</td>
<td align="center">5.091</td>
<td align="center">3.556e-07</td>
<td align="center">***</td>
</tr>
<tr class="odd">
<td align="center"><strong>poly1:TaskMemory</strong></td>
<td align="center">-3.977</td>
<td align="center">0.2676</td>
<td align="center">-14.86</td>
<td align="center">0</td>
<td align="center">***</td>
</tr>
<tr class="even">
<td align="center"><strong>poly2:TasksADL</strong></td>
<td align="center">-0.01326</td>
<td align="center">0.01748</td>
<td align="center">-0.7585</td>
<td align="center">0.4481</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center"><strong>poly2:TaskMemory</strong></td>
<td align="center">0.3389</td>
<td align="center">0.01748</td>
<td align="center">19.39</td>
<td align="center">0</td>
<td align="center">***</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li>For the cADL Task, what is the estimated average performance where x = 0?<br />
</li>
<li>For the sADL and Memory Tasks, is the estimated average where x = 0 different to the cADL Task?</li>
<li>For the cADL Task, how does performance change for every increasing time point? (what is the estimated linear slope?)
<ul>
<li>Note, the quadratic term <code>poly2</code> is non-significant, so we’ll ignore it here<br />
</li>
</ul></li>
<li>For the sADL Task, how is the change in performance over time different from the cADL Task?</li>
<li>The answer to c) + the answer to d) will give you the estimated slope for the sADL Task.</li>
<li>For the Memory Task, how is the change in performance over time different from the cADL Task?
<ul>
<li>This is more difficult. The quadratic term is significant.</li>
<li>Recall the direction of the quadratic term (positive/negative) and how this relates to the visual curvature (see Figure <a href="#fig:quadfig">4</a>).</li>
</ul></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-62" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-62&#39;, &#39;sol-start-62&#39;)"></span>
</div>
<div id="sol-body-62" class="solution-body" style="display: none;">
<ol style="list-style-type: lower-alpha">
<li>For the cADL Task, what is the estimated average performance where x = 0?
<ul>
<li>67.16</li>
</ul></li>
<li>For the sADL and Memory Tasks, is the estimated average where x = 0 different to the cADL Task?
<ul>
<li>Nope. Neither of the intercept differences are significant.</li>
</ul></li>
<li>For the cADL Task, how does performance change for every increasing time point? (what is the estimated linear slope?)
<ul>
<li>Note, the quadratic term <code>poly2</code> is non-significant, so we’ll ignore it here<br />
</li>
<li>For every increase in one timepoint, cADL performance changes by -3.29.</li>
</ul></li>
<li>For the sADL Task, how is the change in performance over time different from the cADL Task?
<ul>
<li>For every increase in one timepoint sADL performance change is 1.36 different from change in cADL</li>
</ul></li>
<li>The answer to c) + the answer to d) will give you the estimated slope for the sADL Task.
<ul>
<li>-3.29 + 1.36 = -1.927803</li>
<li>For every increase in one timepoint, sADL performance changes by -1.93</li>
</ul></li>
<li>For the Memory Task, how is the change in performance over time different from the cADL Task?
<ul>
<li>This is more difficult. The quadratic term is significant.</li>
<li>Recall the direction of the quadratic term (positive/negative) and how this relates to the visual curvature (see Figure <a href="#fig:quadfig">4</a>).</li>
<li>Memory performance declines even more steeply than cADL, with linear change of -3.29 + -3.98 = -7.267803, but it also has a quadratic effect of 0.34. This is positive, which means it is <span class="math inline">\(\cup\)</span>-shaped (rather than <span class="math inline">\(\cap\)</span>-shaped).</li>
</ul></li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A7
</div>
<div class="question-body">
<p>Based on your answers above, can you sketch out (on paper) the model fit?</p>
<p>Then provide a written description.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-63" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-63&#39;, &#39;sol-start-63&#39;)"></span>
</div>
<div id="sol-body-63" class="solution-body" style="display: none;">
<p>TODO INCLUDE VIDEO</p>
<div class="int">
<p>Performance in all tasks starts out the same [thanks, natural polynomials!]. Linear change over time is different depending on task type: compared to complex ADL tasks, decline in simple ADL tasks is slower and decline in Memory is faster. Decline in cADL and sADL tasks is approximately linear, whereas decline in Memory has more curvature (reaching floor?)</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A8
</div>
<div class="question-body">
<p>To what extent do model comparisons (Question A4) and the parameter-specific p-values (Question A5) yield the same results?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-64" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-64&#39;, &#39;sol-start-64&#39;)"></span>
</div>
<div id="sol-body-64" class="solution-body" style="display: none;">
<p>Model comparisons suggest:</p>
<ul>
<li>Linear slopes are different: <span class="math inline">\(\chi^2(2)=30.56, p &lt;&lt; 0.0001\)</span> (comparison <code>m.0</code> and <code>m.1</code> above).<br />
</li>
<li>Quadratic term is different: <span class="math inline">\(\chi^2(2)=172.36, p &lt;&lt; 0.0001\)</span> (comparison <code>m.1</code> and <code>m.Az.full</code> above).</li>
</ul>
<p><em>Note:</em> We can’t investigate the intercept difference via the model comparisons above. Comparison between <code>m.base</code> and <code>m.0</code> indicates difference holding polynomial terms constant (not the conditional effect where poly1 and poly2 are 0).**</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A9
</div>
<div class="question-body">
<p>Plot the model fitted values. This might be pretty similar to the plot you created in Question A2, and (hopefully) similar to the one you drew on paper for Question A7.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-65" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-65&#39;, &#39;sol-start-65&#39;)"></span>
</div>
<div id="sol-body-65" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(Az, aes(Time, Performance, color=Task)) + 
  stat_summary(fun.data=mean_se, geom=&quot;pointrange&quot;) + 
  stat_summary(fun=mean, geom=&quot;line&quot;, aes(y=fitted(m.Az.full)))</code></pre>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-26-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="frame">
<p>Two quotes</p>
<p>“all models are wrong. some are useful.” <a href="https://www.tandfonline.com/doi/abs/10.1080/01621459.1976.10480949">(George Box, 1976)</a>.</p>
<p>“…it does not seem helpful just to say that all models are wrong. The very word model implies simplification and idealization. The idea that complex physical, biological or sociological systems can be exactly described by a few formulae is patently absurd. The construction of idealized representations that capture important stable aspects of such systems is, however, a vital part of general scientific analysis and statistical models, especially substantive ones, do not seem essentially different from other kinds of model.”<a href="https://twitter.com/richarddmorey/status/1111270300241588225">(Sir David Cox, 1995)</a>.</p>
</div>
<div class="optional-begin">
Optional: TIMTOWTDI<span id="opt-start-66" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-66&#39;, &#39;opt-start-66&#39;)"></span>
</div>
<div id="opt-body-66" class="optional-body" style="display: none;">
<p><strong>TIMTOWTDI</strong> <em>(There is more than one way to do it)</em></p>
<p>The approach we are learning about in this course is only one of many approaches to studying non-linearity.
Some alternatives, which you may come across in future work, are listed below.</p>
<p><strong>Piecewise linear regression:</strong> fit a linear model with cut point(s) along x (determine cut points by greatest reduction in mean squared error <span class="math inline">\(\sigma\)</span>)
<img src="03_nonlin_files/figure-html/unnamed-chunk-27-1.png" width="350px" style="display: block; margin: auto;" /></p>
<p><strong>Piecewise polynomial</strong> fit the model <span class="math inline">\(y ~ x + x^2 + x^3\)</span> to equal chunks of x.</p>
<p><img src="03_nonlin_files/figure-html/unnamed-chunk-28-1.png" width="350px" style="display: block; margin: auto;" /></p>
<p><strong>Splines, penalised splines &amp; GAMS</strong></p>
<p>This begins to open a huge can of worms, but if you foresee yourself needing these sort of tools, then Simon Wood, author of the <strong>mgcv</strong> R package for fitting generalised additive models (GAMS), is now in the maths department at Edinburgh. He has plenty of materials on <a href="https://www.maths.ed.ac.uk/~swood34/talks/snw-Koln.pdf">his webpage</a> (Warning, these are fairly technical). There are also a reasonable number of tutorials <a href="https://www.google.com/search?hl=&amp;site=&amp;q=gam+in+r+tutorial">online which are really good</a>.<br />
<img src="03_nonlin_files/figure-html/unnamed-chunk-29-1.png" width="350px" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
