---
title: "Week 5 Exercises: Assumptions, Diagnostics, Writing up"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false
source('assets/setup.R')
library(xaringanExtra)
library(tidyverse)
library(patchwork)
library(ggdist)
xaringanExtra::use_panelset()
qcounter <- function(){
  if(!exists("qcounter_i")){
    qcounter_i <<- 1
  }else{
    qcounter_i <<- qcounter_i + 1
  }
  qcounter_i
}
library(lme4)
```



`r qbegin(qcounter())`
conduct an analysis to address the research aims!  

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`

`r solend()`

`r qbegin(qcounter())`
check the assumptions of your model

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`

`r solend()`

`r qbegin(qcounter())`
check the extent to which your results may be sensitive to certain influential Xs or XXs. 
`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`

`r solend()`



`r qbegin(qcounter())`
Write a short description of the sample data.  


`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`


`r solend()`


`r qbegin(qcounter())`
Write a short explanation of your methods


::: {.callout-tip collapse="true"}
#### Hints

- explain transformations to the data prior to modelling
- explain the model(s) fitted and how they address the research aims
- describe any actions taken as a result of non-convergence
- what estimation method was used (ML, REML)? What software (including version and packages)? What optimiser? 
- if degrees of freedom were used, what kind? If not, how are inferences conducted?  
- what assumptions of the model were checked, and what was the outcome?


:::


`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`

`r solend()`


`r qbegin(qcounter())`
write a short summary of your results, along with suitable visualisations and tables


::: {.callout-tip collapse="true"}
#### Hints

- if model comparisons were conducted, provide results and what they mean  
- present and interpret fixed effects estimates that are relevant to the research aim.  
- discuss random effect estimates - does the relevant effect vary a lot between clusters?  
- was the sensitivty of the results to influential observations/clusters assessed? if so, what did you find?


:::


`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`

`r solend()`



