---
title: "MSMR"
---

These readings and walkthroughs show how we can extend the linear model to analyses of "hierarchical data", in which observations are clustered in higher-level groups (e.g. trials within participants, or students within schools). We see how these methods lend themselves well to longitudinal data, and we present one of the more traditional approaches to studying non-linear change over time. The assumptions underlying these models are discussed, along with certain considerations that are important to bear in mind especially for observational data.  

These readings and walkthroughs introduce the essential tools for analysing questionnaire and other psychological measurement data, focusing on the concept of "latent variables" --- constructs that cannot be directly observed (e.g., "anxiety", "intelligence" etc.). The topics covered introduce data reduction via Principal Component Analysis (PCA), before moving to look at Exploratory Factor Analysis (EFA), as a method to understand the underlying dimensionality that best explains a set of observed relationships. We then transition to Confirmatory Factor Analysis (CFA) for testing specific theoretical models of measurement, before extending the logic to the powerful framework of Structural Equation Modeling (SEM).   


Readings and walkthroughs are presented with accompanying R code.  

