{
  "hash": "10f4ba16d6919e24b43dcddd935fca99",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 9 Exercises: Path Analysis & Mediation\"\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n# Education, Skills, and Salary\n\n\n:::frame\n__Dataset: edskillsalary.csv__  \n\n\n\n\n\n\n\n\n\nWe sampled 500 people who were all 5 years out of their last year of education. All participants completed an extensive questionnaire to ascertain the number of skills of potential interest to employers each participant perceived themselves to have. This resulted in a \"Skillset Metric\".  \n5 years later, participants were followed up and asked to provide their current salaries. 110 participants failed to respond to follow-ups and thus the final sample included 390 people.  \n\nThe data are available at [https://uoepsy.github.io/data/edskillsalary.csv](https://uoepsy.github.io/data/edskillsalary.csv){target=\"_blank\"}.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fgbjnpxgpo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fgbjnpxgpo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fgbjnpxgpo thead, #fgbjnpxgpo tbody, #fgbjnpxgpo tfoot, #fgbjnpxgpo tr, #fgbjnpxgpo td, #fgbjnpxgpo th {\n  border-style: none;\n}\n\n#fgbjnpxgpo p {\n  margin: 0;\n  padding: 0;\n}\n\n#fgbjnpxgpo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fgbjnpxgpo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fgbjnpxgpo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fgbjnpxgpo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fgbjnpxgpo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fgbjnpxgpo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fgbjnpxgpo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fgbjnpxgpo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fgbjnpxgpo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fgbjnpxgpo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fgbjnpxgpo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fgbjnpxgpo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fgbjnpxgpo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fgbjnpxgpo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fgbjnpxgpo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgbjnpxgpo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fgbjnpxgpo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fgbjnpxgpo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fgbjnpxgpo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgbjnpxgpo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fgbjnpxgpo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgbjnpxgpo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fgbjnpxgpo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgbjnpxgpo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fgbjnpxgpo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgbjnpxgpo .gt_left {\n  text-align: left;\n}\n\n#fgbjnpxgpo .gt_center {\n  text-align: center;\n}\n\n#fgbjnpxgpo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fgbjnpxgpo .gt_font_normal {\n  font-weight: normal;\n}\n\n#fgbjnpxgpo .gt_font_bold {\n  font-weight: bold;\n}\n\n#fgbjnpxgpo .gt_font_italic {\n  font-style: italic;\n}\n\n#fgbjnpxgpo .gt_super {\n  font-size: 65%;\n}\n\n#fgbjnpxgpo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fgbjnpxgpo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fgbjnpxgpo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fgbjnpxgpo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fgbjnpxgpo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fgbjnpxgpo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fgbjnpxgpo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fgbjnpxgpo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fgbjnpxgpo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Educ</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of years of education undertaken</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Skill</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Skillset metric (scores listed from a 100 item list of skills deemed relevant to employers)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Salary</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Salary (in thousands of £)</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nRead in the dataset.  \nLet's suppose that the only statistical machinery available to us is the good old regression models with `lm()`, and we are interested in the estimated effect of education on salary.    \n\nWhich model are you going to fit?  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(Salary ~ Educ, data = ... )\nlm(Salary ~ Skill + Educ, data = ... )\n```\n:::\n\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-1' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-1', 'sol-start-1')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-1\" style=\"display: none;\">\n\n\n\nHere's the data: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nedskill <- read_csv(\"https://uoepsy.github.io/data/edskillsalary.csv\")\n```\n:::\n\n\n\n\nI'm going to fit both models so that we can discuss them below\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1 <- lm(Salary ~ Educ, data = edskill)\nm2 <- lm(Salary ~ Skill + Educ, data = edskill)\n# model tables side by side\nsjPlot::tab_model(m1,m2)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Salary</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Salary</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7\">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">21.88</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">15.98&nbsp;&ndash;&nbsp;27.77</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">20.15</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">14.39&nbsp;&ndash;&nbsp;25.91</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Educ</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.14</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.77&nbsp;&ndash;&nbsp;1.51</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.48</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.03&nbsp;&ndash;&nbsp;0.92</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>0.035</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">Skill</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.16&nbsp;&ndash;&nbsp;0.37</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">390</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">390</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.085 / 0.083</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.141 / 0.136</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n\n<br>\n\nSo we have got two quite different pictures. The first model says that for every additional year of education, the salary offered would be £1140 more. The second model says it would only be £480 more, and it looks like skills are also important for getting a good salary, right?  \n\nBut this makes it sound like \"Education\" and \"Skills\" are things that we can compare the effects of independently. The implicit model we are referring to when using `lm(Salary ~ Skill + Educ)` is in the left hand diagram, Model A, of @fig-educ. But does it not make a lot more sense to think that education is a cause of peoples' levels of skills (especially as the skill level being measured 5 years after their last year of education precludes the opposite direction). In other words, does Model B in @fig-educ not make more sense?  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Two theoretical models of process that gives rise to the data](images/path_educ.png){#fig-educ fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n::::{.columns}\n:::{.column width=\"80%\"}\nWhat Model B suggests is that part of *how* education influences peoples' salaries is by giving them more skills. A perfect example is that you are all now on your way to becoming proficient R users! \n:::\n:::{.column width=\"5%\"}\n:::\n:::{.column width=\"15%\"}\n![](images/new-skill-unlocked.gif)\n:::\n::::\n\nThis is a great example that illustrates instances we might **not** want to include a variable in our model. If you are interested in \"what does having an extra year of education do for peoples' salaries?\", then controlling for skill in our model actually _removes_ that part of the mechanism by which education influences salary.  \n\n\n::: {.callout-note collapse=\"true\"}\n#### another example\n\nTo make this point super clear, suppose we were testing some drug that reduces blood pressure in order to lower the risk of cardiac arrest. \nWe do an experiment where we gave some people the drug, and some people a placebo, then after a year we measured their blood pressure, and then we followed up 5 years later to see how many experienced cardiac arrests.  \n\nThe diagram to show how these variable relate is clearly the one in @fig-pathdrugmed  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A drug aimed at reducing cardiac arrests by lowering blood pressure. The faint grey line indicates the path that would be estimated if we attempted to control for post-treatment blood-pressure](images/path_drug.png){#fig-pathdrugmed fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nIf we fitted the model `lm(cardiac_arrest ~ blood_pressure + drug)`, then the estimated coefficient we get for `drug` will be the effect of the drug on cardiac arrests that *isn't* due to how it changes blood pressure. But that is exactly the opposite of what we want, because we think the drug works specifically by lowering blood pressure!  \n\nContrast this with another example, where we do not run an experiment and allocate people into \"drug\" or \"placebo\", we simply observe a whole load of people who either do or do not take the drug, and we follow them up to see how many have cardiac arrests. **But**, it is generally older people who take the drug, whereas younger people do not. In addition, older people have a higher risk of cardiac arrests. So our model is that seen in @fig-pathdrugcon.  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![We are interested in a drug aimed at reducing cardiac arrests. Older people are more likely to take the drug, and are also more likely to experience cardiac arrest](images/path_drug_con.png){#fig-pathdrugcon fig-align='center' width=80%}\n:::\n:::\n\n\n\n\nIn this case, controlling for the third variable `age` is the right thing to do.  \nIf we do not control for age, and fit the model `lm(cardiac_arrest ~ drug)`, then the coefficient for `drug` will be biased because the group who take the drug are on average older, and thus will tend to experience more cardiac arrests. If the imbalance of age between the drug and no-drug groups is great enough, it could even look like the drug is making cardiac arrests _more_ likely!  \n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\nInstead, let's suppose we are actually interested in the mechanism of _how_ education influences salary. Do more educated people tend to have higher salaries in part because of the skills obtained during their education?  \n\nFit a path model in which education has an effect on salary both directly and indirectly, via its influence on the skills obtained (i.e., model B in @fig-educ)\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nwe have an outcome Y, a predictor X, and a mediator M:  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- \"\nY ~ X + M\nM ~ X\n\"\n```\n:::\n\n\n\n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod1 <- \"\nSalary ~ Educ + Skill\nSkill ~ Educ\n\"\n\nmod1.est <- sem(mod1, data = edskill)\nsummary(mod1.est)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-20 ended normally after 1 iteration\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         5\n\n  Number of observations                           390\n\nModel Test User Model:\n                                                      \n  Test statistic                                 0.000\n  Degrees of freedom                                 0\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nRegressions:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  Salary ~                                            \n    Educ              0.479    0.225    2.127    0.033\n    Skill             0.266    0.053    5.017    0.000\n  Skill ~                                             \n    Educ              2.481    0.175   14.175    0.000\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .Salary          129.722    9.290   13.964    0.000\n   .Skill           118.754    8.504   13.964    0.000\n```\n\n\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nWhile the model in the previous question better reflects our theoretical notions of how these variables are actually related, we would ideally get out an estimate of the indirect effect.  \n\nEdit your model formula from the previous question to also estimate both the total and the indirect effects.  \n\nThen re-fit the model, estimating the parameters using bootstrapping.  \nIs the association between education and salary mediated by skills? What proportion of the effect is mediated?  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nYou'll need to add some labels to the existing paths, and then define the indirect and total effects - see [Chapter 7#mediation-in-lavaan](https://uoepsy.github.io/lv/07_mediation.html#mediation-in-lavaan){target=\"_blank\"}.  \n\n:::\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod1 <- \"\nSalary ~ c*Educ + b*Skill\nSkill ~ a*Educ\n\nindirect := a*b\ntotal := a*b + c\n\"\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod1.est <- sem(mod1, data = edskill, se = \"bootstrap\")\n```\n:::\n\n\n\n<p style=\"color:red;font-size:0.8em\">Warning message:<br>\nIn lav_model_nvcov_bootstrap(lavmodel = lavmodel, lavsamplestats = lavsamplestats,  :<br>\n  lavaan WARNING: 8 bootstrap runs failed or did not converge.</p>\n\nNote that we get a warning here, but it's not too much to worry about. It tells us that 8 (out of 1000) of the bootstraps has failed to converge. This means our bootstrapped estimates are really based on 992 bootstrap draws (and so a write up would need to clearly report this).  \nIf this number was bigger (e.g. 10% or 20% of the bootstraps failed) then we it would be more of a cause for concern.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod1.est, ci = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-20 ended normally after 1 iteration\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         5\n\n  Number of observations                           390\n\nModel Test User Model:\n                                                      \n  Test statistic                                 0.000\n  Degrees of freedom                                 0\n\nParameter Estimates:\n\n  Standard errors                            Bootstrap\n  Number of requested bootstrap draws             1000\n  Number of successful bootstrap draws             990\n\nRegressions:\n                   Estimate  Std.Err  z-value  P(>|z|) ci.lower ci.upper\n  Salary ~                                                              \n    Educ       (c)    0.479    0.229    2.096    0.036    0.010    0.918\n    Skill      (b)    0.266    0.054    4.887    0.000    0.159    0.374\n  Skill ~                                                               \n    Educ       (a)    2.481    0.168   14.798    0.000    2.134    2.826\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|) ci.lower ci.upper\n   .Salary          129.722   10.220   12.693    0.000  108.806  148.937\n   .Skill           118.754    8.139   14.591    0.000  103.382  135.392\n\nDefined Parameters:\n                   Estimate  Std.Err  z-value  P(>|z|) ci.lower ci.upper\n    indirect          0.659    0.135    4.873    0.000    0.398    0.929\n    total             1.138    0.189    6.032    0.000    0.752    1.488\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe relationship between education and salary **is** mediated by skill level! We have a significant indirect effect of 0.66, 95% CI [0.4, 0.93].  \n\nThe total effect of education on salary is 1.14, and the indirect effect is 0.66.  \n$\\frac{0.66}{1.14} = 0.58$, so 58% of the effect is mediated by the influence that education has on skillset and skillset has on salary. \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nNothing to code here, just spend a little time to get to grips with what the different parts of the model represent:  \n\nif you can, write down for explanation of each of:  \n\n- a\n- b\n- the total effect\n- the direct effect\n- the indirect effect\n\n![](images/path_educparts.png)\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\n\n- **a: ** this is the estimated number of skills you acquire for every additional year of education. So each year of education tends to lead to acquiring 2.48 new skills.  \n\n- **b: ** this is the estimated increase in salary for every additional skill you have, if you hold years of education constant. So if you just keep your years of education the same, but teach yourself an extra skill, we'd expect your salary to increase by £270  \n\n- **the direct effect: ** this is the estimated increase in salary for every additional year of education, holding number of skills constant. Imagine that you didn't show up to any classes for your masters degree (and so you didn't learn any new skills), but we still gave you the certificate at the end. Having that bit of paper means we expect you to earn £480 more (compared to someone who has the same skill set as you but doesn't have the extra year of education).  \n\n- **the total effect: ** this is the estimated increase in salary for every additional year of education. So by doing your masters degree, we'd expect your salary to be £1140 higher than someone without a masters degree. It will be higher partly because of the skills you acquire (the indirect effect) and partly because of just having the certificate (the direct effect)\n\n- **the indirect effect: ** this is the estimated increase in salary due to the skills you tend to acquire for every additional year of education. To put this another way, imagine that during your masters degree, you come to classes and obtain the various skills that tend to be gained from a masters, but then you never get round to finishing, so you never get your certificate. We would expect your salary to be £659 higher than someone who didn't do the masters degree.  \n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n  \n\nIn order for us to accurately estimate mediation effects, a few conditions have to be met. One of the biggest is that of **no confounding.**\n\nAn unmeasured variable that is a common cause of both X and Y will bias the total and direct effects, and one that is a common cause of both X and M will bias the indirect effect (it will bias the X$\\rightarrow$M path). Randomised experiments (i.e. randomly allocating people to different values of X) will avoid this, because nothing but the random allocation would cause X. However, confounding of the indirect effect can also happen if some variable is a common cause of both M and Y, and it is hard to randomly allocate to a mediator^[there _are_ methods that attempt to \"block\" a mediator, or to manipulate X in multiple ways in order to increase or decrease the mediators' effect. If you're interested see [*Design approaches to experimental mediation*, Pirlott & MacKinnon 2016](https://doi.org/10.1016/j.jesp.2015.09.012){target=\"_blank\"}].  \n\nCan you think of two unmeasured variables that could be in the place of the variables indicated by `?` in @fig-blanks and may be confounding our estimates.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![fill in the blanks!](images/path_educ_conf_blank.png){#fig-blanks fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\n\nHere are my suggestions. Even if we don't believe that it _should_, something like \"socioeconomic status\" can likely influence both peoples' levels of education (people from wealthier backgrounds have more access to more years of education) and their eventual salary (social connections might lead to better paying jobs, etc.).  \n\nSimilarly, aspects of peoples' employment post-education will influence the skills they have _and_ their salary. For instance, some people might leave education and go into private industry jobs with lots of options for on-the-job training and 'upskilling'. This will lead to more skills, but could also lead to being promoted and therefore having a higher salary! \n\n![](images/path_educ_conf_example.png)\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n  \nAnother assumption of our model here is that there is no \"X-M interaction\". By this, I mean that we are assuming that the effect of the mediator M on the outcome Y does not depend on the level of the predictor X.  \n\nThink: what would an X-M interaction mean in this example?  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n  \n\n\nIn our example of Educ$\\rightarrow$Skill$\\rightarrow$Salary, the \"X-M interaction\" would refer to the idea that the number of skills has a different effect on salaries depending on the level of education.  \n\nIntuitively to me this actually seems like a pretty important possibility!  \nSkills may well have a bigger bearing on salaries for people with lower levels of education. It's probably easier to think about this if we split Education into a binary thing. It's quite likely that in reality, there is an interaction like the picture below, where the number of skills tends to 'matter more' (i.e. lead to more of a difference in salaries) for people with less education.  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09ex_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n<br>\n\n# More Conduct Problems  \n\n:::frame\n__Dataset: conductprobteach.csv__  \n\nThus far, we have explored the underlying structure of a scale of adolescent 'conduct problems' [(PCA & EFA exercises)](07ex.html#conduct-problems){target=\"_blank\"} and we then tested this measurement model when the scale was administered to a further sample [(CFA exericses)](08ex.html#conduct-problems){target=\"_blank\"}.  \n\nThis week, we are looking at whether there are associations between conduct problems (both aggressive and non-aggressive) and academic performance and whether the relations are mediated by the quality of relationships with teachers. We collected data on 557 adolescents as they entered school. Their responses to the conduct problem scale were summed to create a scale score. Two years later, we followed up these students, and obtained measures of Academic performance and of their relationship quality with their teachers. Standardised scale scores were created for both of these measures.  \n\nThe data are available at [https://uoepsy.github.io/data/conductprobteach.csv](https://uoepsy.github.io/data/conductprobteach.csv){target=\"_blank\"}  \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hciwcvsyam\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hciwcvsyam table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hciwcvsyam thead, #hciwcvsyam tbody, #hciwcvsyam tfoot, #hciwcvsyam tr, #hciwcvsyam td, #hciwcvsyam th {\n  border-style: none;\n}\n\n#hciwcvsyam p {\n  margin: 0;\n  padding: 0;\n}\n\n#hciwcvsyam .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hciwcvsyam .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hciwcvsyam .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hciwcvsyam .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hciwcvsyam .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hciwcvsyam .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hciwcvsyam .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hciwcvsyam .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hciwcvsyam .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hciwcvsyam .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hciwcvsyam .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hciwcvsyam .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hciwcvsyam .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hciwcvsyam .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hciwcvsyam .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hciwcvsyam .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hciwcvsyam .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hciwcvsyam .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hciwcvsyam .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hciwcvsyam .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hciwcvsyam .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hciwcvsyam .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hciwcvsyam .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hciwcvsyam .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hciwcvsyam .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hciwcvsyam .gt_left {\n  text-align: left;\n}\n\n#hciwcvsyam .gt_center {\n  text-align: center;\n}\n\n#hciwcvsyam .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hciwcvsyam .gt_font_normal {\n  font-weight: normal;\n}\n\n#hciwcvsyam .gt_font_bold {\n  font-weight: bold;\n}\n\n#hciwcvsyam .gt_font_italic {\n  font-style: italic;\n}\n\n#hciwcvsyam .gt_super {\n  font-size: 65%;\n}\n\n#hciwcvsyam .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hciwcvsyam .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hciwcvsyam .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hciwcvsyam .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hciwcvsyam .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hciwcvsyam .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hciwcvsyam .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hciwcvsyam .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hciwcvsyam div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ID</td>\n<td headers=\"description\" class=\"gt_row gt_left\">participant ID</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Acad</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Academic performance (average grade (0-100) based on all available assessments)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Teach_r</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Teacher relationship quality (sum score based on the Teacher-Child-Relationship (TCR) scale - 7 items on a 5-point likert)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Non_agg</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Non-Aggressive conduct problems (sum score based on items 1-5 of the 10 item conduct problems scale - 5 items on a 5-point likert)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">Agg</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Aggressive conduct problems (sum score based on items 6-10 of the 10 item conduct problems scale - 5 items on a 5-point likert)</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n:::\n\n\n\n\n\n<div class='question-begin'>Question 7</div><div class='question-body'>\n\n\nAs a little exercise before we get started, let's just show ourselves that we can use __lavaan__ to estimate all sorts of models, including a multiple regression model. \n\nLet's first just explore the total effects of the two types of conduct problems on academic achievement.  \n\nThe code below fits the same model using `sem()` and using `lm()`. Examine the `summary()` output for both models, and spot the similarities.  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# read in data\ncp_teach <- read_csv(\"https://uoepsy.github.io/data/conductprobteach.csv\")\n\n# a straightforward multiple regression model\nm1_lm <- lm(Acad ~ Non_agg + Agg, data = cp_teach)\n\n# the same model fitted in lavaan\nm1_lav <- 'Acad ~ Non_agg + Agg'\nm1_lav.est <- sem(m1_lav, data = cp_teach)\n```\n:::\n\n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m1_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Acad ~ Non_agg + Agg, data = cp_teach)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-35.758  -7.511   0.254   7.796  38.735 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  89.0801     2.9339  30.362  < 2e-16 ***\nNon_agg      -0.7641     0.2405  -3.177  0.00157 ** \nAgg          -1.3123     0.2340  -5.607 3.24e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.28 on 554 degrees of freedom\nMultiple R-squared:  0.1922,\tAdjusted R-squared:  0.1893 \nF-statistic:  65.9 on 2 and 554 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(m1_lav.est)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-20 ended normally after 1 iteration\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         3\n\n  Number of observations                           557\n\nModel Test User Model:\n                                                      \n  Test statistic                                 0.000\n  Degrees of freedom                                 0\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nRegressions:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  Acad ~                                              \n    Non_agg          -0.764    0.240   -3.185    0.001\n    Agg              -1.312    0.233   -5.623    0.000\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .Acad            150.012    8.989   16.688    0.000\n```\n\n\n:::\n:::\n\n\n\n\nWe can see that both non-aggressive and aggressive conduct problems significantly predict academic performance. The coefficients from the `lm()` are exactly the same as the estimates under the \"Regressions\" section of the model fitted with `sem()`.^[Note that the model fitted with `sem()` provides $Z$ values instead of the $t$-values in regression models. This is because `sem()` fits models with maximum likelihood thereby assuming a reasonably large sample size.] \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n<div class='question-begin'>Question 8</div><div class='question-body'>\n\n\nMake a sketch for a model in which **both** aggressive and non-aggressive conduct problems have indirect (via teacher relationships) and direct effects on academic performance.  \n\nSketch the path diagram on a piece of paper, or use a website like [https://semdiag.psychstat.org/](https://semdiag.psychstat.org/){target=\"_blank\"} or [https://www.diagrams.net/](https://www.diagrams.net/){target=\"_blank\"}.  \n\n\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-8' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-8', 'sol-start-8')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-8\" style=\"display: none;\">\n\n\n\nThere are many ways in which you could position the variables in your diagram, so the two path diagrams below are equivalent:\n\n::::{.panelset}\n:::{.panel}\n### Option A\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/msmr-w8-b1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n\n:::\n:::{.panel}\n### Option B\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/msmr-w8-b2.png){fig-align='center' width=85%}\n:::\n:::\n\n\n\n:::\n::::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 9</div><div class='question-body'>\n\n\nNow specify the model in R, taking care to also define the parameters for the indirect and total effects.  \n\nMake sure to define the indirect effects and total effects. Then estimate the model by bootstrapping.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nyou'll need more labels than just a, b, and c!  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n\n<div class=\"solution-begin\"><button id='sol-start-9' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\nWe now have two predictors, one mediator and one outcome (and two indirect effects, one for each predictor). We can represent this in two lines: one where we specify academic performance as the outcome variable and one where we specify teacher relationships (the mediator) as the outcome variable. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod2 <- '\n    Acad ~ c_A*Agg + c_NA*Non_agg + b*Teach_r\n    Teach_r ~ a_A*Agg + a_NA*Non_agg\n    \n    #indirect effect for aggressive conduct problems\n    ind_agg := a_A*b \n    #indirect effect for non-aggressive conduct problems\n    ind_nonagg := a_NA*b \n    \n    # total effects\n    tot_agg := a_A*b + c_A\n    tot_nonagg := a_NA*b + c_NA\n'\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod2.est <- sem(mod2,  data=cp_teach, se='bootstrap')\n```\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 10</div><div class='question-body'>\n\n\nGiven that the measures we are using here all have fairly uninterpretable scales (i.e., what does being 1 higher on `Agg` really represent?), we might prefer standardised coefficients instead.  \n\nYou can get these using `standardizedSolution(model)`.  \n\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n\n<div class=\"solution-begin\"><button id='sol-start-10' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstandardizedSolution(mod2.est)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          lhs op         rhs      label est.std    se       z pvalue ci.lower\n1        Acad  ~         Agg        c_A  -0.166 0.060  -2.754  0.006   -0.284\n2        Acad  ~     Non_agg       c_NA  -0.083 0.059  -1.396  0.163   -0.198\n3        Acad  ~     Teach_r          b   0.270 0.060   4.473  0.000    0.152\n4     Teach_r  ~         Agg        a_A  -0.502 0.035 -14.338  0.000   -0.570\n5     Teach_r  ~     Non_agg       a_NA  -0.326 0.036  -9.036  0.000   -0.397\n6        Acad ~~        Acad              0.778 0.031  24.991  0.000    0.717\n7     Teach_r ~~     Teach_r              0.411 0.022  18.351  0.000    0.368\n8         Agg ~~         Agg              1.000 0.000      NA     NA    1.000\n9         Agg ~~     Non_agg              0.703 0.000      NA     NA    0.703\n10    Non_agg ~~     Non_agg              1.000 0.000      NA     NA    1.000\n11    ind_agg :=       a_A*b    ind_agg  -0.135 0.032  -4.299  0.000   -0.197\n12 ind_nonagg :=      a_NA*b ind_nonagg  -0.088 0.022  -3.993  0.000   -0.131\n13    tot_agg :=   a_A*b+c_A    tot_agg  -0.301 0.053  -5.728  0.000   -0.404\n14 tot_nonagg := a_NA*b+c_NA tot_nonagg  -0.171 0.057  -3.017  0.003   -0.282\n   ci.upper\n1    -0.048\n2     0.033\n3     0.388\n4    -0.433\n5    -0.256\n6     0.839\n7     0.455\n8     1.000\n9     0.703\n10    1.000\n11   -0.074\n12   -0.045\n13   -0.198\n14   -0.060\n```\n\n\n:::\n:::\n\n\n\n\nWe can see that the 95% confidence intervals for both indirect effects do not include zero, therefore, we can conclude that they are significant at the $\\alpha = .05$ level. \n\n::: red\n__Note__\n\nThe confidence intervals computed using bootstrapping may be slightly different for you. This is normal, as bootstrap is based on random sampling!\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 11</div><div class='question-body'>\n\n\nNow visualise the estimated model and its parameters using the `semPaths()` function from the **semPlot** package.  \n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-11' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# to include the parameter estimates we set what='est' or what='std'\nlibrary(semPlot)\nsemPaths(mod2.est, whatLabels = \"std\")\n```\n\n::: {.cell-output-display}\n![](09ex_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 12</div><div class='question-body'>\n\n\nWrite a brief paragraph reporting on the results of the model estimates. Include a Figure or Table to display the parameter estimates.  \n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-12' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-12', 'sol-start-12')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-12\" style=\"display: none;\">\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n:::int \n\nA path mediation model was used to test the direct and indirect effects (via teacher relationship quality) of aggressive and non-aggressive conduct problems on academic performance. In the model, academic performance was regressed on teacher relationship quality, non-aggressive conduct problems and aggressive conduct problems while teacher relationship quality (the mediator) was regressed on aggressive and non-aggressive conduct problems. The indirect effects were tested using the product of the coefficient for the regression of outcome on mediator and the coefficient for the regression of mediator on predictor. The statistical significance of the indirect effects were evaluated using bootstrapped 95% confidence intervals with 1000 bootstrap samples.\n\nStandardised parameter estimates are provided in @fig-pathcp. Solid lines indicate that a parameter is significant at the 5% significance level, while dashed lines represent non-significant paths. Total effects of both non-aggressive and aggressive conduct problems on academic performance were significant and negative, indicating that both conduct problem domains were associated with poorer academic outcomes. \n\nThe indirect effects of both conduct problem domains on academic performance via teacher-relationship quality were statistically significant ($\\beta = -0.088,\\, 95\\%\\, CI\\, [-0.131, -0.045]$ and $\\beta = -0.135\\, [-0.197, -0.074]$ for non-aggressive and aggressive conduct problems respectively). The direct effect of non-aggressive conduct problems was not significant ($\\beta = -0.083\\,[-0.198, 0.033]$), suggesting that teacher-relationship quality fully mediated the relationship between non-aggressive conduct problems and academic performance. In contrast, teacher-relationship quality only partially mediated the effect of aggressive conduct problems (proportion mediated = 45%), as a significant direct effect on academic performance remained ($\\beta = -0.166\\, [-0.284, -0.048]$). These results suggest that while both types of conduct problems impact academics through the teacher-student bond, aggressive behaviors may also carry additional, direct risks to academic success that are independent of the teacher-student relationship.  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Effect of conduct problems on academic performance mediated by quality of teacher relationship. Standardised estimates presented](images/path_analy_revstd.png){#fig-pathcp fig-align='center' width=1200px}\n:::\n:::\n\n\n\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "09ex_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.3.0/panelset.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/panelset-0.3.0/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}